// Code generated by ent, DO NOT EDIT.

package sample

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the sample type in the database.
	Label = "sample"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTsUnixMs holds the string denoting the ts_unix_ms field in the database.
	FieldTsUnixMs = "ts_unix_ms"
	// FieldTargetLabel holds the string denoting the target_label field in the database.
	FieldTargetLabel = "target_label"
	// FieldTargetKind holds the string denoting the target_kind field in the database.
	FieldTargetKind = "target_kind"
	// FieldTargetHost holds the string denoting the target_host field in the database.
	FieldTargetHost = "target_host"
	// FieldTargetPort holds the string denoting the target_port field in the database.
	FieldTargetPort = "target_port"
	// FieldSuccess holds the string denoting the success field in the database.
	FieldSuccess = "success"
	// FieldRttMs holds the string denoting the rtt_ms field in the database.
	FieldRttMs = "rtt_ms"
	// FieldError holds the string denoting the error field in the database.
	FieldError = "error"
	// Table holds the table name of the sample in the database.
	Table = "samples"
)

// Columns holds all SQL columns for sample fields.
var Columns = []string{
	FieldID,
	FieldTsUnixMs,
	FieldTargetLabel,
	FieldTargetKind,
	FieldTargetHost,
	FieldTargetPort,
	FieldSuccess,
	FieldRttMs,
	FieldError,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TargetLabelValidator is a validator for the "target_label" field. It is called by the builders before save.
	TargetLabelValidator func(string) error
)

// OrderOption defines the ordering options for the Sample queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTsUnixMs orders the results by the ts_unix_ms field.
func ByTsUnixMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTsUnixMs, opts...).ToFunc()
}

// ByTargetLabel orders the results by the target_label field.
func ByTargetLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetLabel, opts...).ToFunc()
}

// ByTargetKind orders the results by the target_kind field.
func ByTargetKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetKind, opts...).ToFunc()
}

// ByTargetHost orders the results by the target_host field.
func ByTargetHost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetHost, opts...).ToFunc()
}

// ByTargetPort orders the results by the target_port field.
func ByTargetPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetPort, opts...).ToFunc()
}

// BySuccess orders the results by the success field.
func BySuccess(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccess, opts...).ToFunc()
}

// ByRttMs orders the results by the rtt_ms field.
func ByRttMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRttMs, opts...).ToFunc()
}

// ByError orders the results by the error field.
func ByError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldError, opts...).ToFunc()
}
