// Code generated by ent, DO NOT EDIT.

package appconfig

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the appconfig type in the database.
	Label = "app_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPingIntervalSec holds the string denoting the ping_interval_sec field in the database.
	FieldPingIntervalSec = "ping_interval_sec"
	// FieldFlushIntervalSec holds the string denoting the flush_interval_sec field in the database.
	FieldFlushIntervalSec = "flush_interval_sec"
	// FieldPingTimeoutMs holds the string denoting the ping_timeout_ms field in the database.
	FieldPingTimeoutMs = "ping_timeout_ms"
	// FieldRetentionRawDays holds the string denoting the retention_raw_days field in the database.
	FieldRetentionRawDays = "retention_raw_days"
	// FieldRetention1minDays holds the string denoting the retention_1min_days field in the database.
	FieldRetention1minDays = "retention_1min_days"
	// FieldRetention5minDays holds the string denoting the retention_5min_days field in the database.
	FieldRetention5minDays = "retention_5min_days"
	// FieldWifiSampleEnabled holds the string denoting the wifi_sample_enabled field in the database.
	FieldWifiSampleEnabled = "wifi_sample_enabled"
	// Table holds the table name of the appconfig in the database.
	Table = "app_configs"
)

// Columns holds all SQL columns for appconfig fields.
var Columns = []string{
	FieldID,
	FieldPingIntervalSec,
	FieldFlushIntervalSec,
	FieldPingTimeoutMs,
	FieldRetentionRawDays,
	FieldRetention1minDays,
	FieldRetention5minDays,
	FieldWifiSampleEnabled,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPingIntervalSec holds the default value on creation for the "ping_interval_sec" field.
	DefaultPingIntervalSec float64
	// DefaultFlushIntervalSec holds the default value on creation for the "flush_interval_sec" field.
	DefaultFlushIntervalSec int
	// DefaultPingTimeoutMs holds the default value on creation for the "ping_timeout_ms" field.
	DefaultPingTimeoutMs int
	// DefaultRetentionRawDays holds the default value on creation for the "retention_raw_days" field.
	DefaultRetentionRawDays int
	// DefaultRetention1minDays holds the default value on creation for the "retention_1min_days" field.
	DefaultRetention1minDays int
	// DefaultRetention5minDays holds the default value on creation for the "retention_5min_days" field.
	DefaultRetention5minDays int
	// DefaultWifiSampleEnabled holds the default value on creation for the "wifi_sample_enabled" field.
	DefaultWifiSampleEnabled bool
)

// OrderOption defines the ordering options for the AppConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPingIntervalSec orders the results by the ping_interval_sec field.
func ByPingIntervalSec(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPingIntervalSec, opts...).ToFunc()
}

// ByFlushIntervalSec orders the results by the flush_interval_sec field.
func ByFlushIntervalSec(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFlushIntervalSec, opts...).ToFunc()
}

// ByPingTimeoutMs orders the results by the ping_timeout_ms field.
func ByPingTimeoutMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPingTimeoutMs, opts...).ToFunc()
}

// ByRetentionRawDays orders the results by the retention_raw_days field.
func ByRetentionRawDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetentionRawDays, opts...).ToFunc()
}

// ByRetention1minDays orders the results by the retention_1min_days field.
func ByRetention1minDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetention1minDays, opts...).ToFunc()
}

// ByRetention5minDays orders the results by the retention_5min_days field.
func ByRetention5minDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetention5minDays, opts...).ToFunc()
}

// ByWifiSampleEnabled orders the results by the wifi_sample_enabled field.
func ByWifiSampleEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWifiSampleEnabled, opts...).ToFunc()
}
