// Code generated by ent, DO NOT EDIT.

package appconfig

import (
	"entgo.io/ent/dialect/sql"
	"github.com/sid-technologies/vigil/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldID, id))
}

// PingIntervalSec applies equality check predicate on the "ping_interval_sec" field. It's identical to PingIntervalSecEQ.
func PingIntervalSec(v float64) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldPingIntervalSec, v))
}

// FlushIntervalSec applies equality check predicate on the "flush_interval_sec" field. It's identical to FlushIntervalSecEQ.
func FlushIntervalSec(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldFlushIntervalSec, v))
}

// PingTimeoutMs applies equality check predicate on the "ping_timeout_ms" field. It's identical to PingTimeoutMsEQ.
func PingTimeoutMs(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldPingTimeoutMs, v))
}

// RetentionRawDays applies equality check predicate on the "retention_raw_days" field. It's identical to RetentionRawDaysEQ.
func RetentionRawDays(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldRetentionRawDays, v))
}

// Retention1minDays applies equality check predicate on the "retention_1min_days" field. It's identical to Retention1minDaysEQ.
func Retention1minDays(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldRetention1minDays, v))
}

// Retention5minDays applies equality check predicate on the "retention_5min_days" field. It's identical to Retention5minDaysEQ.
func Retention5minDays(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldRetention5minDays, v))
}

// WifiSampleEnabled applies equality check predicate on the "wifi_sample_enabled" field. It's identical to WifiSampleEnabledEQ.
func WifiSampleEnabled(v bool) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldWifiSampleEnabled, v))
}

// PingIntervalSecEQ applies the EQ predicate on the "ping_interval_sec" field.
func PingIntervalSecEQ(v float64) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldPingIntervalSec, v))
}

// PingIntervalSecNEQ applies the NEQ predicate on the "ping_interval_sec" field.
func PingIntervalSecNEQ(v float64) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldPingIntervalSec, v))
}

// PingIntervalSecIn applies the In predicate on the "ping_interval_sec" field.
func PingIntervalSecIn(vs ...float64) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldPingIntervalSec, vs...))
}

// PingIntervalSecNotIn applies the NotIn predicate on the "ping_interval_sec" field.
func PingIntervalSecNotIn(vs ...float64) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldPingIntervalSec, vs...))
}

// PingIntervalSecGT applies the GT predicate on the "ping_interval_sec" field.
func PingIntervalSecGT(v float64) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldPingIntervalSec, v))
}

// PingIntervalSecGTE applies the GTE predicate on the "ping_interval_sec" field.
func PingIntervalSecGTE(v float64) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldPingIntervalSec, v))
}

// PingIntervalSecLT applies the LT predicate on the "ping_interval_sec" field.
func PingIntervalSecLT(v float64) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldPingIntervalSec, v))
}

// PingIntervalSecLTE applies the LTE predicate on the "ping_interval_sec" field.
func PingIntervalSecLTE(v float64) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldPingIntervalSec, v))
}

// FlushIntervalSecEQ applies the EQ predicate on the "flush_interval_sec" field.
func FlushIntervalSecEQ(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldFlushIntervalSec, v))
}

// FlushIntervalSecNEQ applies the NEQ predicate on the "flush_interval_sec" field.
func FlushIntervalSecNEQ(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldFlushIntervalSec, v))
}

// FlushIntervalSecIn applies the In predicate on the "flush_interval_sec" field.
func FlushIntervalSecIn(vs ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldFlushIntervalSec, vs...))
}

// FlushIntervalSecNotIn applies the NotIn predicate on the "flush_interval_sec" field.
func FlushIntervalSecNotIn(vs ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldFlushIntervalSec, vs...))
}

// FlushIntervalSecGT applies the GT predicate on the "flush_interval_sec" field.
func FlushIntervalSecGT(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldFlushIntervalSec, v))
}

// FlushIntervalSecGTE applies the GTE predicate on the "flush_interval_sec" field.
func FlushIntervalSecGTE(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldFlushIntervalSec, v))
}

// FlushIntervalSecLT applies the LT predicate on the "flush_interval_sec" field.
func FlushIntervalSecLT(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldFlushIntervalSec, v))
}

// FlushIntervalSecLTE applies the LTE predicate on the "flush_interval_sec" field.
func FlushIntervalSecLTE(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldFlushIntervalSec, v))
}

// PingTimeoutMsEQ applies the EQ predicate on the "ping_timeout_ms" field.
func PingTimeoutMsEQ(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldPingTimeoutMs, v))
}

// PingTimeoutMsNEQ applies the NEQ predicate on the "ping_timeout_ms" field.
func PingTimeoutMsNEQ(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldPingTimeoutMs, v))
}

// PingTimeoutMsIn applies the In predicate on the "ping_timeout_ms" field.
func PingTimeoutMsIn(vs ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldPingTimeoutMs, vs...))
}

// PingTimeoutMsNotIn applies the NotIn predicate on the "ping_timeout_ms" field.
func PingTimeoutMsNotIn(vs ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldPingTimeoutMs, vs...))
}

// PingTimeoutMsGT applies the GT predicate on the "ping_timeout_ms" field.
func PingTimeoutMsGT(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldPingTimeoutMs, v))
}

// PingTimeoutMsGTE applies the GTE predicate on the "ping_timeout_ms" field.
func PingTimeoutMsGTE(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldPingTimeoutMs, v))
}

// PingTimeoutMsLT applies the LT predicate on the "ping_timeout_ms" field.
func PingTimeoutMsLT(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldPingTimeoutMs, v))
}

// PingTimeoutMsLTE applies the LTE predicate on the "ping_timeout_ms" field.
func PingTimeoutMsLTE(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldPingTimeoutMs, v))
}

// RetentionRawDaysEQ applies the EQ predicate on the "retention_raw_days" field.
func RetentionRawDaysEQ(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldRetentionRawDays, v))
}

// RetentionRawDaysNEQ applies the NEQ predicate on the "retention_raw_days" field.
func RetentionRawDaysNEQ(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldRetentionRawDays, v))
}

// RetentionRawDaysIn applies the In predicate on the "retention_raw_days" field.
func RetentionRawDaysIn(vs ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldRetentionRawDays, vs...))
}

// RetentionRawDaysNotIn applies the NotIn predicate on the "retention_raw_days" field.
func RetentionRawDaysNotIn(vs ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldRetentionRawDays, vs...))
}

// RetentionRawDaysGT applies the GT predicate on the "retention_raw_days" field.
func RetentionRawDaysGT(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldRetentionRawDays, v))
}

// RetentionRawDaysGTE applies the GTE predicate on the "retention_raw_days" field.
func RetentionRawDaysGTE(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldRetentionRawDays, v))
}

// RetentionRawDaysLT applies the LT predicate on the "retention_raw_days" field.
func RetentionRawDaysLT(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldRetentionRawDays, v))
}

// RetentionRawDaysLTE applies the LTE predicate on the "retention_raw_days" field.
func RetentionRawDaysLTE(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldRetentionRawDays, v))
}

// Retention1minDaysEQ applies the EQ predicate on the "retention_1min_days" field.
func Retention1minDaysEQ(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldRetention1minDays, v))
}

// Retention1minDaysNEQ applies the NEQ predicate on the "retention_1min_days" field.
func Retention1minDaysNEQ(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldRetention1minDays, v))
}

// Retention1minDaysIn applies the In predicate on the "retention_1min_days" field.
func Retention1minDaysIn(vs ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldRetention1minDays, vs...))
}

// Retention1minDaysNotIn applies the NotIn predicate on the "retention_1min_days" field.
func Retention1minDaysNotIn(vs ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldRetention1minDays, vs...))
}

// Retention1minDaysGT applies the GT predicate on the "retention_1min_days" field.
func Retention1minDaysGT(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldRetention1minDays, v))
}

// Retention1minDaysGTE applies the GTE predicate on the "retention_1min_days" field.
func Retention1minDaysGTE(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldRetention1minDays, v))
}

// Retention1minDaysLT applies the LT predicate on the "retention_1min_days" field.
func Retention1minDaysLT(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldRetention1minDays, v))
}

// Retention1minDaysLTE applies the LTE predicate on the "retention_1min_days" field.
func Retention1minDaysLTE(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldRetention1minDays, v))
}

// Retention5minDaysEQ applies the EQ predicate on the "retention_5min_days" field.
func Retention5minDaysEQ(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldRetention5minDays, v))
}

// Retention5minDaysNEQ applies the NEQ predicate on the "retention_5min_days" field.
func Retention5minDaysNEQ(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldRetention5minDays, v))
}

// Retention5minDaysIn applies the In predicate on the "retention_5min_days" field.
func Retention5minDaysIn(vs ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldRetention5minDays, vs...))
}

// Retention5minDaysNotIn applies the NotIn predicate on the "retention_5min_days" field.
func Retention5minDaysNotIn(vs ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldRetention5minDays, vs...))
}

// Retention5minDaysGT applies the GT predicate on the "retention_5min_days" field.
func Retention5minDaysGT(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldRetention5minDays, v))
}

// Retention5minDaysGTE applies the GTE predicate on the "retention_5min_days" field.
func Retention5minDaysGTE(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldRetention5minDays, v))
}

// Retention5minDaysLT applies the LT predicate on the "retention_5min_days" field.
func Retention5minDaysLT(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldRetention5minDays, v))
}

// Retention5minDaysLTE applies the LTE predicate on the "retention_5min_days" field.
func Retention5minDaysLTE(v int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldRetention5minDays, v))
}

// WifiSampleEnabledEQ applies the EQ predicate on the "wifi_sample_enabled" field.
func WifiSampleEnabledEQ(v bool) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldWifiSampleEnabled, v))
}

// WifiSampleEnabledNEQ applies the NEQ predicate on the "wifi_sample_enabled" field.
func WifiSampleEnabledNEQ(v bool) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldWifiSampleEnabled, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AppConfig) predicate.AppConfig {
	return predicate.AppConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AppConfig) predicate.AppConfig {
	return predicate.AppConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AppConfig) predicate.AppConfig {
	return predicate.AppConfig(sql.NotPredicates(p))
}
