// Code generated by ent, DO NOT EDIT.

package outage

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the outage type in the database.
	Label = "outage"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldScope holds the string denoting the scope field in the database.
	FieldScope = "scope"
	// FieldStartTsUnixMs holds the string denoting the start_ts_unix_ms field in the database.
	FieldStartTsUnixMs = "start_ts_unix_ms"
	// FieldEndTsUnixMs holds the string denoting the end_ts_unix_ms field in the database.
	FieldEndTsUnixMs = "end_ts_unix_ms"
	// FieldConsecutiveFailures holds the string denoting the consecutive_failures field in the database.
	FieldConsecutiveFailures = "consecutive_failures"
	// FieldErrors holds the string denoting the errors field in the database.
	FieldErrors = "errors"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the outage in the database.
	Table = "outages"
)

// Columns holds all SQL columns for outage fields.
var Columns = []string{
	FieldID,
	FieldScope,
	FieldStartTsUnixMs,
	FieldEndTsUnixMs,
	FieldConsecutiveFailures,
	FieldErrors,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ScopeValidator is a validator for the "scope" field. It is called by the builders before save.
	ScopeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the Outage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByScope orders the results by the scope field.
func ByScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScope, opts...).ToFunc()
}

// ByStartTsUnixMs orders the results by the start_ts_unix_ms field.
func ByStartTsUnixMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartTsUnixMs, opts...).ToFunc()
}

// ByEndTsUnixMs orders the results by the end_ts_unix_ms field.
func ByEndTsUnixMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndTsUnixMs, opts...).ToFunc()
}

// ByConsecutiveFailures orders the results by the consecutive_failures field.
func ByConsecutiveFailures(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsecutiveFailures, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
