// Code generated by ent, DO NOT EDIT.

package outage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/sid-technologies/vigil/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Outage {
	return predicate.Outage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Outage {
	return predicate.Outage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Outage {
	return predicate.Outage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Outage {
	return predicate.Outage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Outage {
	return predicate.Outage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Outage {
	return predicate.Outage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Outage {
	return predicate.Outage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Outage {
	return predicate.Outage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Outage {
	return predicate.Outage(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Outage {
	return predicate.Outage(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Outage {
	return predicate.Outage(sql.FieldContainsFold(FieldID, id))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v string) predicate.Outage {
	return predicate.Outage(sql.FieldEQ(FieldScope, v))
}

// StartTsUnixMs applies equality check predicate on the "start_ts_unix_ms" field. It's identical to StartTsUnixMsEQ.
func StartTsUnixMs(v int64) predicate.Outage {
	return predicate.Outage(sql.FieldEQ(FieldStartTsUnixMs, v))
}

// EndTsUnixMs applies equality check predicate on the "end_ts_unix_ms" field. It's identical to EndTsUnixMsEQ.
func EndTsUnixMs(v int64) predicate.Outage {
	return predicate.Outage(sql.FieldEQ(FieldEndTsUnixMs, v))
}

// ConsecutiveFailures applies equality check predicate on the "consecutive_failures" field. It's identical to ConsecutiveFailuresEQ.
func ConsecutiveFailures(v int) predicate.Outage {
	return predicate.Outage(sql.FieldEQ(FieldConsecutiveFailures, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Outage {
	return predicate.Outage(sql.FieldEQ(FieldCreatedAt, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v string) predicate.Outage {
	return predicate.Outage(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v string) predicate.Outage {
	return predicate.Outage(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...string) predicate.Outage {
	return predicate.Outage(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...string) predicate.Outage {
	return predicate.Outage(sql.FieldNotIn(FieldScope, vs...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v string) predicate.Outage {
	return predicate.Outage(sql.FieldGT(FieldScope, v))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v string) predicate.Outage {
	return predicate.Outage(sql.FieldGTE(FieldScope, v))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v string) predicate.Outage {
	return predicate.Outage(sql.FieldLT(FieldScope, v))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v string) predicate.Outage {
	return predicate.Outage(sql.FieldLTE(FieldScope, v))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v string) predicate.Outage {
	return predicate.Outage(sql.FieldContains(FieldScope, v))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v string) predicate.Outage {
	return predicate.Outage(sql.FieldHasPrefix(FieldScope, v))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v string) predicate.Outage {
	return predicate.Outage(sql.FieldHasSuffix(FieldScope, v))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v string) predicate.Outage {
	return predicate.Outage(sql.FieldEqualFold(FieldScope, v))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v string) predicate.Outage {
	return predicate.Outage(sql.FieldContainsFold(FieldScope, v))
}

// StartTsUnixMsEQ applies the EQ predicate on the "start_ts_unix_ms" field.
func StartTsUnixMsEQ(v int64) predicate.Outage {
	return predicate.Outage(sql.FieldEQ(FieldStartTsUnixMs, v))
}

// StartTsUnixMsNEQ applies the NEQ predicate on the "start_ts_unix_ms" field.
func StartTsUnixMsNEQ(v int64) predicate.Outage {
	return predicate.Outage(sql.FieldNEQ(FieldStartTsUnixMs, v))
}

// StartTsUnixMsIn applies the In predicate on the "start_ts_unix_ms" field.
func StartTsUnixMsIn(vs ...int64) predicate.Outage {
	return predicate.Outage(sql.FieldIn(FieldStartTsUnixMs, vs...))
}

// StartTsUnixMsNotIn applies the NotIn predicate on the "start_ts_unix_ms" field.
func StartTsUnixMsNotIn(vs ...int64) predicate.Outage {
	return predicate.Outage(sql.FieldNotIn(FieldStartTsUnixMs, vs...))
}

// StartTsUnixMsGT applies the GT predicate on the "start_ts_unix_ms" field.
func StartTsUnixMsGT(v int64) predicate.Outage {
	return predicate.Outage(sql.FieldGT(FieldStartTsUnixMs, v))
}

// StartTsUnixMsGTE applies the GTE predicate on the "start_ts_unix_ms" field.
func StartTsUnixMsGTE(v int64) predicate.Outage {
	return predicate.Outage(sql.FieldGTE(FieldStartTsUnixMs, v))
}

// StartTsUnixMsLT applies the LT predicate on the "start_ts_unix_ms" field.
func StartTsUnixMsLT(v int64) predicate.Outage {
	return predicate.Outage(sql.FieldLT(FieldStartTsUnixMs, v))
}

// StartTsUnixMsLTE applies the LTE predicate on the "start_ts_unix_ms" field.
func StartTsUnixMsLTE(v int64) predicate.Outage {
	return predicate.Outage(sql.FieldLTE(FieldStartTsUnixMs, v))
}

// EndTsUnixMsEQ applies the EQ predicate on the "end_ts_unix_ms" field.
func EndTsUnixMsEQ(v int64) predicate.Outage {
	return predicate.Outage(sql.FieldEQ(FieldEndTsUnixMs, v))
}

// EndTsUnixMsNEQ applies the NEQ predicate on the "end_ts_unix_ms" field.
func EndTsUnixMsNEQ(v int64) predicate.Outage {
	return predicate.Outage(sql.FieldNEQ(FieldEndTsUnixMs, v))
}

// EndTsUnixMsIn applies the In predicate on the "end_ts_unix_ms" field.
func EndTsUnixMsIn(vs ...int64) predicate.Outage {
	return predicate.Outage(sql.FieldIn(FieldEndTsUnixMs, vs...))
}

// EndTsUnixMsNotIn applies the NotIn predicate on the "end_ts_unix_ms" field.
func EndTsUnixMsNotIn(vs ...int64) predicate.Outage {
	return predicate.Outage(sql.FieldNotIn(FieldEndTsUnixMs, vs...))
}

// EndTsUnixMsGT applies the GT predicate on the "end_ts_unix_ms" field.
func EndTsUnixMsGT(v int64) predicate.Outage {
	return predicate.Outage(sql.FieldGT(FieldEndTsUnixMs, v))
}

// EndTsUnixMsGTE applies the GTE predicate on the "end_ts_unix_ms" field.
func EndTsUnixMsGTE(v int64) predicate.Outage {
	return predicate.Outage(sql.FieldGTE(FieldEndTsUnixMs, v))
}

// EndTsUnixMsLT applies the LT predicate on the "end_ts_unix_ms" field.
func EndTsUnixMsLT(v int64) predicate.Outage {
	return predicate.Outage(sql.FieldLT(FieldEndTsUnixMs, v))
}

// EndTsUnixMsLTE applies the LTE predicate on the "end_ts_unix_ms" field.
func EndTsUnixMsLTE(v int64) predicate.Outage {
	return predicate.Outage(sql.FieldLTE(FieldEndTsUnixMs, v))
}

// EndTsUnixMsIsNil applies the IsNil predicate on the "end_ts_unix_ms" field.
func EndTsUnixMsIsNil() predicate.Outage {
	return predicate.Outage(sql.FieldIsNull(FieldEndTsUnixMs))
}

// EndTsUnixMsNotNil applies the NotNil predicate on the "end_ts_unix_ms" field.
func EndTsUnixMsNotNil() predicate.Outage {
	return predicate.Outage(sql.FieldNotNull(FieldEndTsUnixMs))
}

// ConsecutiveFailuresEQ applies the EQ predicate on the "consecutive_failures" field.
func ConsecutiveFailuresEQ(v int) predicate.Outage {
	return predicate.Outage(sql.FieldEQ(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresNEQ applies the NEQ predicate on the "consecutive_failures" field.
func ConsecutiveFailuresNEQ(v int) predicate.Outage {
	return predicate.Outage(sql.FieldNEQ(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresIn applies the In predicate on the "consecutive_failures" field.
func ConsecutiveFailuresIn(vs ...int) predicate.Outage {
	return predicate.Outage(sql.FieldIn(FieldConsecutiveFailures, vs...))
}

// ConsecutiveFailuresNotIn applies the NotIn predicate on the "consecutive_failures" field.
func ConsecutiveFailuresNotIn(vs ...int) predicate.Outage {
	return predicate.Outage(sql.FieldNotIn(FieldConsecutiveFailures, vs...))
}

// ConsecutiveFailuresGT applies the GT predicate on the "consecutive_failures" field.
func ConsecutiveFailuresGT(v int) predicate.Outage {
	return predicate.Outage(sql.FieldGT(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresGTE applies the GTE predicate on the "consecutive_failures" field.
func ConsecutiveFailuresGTE(v int) predicate.Outage {
	return predicate.Outage(sql.FieldGTE(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresLT applies the LT predicate on the "consecutive_failures" field.
func ConsecutiveFailuresLT(v int) predicate.Outage {
	return predicate.Outage(sql.FieldLT(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresLTE applies the LTE predicate on the "consecutive_failures" field.
func ConsecutiveFailuresLTE(v int) predicate.Outage {
	return predicate.Outage(sql.FieldLTE(FieldConsecutiveFailures, v))
}

// ErrorsIsNil applies the IsNil predicate on the "errors" field.
func ErrorsIsNil() predicate.Outage {
	return predicate.Outage(sql.FieldIsNull(FieldErrors))
}

// ErrorsNotNil applies the NotNil predicate on the "errors" field.
func ErrorsNotNil() predicate.Outage {
	return predicate.Outage(sql.FieldNotNull(FieldErrors))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Outage {
	return predicate.Outage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Outage {
	return predicate.Outage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Outage {
	return predicate.Outage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Outage {
	return predicate.Outage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Outage {
	return predicate.Outage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Outage {
	return predicate.Outage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Outage {
	return predicate.Outage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Outage {
	return predicate.Outage(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Outage) predicate.Outage {
	return predicate.Outage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Outage) predicate.Outage {
	return predicate.Outage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Outage) predicate.Outage {
	return predicate.Outage(sql.NotPredicates(p))
}
