// Code generated by ent, DO NOT EDIT.

package sample1min

import (
	"entgo.io/ent/dialect/sql"
	"github.com/sid-technologies/vigil/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldLTE(FieldID, id))
}

// BucketStartUnixMs applies equality check predicate on the "bucket_start_unix_ms" field. It's identical to BucketStartUnixMsEQ.
func BucketStartUnixMs(v int64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldEQ(FieldBucketStartUnixMs, v))
}

// TargetLabel applies equality check predicate on the "target_label" field. It's identical to TargetLabelEQ.
func TargetLabel(v string) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldEQ(FieldTargetLabel, v))
}

// Count applies equality check predicate on the "count" field. It's identical to CountEQ.
func Count(v int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldEQ(FieldCount, v))
}

// SuccessCount applies equality check predicate on the "success_count" field. It's identical to SuccessCountEQ.
func SuccessCount(v int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldEQ(FieldSuccessCount, v))
}

// FailCount applies equality check predicate on the "fail_count" field. It's identical to FailCountEQ.
func FailCount(v int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldEQ(FieldFailCount, v))
}

// RttP50Ms applies equality check predicate on the "rtt_p50_ms" field. It's identical to RttP50MsEQ.
func RttP50Ms(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldEQ(FieldRttP50Ms, v))
}

// RttP95Ms applies equality check predicate on the "rtt_p95_ms" field. It's identical to RttP95MsEQ.
func RttP95Ms(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldEQ(FieldRttP95Ms, v))
}

// RttP99Ms applies equality check predicate on the "rtt_p99_ms" field. It's identical to RttP99MsEQ.
func RttP99Ms(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldEQ(FieldRttP99Ms, v))
}

// RttMaxMs applies equality check predicate on the "rtt_max_ms" field. It's identical to RttMaxMsEQ.
func RttMaxMs(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldEQ(FieldRttMaxMs, v))
}

// RttMeanMs applies equality check predicate on the "rtt_mean_ms" field. It's identical to RttMeanMsEQ.
func RttMeanMs(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldEQ(FieldRttMeanMs, v))
}

// JitterMs applies equality check predicate on the "jitter_ms" field. It's identical to JitterMsEQ.
func JitterMs(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldEQ(FieldJitterMs, v))
}

// BucketStartUnixMsEQ applies the EQ predicate on the "bucket_start_unix_ms" field.
func BucketStartUnixMsEQ(v int64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldEQ(FieldBucketStartUnixMs, v))
}

// BucketStartUnixMsNEQ applies the NEQ predicate on the "bucket_start_unix_ms" field.
func BucketStartUnixMsNEQ(v int64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNEQ(FieldBucketStartUnixMs, v))
}

// BucketStartUnixMsIn applies the In predicate on the "bucket_start_unix_ms" field.
func BucketStartUnixMsIn(vs ...int64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldIn(FieldBucketStartUnixMs, vs...))
}

// BucketStartUnixMsNotIn applies the NotIn predicate on the "bucket_start_unix_ms" field.
func BucketStartUnixMsNotIn(vs ...int64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNotIn(FieldBucketStartUnixMs, vs...))
}

// BucketStartUnixMsGT applies the GT predicate on the "bucket_start_unix_ms" field.
func BucketStartUnixMsGT(v int64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldGT(FieldBucketStartUnixMs, v))
}

// BucketStartUnixMsGTE applies the GTE predicate on the "bucket_start_unix_ms" field.
func BucketStartUnixMsGTE(v int64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldGTE(FieldBucketStartUnixMs, v))
}

// BucketStartUnixMsLT applies the LT predicate on the "bucket_start_unix_ms" field.
func BucketStartUnixMsLT(v int64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldLT(FieldBucketStartUnixMs, v))
}

// BucketStartUnixMsLTE applies the LTE predicate on the "bucket_start_unix_ms" field.
func BucketStartUnixMsLTE(v int64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldLTE(FieldBucketStartUnixMs, v))
}

// TargetLabelEQ applies the EQ predicate on the "target_label" field.
func TargetLabelEQ(v string) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldEQ(FieldTargetLabel, v))
}

// TargetLabelNEQ applies the NEQ predicate on the "target_label" field.
func TargetLabelNEQ(v string) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNEQ(FieldTargetLabel, v))
}

// TargetLabelIn applies the In predicate on the "target_label" field.
func TargetLabelIn(vs ...string) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldIn(FieldTargetLabel, vs...))
}

// TargetLabelNotIn applies the NotIn predicate on the "target_label" field.
func TargetLabelNotIn(vs ...string) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNotIn(FieldTargetLabel, vs...))
}

// TargetLabelGT applies the GT predicate on the "target_label" field.
func TargetLabelGT(v string) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldGT(FieldTargetLabel, v))
}

// TargetLabelGTE applies the GTE predicate on the "target_label" field.
func TargetLabelGTE(v string) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldGTE(FieldTargetLabel, v))
}

// TargetLabelLT applies the LT predicate on the "target_label" field.
func TargetLabelLT(v string) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldLT(FieldTargetLabel, v))
}

// TargetLabelLTE applies the LTE predicate on the "target_label" field.
func TargetLabelLTE(v string) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldLTE(FieldTargetLabel, v))
}

// TargetLabelContains applies the Contains predicate on the "target_label" field.
func TargetLabelContains(v string) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldContains(FieldTargetLabel, v))
}

// TargetLabelHasPrefix applies the HasPrefix predicate on the "target_label" field.
func TargetLabelHasPrefix(v string) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldHasPrefix(FieldTargetLabel, v))
}

// TargetLabelHasSuffix applies the HasSuffix predicate on the "target_label" field.
func TargetLabelHasSuffix(v string) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldHasSuffix(FieldTargetLabel, v))
}

// TargetLabelEqualFold applies the EqualFold predicate on the "target_label" field.
func TargetLabelEqualFold(v string) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldEqualFold(FieldTargetLabel, v))
}

// TargetLabelContainsFold applies the ContainsFold predicate on the "target_label" field.
func TargetLabelContainsFold(v string) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldContainsFold(FieldTargetLabel, v))
}

// CountEQ applies the EQ predicate on the "count" field.
func CountEQ(v int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldEQ(FieldCount, v))
}

// CountNEQ applies the NEQ predicate on the "count" field.
func CountNEQ(v int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNEQ(FieldCount, v))
}

// CountIn applies the In predicate on the "count" field.
func CountIn(vs ...int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldIn(FieldCount, vs...))
}

// CountNotIn applies the NotIn predicate on the "count" field.
func CountNotIn(vs ...int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNotIn(FieldCount, vs...))
}

// CountGT applies the GT predicate on the "count" field.
func CountGT(v int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldGT(FieldCount, v))
}

// CountGTE applies the GTE predicate on the "count" field.
func CountGTE(v int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldGTE(FieldCount, v))
}

// CountLT applies the LT predicate on the "count" field.
func CountLT(v int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldLT(FieldCount, v))
}

// CountLTE applies the LTE predicate on the "count" field.
func CountLTE(v int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldLTE(FieldCount, v))
}

// SuccessCountEQ applies the EQ predicate on the "success_count" field.
func SuccessCountEQ(v int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldEQ(FieldSuccessCount, v))
}

// SuccessCountNEQ applies the NEQ predicate on the "success_count" field.
func SuccessCountNEQ(v int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNEQ(FieldSuccessCount, v))
}

// SuccessCountIn applies the In predicate on the "success_count" field.
func SuccessCountIn(vs ...int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldIn(FieldSuccessCount, vs...))
}

// SuccessCountNotIn applies the NotIn predicate on the "success_count" field.
func SuccessCountNotIn(vs ...int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNotIn(FieldSuccessCount, vs...))
}

// SuccessCountGT applies the GT predicate on the "success_count" field.
func SuccessCountGT(v int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldGT(FieldSuccessCount, v))
}

// SuccessCountGTE applies the GTE predicate on the "success_count" field.
func SuccessCountGTE(v int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldGTE(FieldSuccessCount, v))
}

// SuccessCountLT applies the LT predicate on the "success_count" field.
func SuccessCountLT(v int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldLT(FieldSuccessCount, v))
}

// SuccessCountLTE applies the LTE predicate on the "success_count" field.
func SuccessCountLTE(v int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldLTE(FieldSuccessCount, v))
}

// FailCountEQ applies the EQ predicate on the "fail_count" field.
func FailCountEQ(v int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldEQ(FieldFailCount, v))
}

// FailCountNEQ applies the NEQ predicate on the "fail_count" field.
func FailCountNEQ(v int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNEQ(FieldFailCount, v))
}

// FailCountIn applies the In predicate on the "fail_count" field.
func FailCountIn(vs ...int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldIn(FieldFailCount, vs...))
}

// FailCountNotIn applies the NotIn predicate on the "fail_count" field.
func FailCountNotIn(vs ...int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNotIn(FieldFailCount, vs...))
}

// FailCountGT applies the GT predicate on the "fail_count" field.
func FailCountGT(v int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldGT(FieldFailCount, v))
}

// FailCountGTE applies the GTE predicate on the "fail_count" field.
func FailCountGTE(v int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldGTE(FieldFailCount, v))
}

// FailCountLT applies the LT predicate on the "fail_count" field.
func FailCountLT(v int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldLT(FieldFailCount, v))
}

// FailCountLTE applies the LTE predicate on the "fail_count" field.
func FailCountLTE(v int) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldLTE(FieldFailCount, v))
}

// RttP50MsEQ applies the EQ predicate on the "rtt_p50_ms" field.
func RttP50MsEQ(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldEQ(FieldRttP50Ms, v))
}

// RttP50MsNEQ applies the NEQ predicate on the "rtt_p50_ms" field.
func RttP50MsNEQ(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNEQ(FieldRttP50Ms, v))
}

// RttP50MsIn applies the In predicate on the "rtt_p50_ms" field.
func RttP50MsIn(vs ...float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldIn(FieldRttP50Ms, vs...))
}

// RttP50MsNotIn applies the NotIn predicate on the "rtt_p50_ms" field.
func RttP50MsNotIn(vs ...float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNotIn(FieldRttP50Ms, vs...))
}

// RttP50MsGT applies the GT predicate on the "rtt_p50_ms" field.
func RttP50MsGT(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldGT(FieldRttP50Ms, v))
}

// RttP50MsGTE applies the GTE predicate on the "rtt_p50_ms" field.
func RttP50MsGTE(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldGTE(FieldRttP50Ms, v))
}

// RttP50MsLT applies the LT predicate on the "rtt_p50_ms" field.
func RttP50MsLT(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldLT(FieldRttP50Ms, v))
}

// RttP50MsLTE applies the LTE predicate on the "rtt_p50_ms" field.
func RttP50MsLTE(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldLTE(FieldRttP50Ms, v))
}

// RttP50MsIsNil applies the IsNil predicate on the "rtt_p50_ms" field.
func RttP50MsIsNil() predicate.Sample1min {
	return predicate.Sample1min(sql.FieldIsNull(FieldRttP50Ms))
}

// RttP50MsNotNil applies the NotNil predicate on the "rtt_p50_ms" field.
func RttP50MsNotNil() predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNotNull(FieldRttP50Ms))
}

// RttP95MsEQ applies the EQ predicate on the "rtt_p95_ms" field.
func RttP95MsEQ(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldEQ(FieldRttP95Ms, v))
}

// RttP95MsNEQ applies the NEQ predicate on the "rtt_p95_ms" field.
func RttP95MsNEQ(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNEQ(FieldRttP95Ms, v))
}

// RttP95MsIn applies the In predicate on the "rtt_p95_ms" field.
func RttP95MsIn(vs ...float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldIn(FieldRttP95Ms, vs...))
}

// RttP95MsNotIn applies the NotIn predicate on the "rtt_p95_ms" field.
func RttP95MsNotIn(vs ...float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNotIn(FieldRttP95Ms, vs...))
}

// RttP95MsGT applies the GT predicate on the "rtt_p95_ms" field.
func RttP95MsGT(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldGT(FieldRttP95Ms, v))
}

// RttP95MsGTE applies the GTE predicate on the "rtt_p95_ms" field.
func RttP95MsGTE(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldGTE(FieldRttP95Ms, v))
}

// RttP95MsLT applies the LT predicate on the "rtt_p95_ms" field.
func RttP95MsLT(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldLT(FieldRttP95Ms, v))
}

// RttP95MsLTE applies the LTE predicate on the "rtt_p95_ms" field.
func RttP95MsLTE(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldLTE(FieldRttP95Ms, v))
}

// RttP95MsIsNil applies the IsNil predicate on the "rtt_p95_ms" field.
func RttP95MsIsNil() predicate.Sample1min {
	return predicate.Sample1min(sql.FieldIsNull(FieldRttP95Ms))
}

// RttP95MsNotNil applies the NotNil predicate on the "rtt_p95_ms" field.
func RttP95MsNotNil() predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNotNull(FieldRttP95Ms))
}

// RttP99MsEQ applies the EQ predicate on the "rtt_p99_ms" field.
func RttP99MsEQ(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldEQ(FieldRttP99Ms, v))
}

// RttP99MsNEQ applies the NEQ predicate on the "rtt_p99_ms" field.
func RttP99MsNEQ(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNEQ(FieldRttP99Ms, v))
}

// RttP99MsIn applies the In predicate on the "rtt_p99_ms" field.
func RttP99MsIn(vs ...float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldIn(FieldRttP99Ms, vs...))
}

// RttP99MsNotIn applies the NotIn predicate on the "rtt_p99_ms" field.
func RttP99MsNotIn(vs ...float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNotIn(FieldRttP99Ms, vs...))
}

// RttP99MsGT applies the GT predicate on the "rtt_p99_ms" field.
func RttP99MsGT(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldGT(FieldRttP99Ms, v))
}

// RttP99MsGTE applies the GTE predicate on the "rtt_p99_ms" field.
func RttP99MsGTE(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldGTE(FieldRttP99Ms, v))
}

// RttP99MsLT applies the LT predicate on the "rtt_p99_ms" field.
func RttP99MsLT(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldLT(FieldRttP99Ms, v))
}

// RttP99MsLTE applies the LTE predicate on the "rtt_p99_ms" field.
func RttP99MsLTE(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldLTE(FieldRttP99Ms, v))
}

// RttP99MsIsNil applies the IsNil predicate on the "rtt_p99_ms" field.
func RttP99MsIsNil() predicate.Sample1min {
	return predicate.Sample1min(sql.FieldIsNull(FieldRttP99Ms))
}

// RttP99MsNotNil applies the NotNil predicate on the "rtt_p99_ms" field.
func RttP99MsNotNil() predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNotNull(FieldRttP99Ms))
}

// RttMaxMsEQ applies the EQ predicate on the "rtt_max_ms" field.
func RttMaxMsEQ(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldEQ(FieldRttMaxMs, v))
}

// RttMaxMsNEQ applies the NEQ predicate on the "rtt_max_ms" field.
func RttMaxMsNEQ(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNEQ(FieldRttMaxMs, v))
}

// RttMaxMsIn applies the In predicate on the "rtt_max_ms" field.
func RttMaxMsIn(vs ...float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldIn(FieldRttMaxMs, vs...))
}

// RttMaxMsNotIn applies the NotIn predicate on the "rtt_max_ms" field.
func RttMaxMsNotIn(vs ...float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNotIn(FieldRttMaxMs, vs...))
}

// RttMaxMsGT applies the GT predicate on the "rtt_max_ms" field.
func RttMaxMsGT(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldGT(FieldRttMaxMs, v))
}

// RttMaxMsGTE applies the GTE predicate on the "rtt_max_ms" field.
func RttMaxMsGTE(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldGTE(FieldRttMaxMs, v))
}

// RttMaxMsLT applies the LT predicate on the "rtt_max_ms" field.
func RttMaxMsLT(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldLT(FieldRttMaxMs, v))
}

// RttMaxMsLTE applies the LTE predicate on the "rtt_max_ms" field.
func RttMaxMsLTE(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldLTE(FieldRttMaxMs, v))
}

// RttMaxMsIsNil applies the IsNil predicate on the "rtt_max_ms" field.
func RttMaxMsIsNil() predicate.Sample1min {
	return predicate.Sample1min(sql.FieldIsNull(FieldRttMaxMs))
}

// RttMaxMsNotNil applies the NotNil predicate on the "rtt_max_ms" field.
func RttMaxMsNotNil() predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNotNull(FieldRttMaxMs))
}

// RttMeanMsEQ applies the EQ predicate on the "rtt_mean_ms" field.
func RttMeanMsEQ(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldEQ(FieldRttMeanMs, v))
}

// RttMeanMsNEQ applies the NEQ predicate on the "rtt_mean_ms" field.
func RttMeanMsNEQ(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNEQ(FieldRttMeanMs, v))
}

// RttMeanMsIn applies the In predicate on the "rtt_mean_ms" field.
func RttMeanMsIn(vs ...float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldIn(FieldRttMeanMs, vs...))
}

// RttMeanMsNotIn applies the NotIn predicate on the "rtt_mean_ms" field.
func RttMeanMsNotIn(vs ...float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNotIn(FieldRttMeanMs, vs...))
}

// RttMeanMsGT applies the GT predicate on the "rtt_mean_ms" field.
func RttMeanMsGT(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldGT(FieldRttMeanMs, v))
}

// RttMeanMsGTE applies the GTE predicate on the "rtt_mean_ms" field.
func RttMeanMsGTE(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldGTE(FieldRttMeanMs, v))
}

// RttMeanMsLT applies the LT predicate on the "rtt_mean_ms" field.
func RttMeanMsLT(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldLT(FieldRttMeanMs, v))
}

// RttMeanMsLTE applies the LTE predicate on the "rtt_mean_ms" field.
func RttMeanMsLTE(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldLTE(FieldRttMeanMs, v))
}

// RttMeanMsIsNil applies the IsNil predicate on the "rtt_mean_ms" field.
func RttMeanMsIsNil() predicate.Sample1min {
	return predicate.Sample1min(sql.FieldIsNull(FieldRttMeanMs))
}

// RttMeanMsNotNil applies the NotNil predicate on the "rtt_mean_ms" field.
func RttMeanMsNotNil() predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNotNull(FieldRttMeanMs))
}

// JitterMsEQ applies the EQ predicate on the "jitter_ms" field.
func JitterMsEQ(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldEQ(FieldJitterMs, v))
}

// JitterMsNEQ applies the NEQ predicate on the "jitter_ms" field.
func JitterMsNEQ(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNEQ(FieldJitterMs, v))
}

// JitterMsIn applies the In predicate on the "jitter_ms" field.
func JitterMsIn(vs ...float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldIn(FieldJitterMs, vs...))
}

// JitterMsNotIn applies the NotIn predicate on the "jitter_ms" field.
func JitterMsNotIn(vs ...float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNotIn(FieldJitterMs, vs...))
}

// JitterMsGT applies the GT predicate on the "jitter_ms" field.
func JitterMsGT(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldGT(FieldJitterMs, v))
}

// JitterMsGTE applies the GTE predicate on the "jitter_ms" field.
func JitterMsGTE(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldGTE(FieldJitterMs, v))
}

// JitterMsLT applies the LT predicate on the "jitter_ms" field.
func JitterMsLT(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldLT(FieldJitterMs, v))
}

// JitterMsLTE applies the LTE predicate on the "jitter_ms" field.
func JitterMsLTE(v float64) predicate.Sample1min {
	return predicate.Sample1min(sql.FieldLTE(FieldJitterMs, v))
}

// JitterMsIsNil applies the IsNil predicate on the "jitter_ms" field.
func JitterMsIsNil() predicate.Sample1min {
	return predicate.Sample1min(sql.FieldIsNull(FieldJitterMs))
}

// JitterMsNotNil applies the NotNil predicate on the "jitter_ms" field.
func JitterMsNotNil() predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNotNull(FieldJitterMs))
}

// ErrorsIsNil applies the IsNil predicate on the "errors" field.
func ErrorsIsNil() predicate.Sample1min {
	return predicate.Sample1min(sql.FieldIsNull(FieldErrors))
}

// ErrorsNotNil applies the NotNil predicate on the "errors" field.
func ErrorsNotNil() predicate.Sample1min {
	return predicate.Sample1min(sql.FieldNotNull(FieldErrors))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Sample1min) predicate.Sample1min {
	return predicate.Sample1min(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Sample1min) predicate.Sample1min {
	return predicate.Sample1min(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Sample1min) predicate.Sample1min {
	return predicate.Sample1min(sql.NotPredicates(p))
}
