// Code generated by ent, DO NOT EDIT.

package sample1h

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the sample1h type in the database.
	Label = "sample1h"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBucketStartUnixMs holds the string denoting the bucket_start_unix_ms field in the database.
	FieldBucketStartUnixMs = "bucket_start_unix_ms"
	// FieldTargetLabel holds the string denoting the target_label field in the database.
	FieldTargetLabel = "target_label"
	// FieldCount holds the string denoting the count field in the database.
	FieldCount = "count"
	// FieldSuccessCount holds the string denoting the success_count field in the database.
	FieldSuccessCount = "success_count"
	// FieldFailCount holds the string denoting the fail_count field in the database.
	FieldFailCount = "fail_count"
	// FieldRttP50Ms holds the string denoting the rtt_p50_ms field in the database.
	FieldRttP50Ms = "rtt_p50_ms"
	// FieldRttP95Ms holds the string denoting the rtt_p95_ms field in the database.
	FieldRttP95Ms = "rtt_p95_ms"
	// FieldRttP99Ms holds the string denoting the rtt_p99_ms field in the database.
	FieldRttP99Ms = "rtt_p99_ms"
	// FieldRttMaxMs holds the string denoting the rtt_max_ms field in the database.
	FieldRttMaxMs = "rtt_max_ms"
	// FieldRttMeanMs holds the string denoting the rtt_mean_ms field in the database.
	FieldRttMeanMs = "rtt_mean_ms"
	// FieldJitterMs holds the string denoting the jitter_ms field in the database.
	FieldJitterMs = "jitter_ms"
	// FieldErrors holds the string denoting the errors field in the database.
	FieldErrors = "errors"
	// Table holds the table name of the sample1h in the database.
	Table = "sample1hs"
)

// Columns holds all SQL columns for sample1h fields.
var Columns = []string{
	FieldID,
	FieldBucketStartUnixMs,
	FieldTargetLabel,
	FieldCount,
	FieldSuccessCount,
	FieldFailCount,
	FieldRttP50Ms,
	FieldRttP95Ms,
	FieldRttP99Ms,
	FieldRttMaxMs,
	FieldRttMeanMs,
	FieldJitterMs,
	FieldErrors,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TargetLabelValidator is a validator for the "target_label" field. It is called by the builders before save.
	TargetLabelValidator func(string) error
)

// OrderOption defines the ordering options for the Sample1h queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBucketStartUnixMs orders the results by the bucket_start_unix_ms field.
func ByBucketStartUnixMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBucketStartUnixMs, opts...).ToFunc()
}

// ByTargetLabel orders the results by the target_label field.
func ByTargetLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetLabel, opts...).ToFunc()
}

// ByCount orders the results by the count field.
func ByCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCount, opts...).ToFunc()
}

// BySuccessCount orders the results by the success_count field.
func BySuccessCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccessCount, opts...).ToFunc()
}

// ByFailCount orders the results by the fail_count field.
func ByFailCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailCount, opts...).ToFunc()
}

// ByRttP50Ms orders the results by the rtt_p50_ms field.
func ByRttP50Ms(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRttP50Ms, opts...).ToFunc()
}

// ByRttP95Ms orders the results by the rtt_p95_ms field.
func ByRttP95Ms(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRttP95Ms, opts...).ToFunc()
}

// ByRttP99Ms orders the results by the rtt_p99_ms field.
func ByRttP99Ms(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRttP99Ms, opts...).ToFunc()
}

// ByRttMaxMs orders the results by the rtt_max_ms field.
func ByRttMaxMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRttMaxMs, opts...).ToFunc()
}

// ByRttMeanMs orders the results by the rtt_mean_ms field.
func ByRttMeanMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRttMeanMs, opts...).ToFunc()
}

// ByJitterMs orders the results by the jitter_ms field.
func ByJitterMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJitterMs, opts...).ToFunc()
}
