// Code generated by ent, DO NOT EDIT.

package wifisample

import (
	"entgo.io/ent/dialect/sql"
	"github.com/sid-technologies/vigil/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldLTE(FieldID, id))
}

// TsUnixMs applies equality check predicate on the "ts_unix_ms" field. It's identical to TsUnixMsEQ.
func TsUnixMs(v int64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldEQ(FieldTsUnixMs, v))
}

// Ssid applies equality check predicate on the "ssid" field. It's identical to SsidEQ.
func Ssid(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldEQ(FieldSsid, v))
}

// Bssid applies equality check predicate on the "bssid" field. It's identical to BssidEQ.
func Bssid(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldEQ(FieldBssid, v))
}

// SignalPercent applies equality check predicate on the "signal_percent" field. It's identical to SignalPercentEQ.
func SignalPercent(v int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldEQ(FieldSignalPercent, v))
}

// RssiDbm applies equality check predicate on the "rssi_dbm" field. It's identical to RssiDbmEQ.
func RssiDbm(v int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldEQ(FieldRssiDbm, v))
}

// RxRateMbps applies equality check predicate on the "rx_rate_mbps" field. It's identical to RxRateMbpsEQ.
func RxRateMbps(v float64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldEQ(FieldRxRateMbps, v))
}

// TxRateMbps applies equality check predicate on the "tx_rate_mbps" field. It's identical to TxRateMbpsEQ.
func TxRateMbps(v float64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldEQ(FieldTxRateMbps, v))
}

// Channel applies equality check predicate on the "channel" field. It's identical to ChannelEQ.
func Channel(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldEQ(FieldChannel, v))
}

// TsUnixMsEQ applies the EQ predicate on the "ts_unix_ms" field.
func TsUnixMsEQ(v int64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldEQ(FieldTsUnixMs, v))
}

// TsUnixMsNEQ applies the NEQ predicate on the "ts_unix_ms" field.
func TsUnixMsNEQ(v int64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldNEQ(FieldTsUnixMs, v))
}

// TsUnixMsIn applies the In predicate on the "ts_unix_ms" field.
func TsUnixMsIn(vs ...int64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldIn(FieldTsUnixMs, vs...))
}

// TsUnixMsNotIn applies the NotIn predicate on the "ts_unix_ms" field.
func TsUnixMsNotIn(vs ...int64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldNotIn(FieldTsUnixMs, vs...))
}

// TsUnixMsGT applies the GT predicate on the "ts_unix_ms" field.
func TsUnixMsGT(v int64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldGT(FieldTsUnixMs, v))
}

// TsUnixMsGTE applies the GTE predicate on the "ts_unix_ms" field.
func TsUnixMsGTE(v int64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldGTE(FieldTsUnixMs, v))
}

// TsUnixMsLT applies the LT predicate on the "ts_unix_ms" field.
func TsUnixMsLT(v int64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldLT(FieldTsUnixMs, v))
}

// TsUnixMsLTE applies the LTE predicate on the "ts_unix_ms" field.
func TsUnixMsLTE(v int64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldLTE(FieldTsUnixMs, v))
}

// SsidEQ applies the EQ predicate on the "ssid" field.
func SsidEQ(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldEQ(FieldSsid, v))
}

// SsidNEQ applies the NEQ predicate on the "ssid" field.
func SsidNEQ(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldNEQ(FieldSsid, v))
}

// SsidIn applies the In predicate on the "ssid" field.
func SsidIn(vs ...string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldIn(FieldSsid, vs...))
}

// SsidNotIn applies the NotIn predicate on the "ssid" field.
func SsidNotIn(vs ...string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldNotIn(FieldSsid, vs...))
}

// SsidGT applies the GT predicate on the "ssid" field.
func SsidGT(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldGT(FieldSsid, v))
}

// SsidGTE applies the GTE predicate on the "ssid" field.
func SsidGTE(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldGTE(FieldSsid, v))
}

// SsidLT applies the LT predicate on the "ssid" field.
func SsidLT(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldLT(FieldSsid, v))
}

// SsidLTE applies the LTE predicate on the "ssid" field.
func SsidLTE(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldLTE(FieldSsid, v))
}

// SsidContains applies the Contains predicate on the "ssid" field.
func SsidContains(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldContains(FieldSsid, v))
}

// SsidHasPrefix applies the HasPrefix predicate on the "ssid" field.
func SsidHasPrefix(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldHasPrefix(FieldSsid, v))
}

// SsidHasSuffix applies the HasSuffix predicate on the "ssid" field.
func SsidHasSuffix(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldHasSuffix(FieldSsid, v))
}

// SsidIsNil applies the IsNil predicate on the "ssid" field.
func SsidIsNil() predicate.WifiSample {
	return predicate.WifiSample(sql.FieldIsNull(FieldSsid))
}

// SsidNotNil applies the NotNil predicate on the "ssid" field.
func SsidNotNil() predicate.WifiSample {
	return predicate.WifiSample(sql.FieldNotNull(FieldSsid))
}

// SsidEqualFold applies the EqualFold predicate on the "ssid" field.
func SsidEqualFold(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldEqualFold(FieldSsid, v))
}

// SsidContainsFold applies the ContainsFold predicate on the "ssid" field.
func SsidContainsFold(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldContainsFold(FieldSsid, v))
}

// BssidEQ applies the EQ predicate on the "bssid" field.
func BssidEQ(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldEQ(FieldBssid, v))
}

// BssidNEQ applies the NEQ predicate on the "bssid" field.
func BssidNEQ(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldNEQ(FieldBssid, v))
}

// BssidIn applies the In predicate on the "bssid" field.
func BssidIn(vs ...string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldIn(FieldBssid, vs...))
}

// BssidNotIn applies the NotIn predicate on the "bssid" field.
func BssidNotIn(vs ...string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldNotIn(FieldBssid, vs...))
}

// BssidGT applies the GT predicate on the "bssid" field.
func BssidGT(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldGT(FieldBssid, v))
}

// BssidGTE applies the GTE predicate on the "bssid" field.
func BssidGTE(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldGTE(FieldBssid, v))
}

// BssidLT applies the LT predicate on the "bssid" field.
func BssidLT(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldLT(FieldBssid, v))
}

// BssidLTE applies the LTE predicate on the "bssid" field.
func BssidLTE(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldLTE(FieldBssid, v))
}

// BssidContains applies the Contains predicate on the "bssid" field.
func BssidContains(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldContains(FieldBssid, v))
}

// BssidHasPrefix applies the HasPrefix predicate on the "bssid" field.
func BssidHasPrefix(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldHasPrefix(FieldBssid, v))
}

// BssidHasSuffix applies the HasSuffix predicate on the "bssid" field.
func BssidHasSuffix(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldHasSuffix(FieldBssid, v))
}

// BssidIsNil applies the IsNil predicate on the "bssid" field.
func BssidIsNil() predicate.WifiSample {
	return predicate.WifiSample(sql.FieldIsNull(FieldBssid))
}

// BssidNotNil applies the NotNil predicate on the "bssid" field.
func BssidNotNil() predicate.WifiSample {
	return predicate.WifiSample(sql.FieldNotNull(FieldBssid))
}

// BssidEqualFold applies the EqualFold predicate on the "bssid" field.
func BssidEqualFold(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldEqualFold(FieldBssid, v))
}

// BssidContainsFold applies the ContainsFold predicate on the "bssid" field.
func BssidContainsFold(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldContainsFold(FieldBssid, v))
}

// SignalPercentEQ applies the EQ predicate on the "signal_percent" field.
func SignalPercentEQ(v int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldEQ(FieldSignalPercent, v))
}

// SignalPercentNEQ applies the NEQ predicate on the "signal_percent" field.
func SignalPercentNEQ(v int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldNEQ(FieldSignalPercent, v))
}

// SignalPercentIn applies the In predicate on the "signal_percent" field.
func SignalPercentIn(vs ...int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldIn(FieldSignalPercent, vs...))
}

// SignalPercentNotIn applies the NotIn predicate on the "signal_percent" field.
func SignalPercentNotIn(vs ...int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldNotIn(FieldSignalPercent, vs...))
}

// SignalPercentGT applies the GT predicate on the "signal_percent" field.
func SignalPercentGT(v int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldGT(FieldSignalPercent, v))
}

// SignalPercentGTE applies the GTE predicate on the "signal_percent" field.
func SignalPercentGTE(v int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldGTE(FieldSignalPercent, v))
}

// SignalPercentLT applies the LT predicate on the "signal_percent" field.
func SignalPercentLT(v int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldLT(FieldSignalPercent, v))
}

// SignalPercentLTE applies the LTE predicate on the "signal_percent" field.
func SignalPercentLTE(v int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldLTE(FieldSignalPercent, v))
}

// SignalPercentIsNil applies the IsNil predicate on the "signal_percent" field.
func SignalPercentIsNil() predicate.WifiSample {
	return predicate.WifiSample(sql.FieldIsNull(FieldSignalPercent))
}

// SignalPercentNotNil applies the NotNil predicate on the "signal_percent" field.
func SignalPercentNotNil() predicate.WifiSample {
	return predicate.WifiSample(sql.FieldNotNull(FieldSignalPercent))
}

// RssiDbmEQ applies the EQ predicate on the "rssi_dbm" field.
func RssiDbmEQ(v int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldEQ(FieldRssiDbm, v))
}

// RssiDbmNEQ applies the NEQ predicate on the "rssi_dbm" field.
func RssiDbmNEQ(v int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldNEQ(FieldRssiDbm, v))
}

// RssiDbmIn applies the In predicate on the "rssi_dbm" field.
func RssiDbmIn(vs ...int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldIn(FieldRssiDbm, vs...))
}

// RssiDbmNotIn applies the NotIn predicate on the "rssi_dbm" field.
func RssiDbmNotIn(vs ...int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldNotIn(FieldRssiDbm, vs...))
}

// RssiDbmGT applies the GT predicate on the "rssi_dbm" field.
func RssiDbmGT(v int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldGT(FieldRssiDbm, v))
}

// RssiDbmGTE applies the GTE predicate on the "rssi_dbm" field.
func RssiDbmGTE(v int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldGTE(FieldRssiDbm, v))
}

// RssiDbmLT applies the LT predicate on the "rssi_dbm" field.
func RssiDbmLT(v int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldLT(FieldRssiDbm, v))
}

// RssiDbmLTE applies the LTE predicate on the "rssi_dbm" field.
func RssiDbmLTE(v int) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldLTE(FieldRssiDbm, v))
}

// RssiDbmIsNil applies the IsNil predicate on the "rssi_dbm" field.
func RssiDbmIsNil() predicate.WifiSample {
	return predicate.WifiSample(sql.FieldIsNull(FieldRssiDbm))
}

// RssiDbmNotNil applies the NotNil predicate on the "rssi_dbm" field.
func RssiDbmNotNil() predicate.WifiSample {
	return predicate.WifiSample(sql.FieldNotNull(FieldRssiDbm))
}

// RxRateMbpsEQ applies the EQ predicate on the "rx_rate_mbps" field.
func RxRateMbpsEQ(v float64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldEQ(FieldRxRateMbps, v))
}

// RxRateMbpsNEQ applies the NEQ predicate on the "rx_rate_mbps" field.
func RxRateMbpsNEQ(v float64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldNEQ(FieldRxRateMbps, v))
}

// RxRateMbpsIn applies the In predicate on the "rx_rate_mbps" field.
func RxRateMbpsIn(vs ...float64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldIn(FieldRxRateMbps, vs...))
}

// RxRateMbpsNotIn applies the NotIn predicate on the "rx_rate_mbps" field.
func RxRateMbpsNotIn(vs ...float64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldNotIn(FieldRxRateMbps, vs...))
}

// RxRateMbpsGT applies the GT predicate on the "rx_rate_mbps" field.
func RxRateMbpsGT(v float64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldGT(FieldRxRateMbps, v))
}

// RxRateMbpsGTE applies the GTE predicate on the "rx_rate_mbps" field.
func RxRateMbpsGTE(v float64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldGTE(FieldRxRateMbps, v))
}

// RxRateMbpsLT applies the LT predicate on the "rx_rate_mbps" field.
func RxRateMbpsLT(v float64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldLT(FieldRxRateMbps, v))
}

// RxRateMbpsLTE applies the LTE predicate on the "rx_rate_mbps" field.
func RxRateMbpsLTE(v float64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldLTE(FieldRxRateMbps, v))
}

// RxRateMbpsIsNil applies the IsNil predicate on the "rx_rate_mbps" field.
func RxRateMbpsIsNil() predicate.WifiSample {
	return predicate.WifiSample(sql.FieldIsNull(FieldRxRateMbps))
}

// RxRateMbpsNotNil applies the NotNil predicate on the "rx_rate_mbps" field.
func RxRateMbpsNotNil() predicate.WifiSample {
	return predicate.WifiSample(sql.FieldNotNull(FieldRxRateMbps))
}

// TxRateMbpsEQ applies the EQ predicate on the "tx_rate_mbps" field.
func TxRateMbpsEQ(v float64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldEQ(FieldTxRateMbps, v))
}

// TxRateMbpsNEQ applies the NEQ predicate on the "tx_rate_mbps" field.
func TxRateMbpsNEQ(v float64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldNEQ(FieldTxRateMbps, v))
}

// TxRateMbpsIn applies the In predicate on the "tx_rate_mbps" field.
func TxRateMbpsIn(vs ...float64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldIn(FieldTxRateMbps, vs...))
}

// TxRateMbpsNotIn applies the NotIn predicate on the "tx_rate_mbps" field.
func TxRateMbpsNotIn(vs ...float64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldNotIn(FieldTxRateMbps, vs...))
}

// TxRateMbpsGT applies the GT predicate on the "tx_rate_mbps" field.
func TxRateMbpsGT(v float64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldGT(FieldTxRateMbps, v))
}

// TxRateMbpsGTE applies the GTE predicate on the "tx_rate_mbps" field.
func TxRateMbpsGTE(v float64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldGTE(FieldTxRateMbps, v))
}

// TxRateMbpsLT applies the LT predicate on the "tx_rate_mbps" field.
func TxRateMbpsLT(v float64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldLT(FieldTxRateMbps, v))
}

// TxRateMbpsLTE applies the LTE predicate on the "tx_rate_mbps" field.
func TxRateMbpsLTE(v float64) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldLTE(FieldTxRateMbps, v))
}

// TxRateMbpsIsNil applies the IsNil predicate on the "tx_rate_mbps" field.
func TxRateMbpsIsNil() predicate.WifiSample {
	return predicate.WifiSample(sql.FieldIsNull(FieldTxRateMbps))
}

// TxRateMbpsNotNil applies the NotNil predicate on the "tx_rate_mbps" field.
func TxRateMbpsNotNil() predicate.WifiSample {
	return predicate.WifiSample(sql.FieldNotNull(FieldTxRateMbps))
}

// ChannelEQ applies the EQ predicate on the "channel" field.
func ChannelEQ(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldEQ(FieldChannel, v))
}

// ChannelNEQ applies the NEQ predicate on the "channel" field.
func ChannelNEQ(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldNEQ(FieldChannel, v))
}

// ChannelIn applies the In predicate on the "channel" field.
func ChannelIn(vs ...string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldIn(FieldChannel, vs...))
}

// ChannelNotIn applies the NotIn predicate on the "channel" field.
func ChannelNotIn(vs ...string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldNotIn(FieldChannel, vs...))
}

// ChannelGT applies the GT predicate on the "channel" field.
func ChannelGT(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldGT(FieldChannel, v))
}

// ChannelGTE applies the GTE predicate on the "channel" field.
func ChannelGTE(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldGTE(FieldChannel, v))
}

// ChannelLT applies the LT predicate on the "channel" field.
func ChannelLT(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldLT(FieldChannel, v))
}

// ChannelLTE applies the LTE predicate on the "channel" field.
func ChannelLTE(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldLTE(FieldChannel, v))
}

// ChannelContains applies the Contains predicate on the "channel" field.
func ChannelContains(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldContains(FieldChannel, v))
}

// ChannelHasPrefix applies the HasPrefix predicate on the "channel" field.
func ChannelHasPrefix(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldHasPrefix(FieldChannel, v))
}

// ChannelHasSuffix applies the HasSuffix predicate on the "channel" field.
func ChannelHasSuffix(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldHasSuffix(FieldChannel, v))
}

// ChannelIsNil applies the IsNil predicate on the "channel" field.
func ChannelIsNil() predicate.WifiSample {
	return predicate.WifiSample(sql.FieldIsNull(FieldChannel))
}

// ChannelNotNil applies the NotNil predicate on the "channel" field.
func ChannelNotNil() predicate.WifiSample {
	return predicate.WifiSample(sql.FieldNotNull(FieldChannel))
}

// ChannelEqualFold applies the EqualFold predicate on the "channel" field.
func ChannelEqualFold(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldEqualFold(FieldChannel, v))
}

// ChannelContainsFold applies the ContainsFold predicate on the "channel" field.
func ChannelContainsFold(v string) predicate.WifiSample {
	return predicate.WifiSample(sql.FieldContainsFold(FieldChannel, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WifiSample) predicate.WifiSample {
	return predicate.WifiSample(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WifiSample) predicate.WifiSample {
	return predicate.WifiSample(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WifiSample) predicate.WifiSample {
	return predicate.WifiSample(sql.NotPredicates(p))
}
