// Code generated by ent, DO NOT EDIT.

package wifisample

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the wifisample type in the database.
	Label = "wifi_sample"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTsUnixMs holds the string denoting the ts_unix_ms field in the database.
	FieldTsUnixMs = "ts_unix_ms"
	// FieldSsid holds the string denoting the ssid field in the database.
	FieldSsid = "ssid"
	// FieldBssid holds the string denoting the bssid field in the database.
	FieldBssid = "bssid"
	// FieldSignalPercent holds the string denoting the signal_percent field in the database.
	FieldSignalPercent = "signal_percent"
	// FieldRssiDbm holds the string denoting the rssi_dbm field in the database.
	FieldRssiDbm = "rssi_dbm"
	// FieldRxRateMbps holds the string denoting the rx_rate_mbps field in the database.
	FieldRxRateMbps = "rx_rate_mbps"
	// FieldTxRateMbps holds the string denoting the tx_rate_mbps field in the database.
	FieldTxRateMbps = "tx_rate_mbps"
	// FieldChannel holds the string denoting the channel field in the database.
	FieldChannel = "channel"
	// Table holds the table name of the wifisample in the database.
	Table = "wifi_samples"
)

// Columns holds all SQL columns for wifisample fields.
var Columns = []string{
	FieldID,
	FieldTsUnixMs,
	FieldSsid,
	FieldBssid,
	FieldSignalPercent,
	FieldRssiDbm,
	FieldRxRateMbps,
	FieldTxRateMbps,
	FieldChannel,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the WifiSample queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTsUnixMs orders the results by the ts_unix_ms field.
func ByTsUnixMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTsUnixMs, opts...).ToFunc()
}

// BySsid orders the results by the ssid field.
func BySsid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSsid, opts...).ToFunc()
}

// ByBssid orders the results by the bssid field.
func ByBssid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBssid, opts...).ToFunc()
}

// BySignalPercent orders the results by the signal_percent field.
func BySignalPercent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSignalPercent, opts...).ToFunc()
}

// ByRssiDbm orders the results by the rssi_dbm field.
func ByRssiDbm(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRssiDbm, opts...).ToFunc()
}

// ByRxRateMbps orders the results by the rx_rate_mbps field.
func ByRxRateMbps(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRxRateMbps, opts...).ToFunc()
}

// ByTxRateMbps orders the results by the tx_rate_mbps field.
func ByTxRateMbps(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTxRateMbps, opts...).ToFunc()
}

// ByChannel orders the results by the channel field.
func ByChannel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannel, opts...).ToFunc()
}
