// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AppConfigsColumns holds the columns for the "app_configs" table.
	AppConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ping_interval_sec", Type: field.TypeFloat64, Default: 2.5},
		{Name: "flush_interval_sec", Type: field.TypeInt, Default: 60},
		{Name: "ping_timeout_ms", Type: field.TypeInt, Default: 2000},
		{Name: "retention_raw_days", Type: field.TypeInt, Default: 7},
		{Name: "retention_1min_days", Type: field.TypeInt, Default: 14},
		{Name: "retention_5min_days", Type: field.TypeInt, Default: 90},
		{Name: "wifi_sample_enabled", Type: field.TypeBool, Default: true},
	}
	// AppConfigsTable holds the schema information for the "app_configs" table.
	AppConfigsTable = &schema.Table{
		Name:       "app_configs",
		Columns:    AppConfigsColumns,
		PrimaryKey: []*schema.Column{AppConfigsColumns[0]},
	}
	// OutagesColumns holds the columns for the "outages" table.
	OutagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "scope", Type: field.TypeString},
		{Name: "start_ts_unix_ms", Type: field.TypeInt64},
		{Name: "end_ts_unix_ms", Type: field.TypeInt64, Nullable: true},
		{Name: "consecutive_failures", Type: field.TypeInt},
		{Name: "errors", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// OutagesTable holds the schema information for the "outages" table.
	OutagesTable = &schema.Table{
		Name:       "outages",
		Columns:    OutagesColumns,
		PrimaryKey: []*schema.Column{OutagesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "outage_scope_start_ts_unix_ms",
				Unique:  false,
				Columns: []*schema.Column{OutagesColumns[1], OutagesColumns[2]},
			},
			{
				Name:    "outage_scope_end_ts_unix_ms",
				Unique:  false,
				Columns: []*schema.Column{OutagesColumns[1], OutagesColumns[3]},
			},
		},
	}
	// SamplesColumns holds the columns for the "samples" table.
	SamplesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ts_unix_ms", Type: field.TypeInt64},
		{Name: "target_label", Type: field.TypeString},
		{Name: "target_kind", Type: field.TypeString},
		{Name: "target_host", Type: field.TypeString},
		{Name: "target_port", Type: field.TypeInt, Nullable: true},
		{Name: "success", Type: field.TypeBool},
		{Name: "rtt_ms", Type: field.TypeFloat64, Nullable: true},
		{Name: "error", Type: field.TypeString, Nullable: true},
	}
	// SamplesTable holds the schema information for the "samples" table.
	SamplesTable = &schema.Table{
		Name:       "samples",
		Columns:    SamplesColumns,
		PrimaryKey: []*schema.Column{SamplesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sample_ts_unix_ms",
				Unique:  false,
				Columns: []*schema.Column{SamplesColumns[1]},
			},
			{
				Name:    "sample_target_label_ts_unix_ms",
				Unique:  false,
				Columns: []*schema.Column{SamplesColumns[2], SamplesColumns[1]},
			},
		},
	}
	// Sample1hsColumns holds the columns for the "sample1hs" table.
	Sample1hsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "bucket_start_unix_ms", Type: field.TypeInt64},
		{Name: "target_label", Type: field.TypeString},
		{Name: "count", Type: field.TypeInt},
		{Name: "success_count", Type: field.TypeInt},
		{Name: "fail_count", Type: field.TypeInt},
		{Name: "rtt_p50_ms", Type: field.TypeFloat64, Nullable: true},
		{Name: "rtt_p95_ms", Type: field.TypeFloat64, Nullable: true},
		{Name: "rtt_p99_ms", Type: field.TypeFloat64, Nullable: true},
		{Name: "rtt_max_ms", Type: field.TypeFloat64, Nullable: true},
		{Name: "rtt_mean_ms", Type: field.TypeFloat64, Nullable: true},
		{Name: "jitter_ms", Type: field.TypeFloat64, Nullable: true},
		{Name: "errors", Type: field.TypeJSON, Nullable: true},
	}
	// Sample1hsTable holds the schema information for the "sample1hs" table.
	Sample1hsTable = &schema.Table{
		Name:       "sample1hs",
		Columns:    Sample1hsColumns,
		PrimaryKey: []*schema.Column{Sample1hsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sample1h_bucket_start_unix_ms_target_label",
				Unique:  true,
				Columns: []*schema.Column{Sample1hsColumns[1], Sample1hsColumns[2]},
			},
			{
				Name:    "sample1h_bucket_start_unix_ms",
				Unique:  false,
				Columns: []*schema.Column{Sample1hsColumns[1]},
			},
		},
	}
	// Sample1minsColumns holds the columns for the "sample1mins" table.
	Sample1minsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "bucket_start_unix_ms", Type: field.TypeInt64},
		{Name: "target_label", Type: field.TypeString},
		{Name: "count", Type: field.TypeInt},
		{Name: "success_count", Type: field.TypeInt},
		{Name: "fail_count", Type: field.TypeInt},
		{Name: "rtt_p50_ms", Type: field.TypeFloat64, Nullable: true},
		{Name: "rtt_p95_ms", Type: field.TypeFloat64, Nullable: true},
		{Name: "rtt_p99_ms", Type: field.TypeFloat64, Nullable: true},
		{Name: "rtt_max_ms", Type: field.TypeFloat64, Nullable: true},
		{Name: "rtt_mean_ms", Type: field.TypeFloat64, Nullable: true},
		{Name: "jitter_ms", Type: field.TypeFloat64, Nullable: true},
		{Name: "errors", Type: field.TypeJSON, Nullable: true},
	}
	// Sample1minsTable holds the schema information for the "sample1mins" table.
	Sample1minsTable = &schema.Table{
		Name:       "sample1mins",
		Columns:    Sample1minsColumns,
		PrimaryKey: []*schema.Column{Sample1minsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sample1min_bucket_start_unix_ms_target_label",
				Unique:  true,
				Columns: []*schema.Column{Sample1minsColumns[1], Sample1minsColumns[2]},
			},
			{
				Name:    "sample1min_bucket_start_unix_ms",
				Unique:  false,
				Columns: []*schema.Column{Sample1minsColumns[1]},
			},
		},
	}
	// Sample5minsColumns holds the columns for the "sample5mins" table.
	Sample5minsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "bucket_start_unix_ms", Type: field.TypeInt64},
		{Name: "target_label", Type: field.TypeString},
		{Name: "count", Type: field.TypeInt},
		{Name: "success_count", Type: field.TypeInt},
		{Name: "fail_count", Type: field.TypeInt},
		{Name: "rtt_p50_ms", Type: field.TypeFloat64, Nullable: true},
		{Name: "rtt_p95_ms", Type: field.TypeFloat64, Nullable: true},
		{Name: "rtt_p99_ms", Type: field.TypeFloat64, Nullable: true},
		{Name: "rtt_max_ms", Type: field.TypeFloat64, Nullable: true},
		{Name: "rtt_mean_ms", Type: field.TypeFloat64, Nullable: true},
		{Name: "jitter_ms", Type: field.TypeFloat64, Nullable: true},
		{Name: "errors", Type: field.TypeJSON, Nullable: true},
	}
	// Sample5minsTable holds the schema information for the "sample5mins" table.
	Sample5minsTable = &schema.Table{
		Name:       "sample5mins",
		Columns:    Sample5minsColumns,
		PrimaryKey: []*schema.Column{Sample5minsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sample5min_bucket_start_unix_ms_target_label",
				Unique:  true,
				Columns: []*schema.Column{Sample5minsColumns[1], Sample5minsColumns[2]},
			},
			{
				Name:    "sample5min_bucket_start_unix_ms",
				Unique:  false,
				Columns: []*schema.Column{Sample5minsColumns[1]},
			},
		},
	}
	// TargetsColumns holds the columns for the "targets" table.
	TargetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "label", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "kind", Type: field.TypeEnum, Enums: []string{"icmp", "tcp", "udp_dns", "udp_stun"}},
		{Name: "host", Type: field.TypeString},
		{Name: "port", Type: field.TypeInt, Nullable: true},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "is_builtin", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TargetsTable holds the schema information for the "targets" table.
	TargetsTable = &schema.Table{
		Name:       "targets",
		Columns:    TargetsColumns,
		PrimaryKey: []*schema.Column{TargetsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "target_enabled_kind",
				Unique:  false,
				Columns: []*schema.Column{TargetsColumns[5], TargetsColumns[2]},
			},
		},
	}
	// WifiSamplesColumns holds the columns for the "wifi_samples" table.
	WifiSamplesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ts_unix_ms", Type: field.TypeInt64},
		{Name: "ssid", Type: field.TypeString, Nullable: true},
		{Name: "bssid", Type: field.TypeString, Nullable: true},
		{Name: "signal_percent", Type: field.TypeInt, Nullable: true},
		{Name: "rssi_dbm", Type: field.TypeInt, Nullable: true},
		{Name: "rx_rate_mbps", Type: field.TypeFloat64, Nullable: true},
		{Name: "tx_rate_mbps", Type: field.TypeFloat64, Nullable: true},
		{Name: "channel", Type: field.TypeString, Nullable: true},
	}
	// WifiSamplesTable holds the schema information for the "wifi_samples" table.
	WifiSamplesTable = &schema.Table{
		Name:       "wifi_samples",
		Columns:    WifiSamplesColumns,
		PrimaryKey: []*schema.Column{WifiSamplesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "wifisample_ts_unix_ms",
				Unique:  false,
				Columns: []*schema.Column{WifiSamplesColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AppConfigsTable,
		OutagesTable,
		SamplesTable,
		Sample1hsTable,
		Sample1minsTable,
		Sample5minsTable,
		TargetsTable,
		WifiSamplesTable,
	}
)

func init() {
}
