// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AppConfig is the predicate function for appconfig builders.
type AppConfig func(*sql.Selector)

// Outage is the predicate function for outage builders.
type Outage func(*sql.Selector)

// Sample is the predicate function for sample builders.
type Sample func(*sql.Selector)

// Sample1h is the predicate function for sample1h builders.
type Sample1h func(*sql.Selector)

// Sample5min is the predicate function for sample5min builders.
type Sample5min func(*sql.Selector)

// Target is the predicate function for target builders.
type Target func(*sql.Selector)

// WifiSample is the predicate function for wifisample builders.
type WifiSample func(*sql.Selector)
