// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sid-technologies/vigil/db/ent/appconfig"
	"github.com/sid-technologies/vigil/db/ent/predicate"
)

// AppConfigUpdate is the builder for updating AppConfig entities.
type AppConfigUpdate struct {
	config
	hooks    []Hook
	mutation *AppConfigMutation
}

// Where appends a list predicates to the AppConfigUpdate builder.
func (_u *AppConfigUpdate) Where(ps ...predicate.AppConfig) *AppConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPingIntervalSec sets the "ping_interval_sec" field.
func (_u *AppConfigUpdate) SetPingIntervalSec(v float64) *AppConfigUpdate {
	_u.mutation.ResetPingIntervalSec()
	_u.mutation.SetPingIntervalSec(v)
	return _u
}

// SetNillablePingIntervalSec sets the "ping_interval_sec" field if the given value is not nil.
func (_u *AppConfigUpdate) SetNillablePingIntervalSec(v *float64) *AppConfigUpdate {
	if v != nil {
		_u.SetPingIntervalSec(*v)
	}
	return _u
}

// AddPingIntervalSec adds value to the "ping_interval_sec" field.
func (_u *AppConfigUpdate) AddPingIntervalSec(v float64) *AppConfigUpdate {
	_u.mutation.AddPingIntervalSec(v)
	return _u
}

// SetFlushIntervalSec sets the "flush_interval_sec" field.
func (_u *AppConfigUpdate) SetFlushIntervalSec(v int) *AppConfigUpdate {
	_u.mutation.ResetFlushIntervalSec()
	_u.mutation.SetFlushIntervalSec(v)
	return _u
}

// SetNillableFlushIntervalSec sets the "flush_interval_sec" field if the given value is not nil.
func (_u *AppConfigUpdate) SetNillableFlushIntervalSec(v *int) *AppConfigUpdate {
	if v != nil {
		_u.SetFlushIntervalSec(*v)
	}
	return _u
}

// AddFlushIntervalSec adds value to the "flush_interval_sec" field.
func (_u *AppConfigUpdate) AddFlushIntervalSec(v int) *AppConfigUpdate {
	_u.mutation.AddFlushIntervalSec(v)
	return _u
}

// SetPingTimeoutMs sets the "ping_timeout_ms" field.
func (_u *AppConfigUpdate) SetPingTimeoutMs(v int) *AppConfigUpdate {
	_u.mutation.ResetPingTimeoutMs()
	_u.mutation.SetPingTimeoutMs(v)
	return _u
}

// SetNillablePingTimeoutMs sets the "ping_timeout_ms" field if the given value is not nil.
func (_u *AppConfigUpdate) SetNillablePingTimeoutMs(v *int) *AppConfigUpdate {
	if v != nil {
		_u.SetPingTimeoutMs(*v)
	}
	return _u
}

// AddPingTimeoutMs adds value to the "ping_timeout_ms" field.
func (_u *AppConfigUpdate) AddPingTimeoutMs(v int) *AppConfigUpdate {
	_u.mutation.AddPingTimeoutMs(v)
	return _u
}

// SetRetentionRawDays sets the "retention_raw_days" field.
func (_u *AppConfigUpdate) SetRetentionRawDays(v int) *AppConfigUpdate {
	_u.mutation.ResetRetentionRawDays()
	_u.mutation.SetRetentionRawDays(v)
	return _u
}

// SetNillableRetentionRawDays sets the "retention_raw_days" field if the given value is not nil.
func (_u *AppConfigUpdate) SetNillableRetentionRawDays(v *int) *AppConfigUpdate {
	if v != nil {
		_u.SetRetentionRawDays(*v)
	}
	return _u
}

// AddRetentionRawDays adds value to the "retention_raw_days" field.
func (_u *AppConfigUpdate) AddRetentionRawDays(v int) *AppConfigUpdate {
	_u.mutation.AddRetentionRawDays(v)
	return _u
}

// SetRetention1minDays sets the "retention_1min_days" field.
func (_u *AppConfigUpdate) SetRetention1minDays(v int) *AppConfigUpdate {
	_u.mutation.ResetRetention1minDays()
	_u.mutation.SetRetention1minDays(v)
	return _u
}

// SetNillableRetention1minDays sets the "retention_1min_days" field if the given value is not nil.
func (_u *AppConfigUpdate) SetNillableRetention1minDays(v *int) *AppConfigUpdate {
	if v != nil {
		_u.SetRetention1minDays(*v)
	}
	return _u
}

// AddRetention1minDays adds value to the "retention_1min_days" field.
func (_u *AppConfigUpdate) AddRetention1minDays(v int) *AppConfigUpdate {
	_u.mutation.AddRetention1minDays(v)
	return _u
}

// SetRetention5minDays sets the "retention_5min_days" field.
func (_u *AppConfigUpdate) SetRetention5minDays(v int) *AppConfigUpdate {
	_u.mutation.ResetRetention5minDays()
	_u.mutation.SetRetention5minDays(v)
	return _u
}

// SetNillableRetention5minDays sets the "retention_5min_days" field if the given value is not nil.
func (_u *AppConfigUpdate) SetNillableRetention5minDays(v *int) *AppConfigUpdate {
	if v != nil {
		_u.SetRetention5minDays(*v)
	}
	return _u
}

// AddRetention5minDays adds value to the "retention_5min_days" field.
func (_u *AppConfigUpdate) AddRetention5minDays(v int) *AppConfigUpdate {
	_u.mutation.AddRetention5minDays(v)
	return _u
}

// SetWifiSampleEnabled sets the "wifi_sample_enabled" field.
func (_u *AppConfigUpdate) SetWifiSampleEnabled(v bool) *AppConfigUpdate {
	_u.mutation.SetWifiSampleEnabled(v)
	return _u
}

// SetNillableWifiSampleEnabled sets the "wifi_sample_enabled" field if the given value is not nil.
func (_u *AppConfigUpdate) SetNillableWifiSampleEnabled(v *bool) *AppConfigUpdate {
	if v != nil {
		_u.SetWifiSampleEnabled(*v)
	}
	return _u
}

// Mutation returns the AppConfigMutation object of the builder.
func (_u *AppConfigUpdate) Mutation() *AppConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AppConfigUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AppConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AppConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(appconfig.Table, appconfig.Columns, sqlgraph.NewFieldSpec(appconfig.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PingIntervalSec(); ok {
		_spec.SetField(appconfig.FieldPingIntervalSec, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPingIntervalSec(); ok {
		_spec.AddField(appconfig.FieldPingIntervalSec, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FlushIntervalSec(); ok {
		_spec.SetField(appconfig.FieldFlushIntervalSec, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFlushIntervalSec(); ok {
		_spec.AddField(appconfig.FieldFlushIntervalSec, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PingTimeoutMs(); ok {
		_spec.SetField(appconfig.FieldPingTimeoutMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPingTimeoutMs(); ok {
		_spec.AddField(appconfig.FieldPingTimeoutMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RetentionRawDays(); ok {
		_spec.SetField(appconfig.FieldRetentionRawDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetentionRawDays(); ok {
		_spec.AddField(appconfig.FieldRetentionRawDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Retention1minDays(); ok {
		_spec.SetField(appconfig.FieldRetention1minDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetention1minDays(); ok {
		_spec.AddField(appconfig.FieldRetention1minDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Retention5minDays(); ok {
		_spec.SetField(appconfig.FieldRetention5minDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetention5minDays(); ok {
		_spec.AddField(appconfig.FieldRetention5minDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WifiSampleEnabled(); ok {
		_spec.SetField(appconfig.FieldWifiSampleEnabled, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AppConfigUpdateOne is the builder for updating a single AppConfig entity.
type AppConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppConfigMutation
}

// SetPingIntervalSec sets the "ping_interval_sec" field.
func (_u *AppConfigUpdateOne) SetPingIntervalSec(v float64) *AppConfigUpdateOne {
	_u.mutation.ResetPingIntervalSec()
	_u.mutation.SetPingIntervalSec(v)
	return _u
}

// SetNillablePingIntervalSec sets the "ping_interval_sec" field if the given value is not nil.
func (_u *AppConfigUpdateOne) SetNillablePingIntervalSec(v *float64) *AppConfigUpdateOne {
	if v != nil {
		_u.SetPingIntervalSec(*v)
	}
	return _u
}

// AddPingIntervalSec adds value to the "ping_interval_sec" field.
func (_u *AppConfigUpdateOne) AddPingIntervalSec(v float64) *AppConfigUpdateOne {
	_u.mutation.AddPingIntervalSec(v)
	return _u
}

// SetFlushIntervalSec sets the "flush_interval_sec" field.
func (_u *AppConfigUpdateOne) SetFlushIntervalSec(v int) *AppConfigUpdateOne {
	_u.mutation.ResetFlushIntervalSec()
	_u.mutation.SetFlushIntervalSec(v)
	return _u
}

// SetNillableFlushIntervalSec sets the "flush_interval_sec" field if the given value is not nil.
func (_u *AppConfigUpdateOne) SetNillableFlushIntervalSec(v *int) *AppConfigUpdateOne {
	if v != nil {
		_u.SetFlushIntervalSec(*v)
	}
	return _u
}

// AddFlushIntervalSec adds value to the "flush_interval_sec" field.
func (_u *AppConfigUpdateOne) AddFlushIntervalSec(v int) *AppConfigUpdateOne {
	_u.mutation.AddFlushIntervalSec(v)
	return _u
}

// SetPingTimeoutMs sets the "ping_timeout_ms" field.
func (_u *AppConfigUpdateOne) SetPingTimeoutMs(v int) *AppConfigUpdateOne {
	_u.mutation.ResetPingTimeoutMs()
	_u.mutation.SetPingTimeoutMs(v)
	return _u
}

// SetNillablePingTimeoutMs sets the "ping_timeout_ms" field if the given value is not nil.
func (_u *AppConfigUpdateOne) SetNillablePingTimeoutMs(v *int) *AppConfigUpdateOne {
	if v != nil {
		_u.SetPingTimeoutMs(*v)
	}
	return _u
}

// AddPingTimeoutMs adds value to the "ping_timeout_ms" field.
func (_u *AppConfigUpdateOne) AddPingTimeoutMs(v int) *AppConfigUpdateOne {
	_u.mutation.AddPingTimeoutMs(v)
	return _u
}

// SetRetentionRawDays sets the "retention_raw_days" field.
func (_u *AppConfigUpdateOne) SetRetentionRawDays(v int) *AppConfigUpdateOne {
	_u.mutation.ResetRetentionRawDays()
	_u.mutation.SetRetentionRawDays(v)
	return _u
}

// SetNillableRetentionRawDays sets the "retention_raw_days" field if the given value is not nil.
func (_u *AppConfigUpdateOne) SetNillableRetentionRawDays(v *int) *AppConfigUpdateOne {
	if v != nil {
		_u.SetRetentionRawDays(*v)
	}
	return _u
}

// AddRetentionRawDays adds value to the "retention_raw_days" field.
func (_u *AppConfigUpdateOne) AddRetentionRawDays(v int) *AppConfigUpdateOne {
	_u.mutation.AddRetentionRawDays(v)
	return _u
}

// SetRetention1minDays sets the "retention_1min_days" field.
func (_u *AppConfigUpdateOne) SetRetention1minDays(v int) *AppConfigUpdateOne {
	_u.mutation.ResetRetention1minDays()
	_u.mutation.SetRetention1minDays(v)
	return _u
}

// SetNillableRetention1minDays sets the "retention_1min_days" field if the given value is not nil.
func (_u *AppConfigUpdateOne) SetNillableRetention1minDays(v *int) *AppConfigUpdateOne {
	if v != nil {
		_u.SetRetention1minDays(*v)
	}
	return _u
}

// AddRetention1minDays adds value to the "retention_1min_days" field.
func (_u *AppConfigUpdateOne) AddRetention1minDays(v int) *AppConfigUpdateOne {
	_u.mutation.AddRetention1minDays(v)
	return _u
}

// SetRetention5minDays sets the "retention_5min_days" field.
func (_u *AppConfigUpdateOne) SetRetention5minDays(v int) *AppConfigUpdateOne {
	_u.mutation.ResetRetention5minDays()
	_u.mutation.SetRetention5minDays(v)
	return _u
}

// SetNillableRetention5minDays sets the "retention_5min_days" field if the given value is not nil.
func (_u *AppConfigUpdateOne) SetNillableRetention5minDays(v *int) *AppConfigUpdateOne {
	if v != nil {
		_u.SetRetention5minDays(*v)
	}
	return _u
}

// AddRetention5minDays adds value to the "retention_5min_days" field.
func (_u *AppConfigUpdateOne) AddRetention5minDays(v int) *AppConfigUpdateOne {
	_u.mutation.AddRetention5minDays(v)
	return _u
}

// SetWifiSampleEnabled sets the "wifi_sample_enabled" field.
func (_u *AppConfigUpdateOne) SetWifiSampleEnabled(v bool) *AppConfigUpdateOne {
	_u.mutation.SetWifiSampleEnabled(v)
	return _u
}

// SetNillableWifiSampleEnabled sets the "wifi_sample_enabled" field if the given value is not nil.
func (_u *AppConfigUpdateOne) SetNillableWifiSampleEnabled(v *bool) *AppConfigUpdateOne {
	if v != nil {
		_u.SetWifiSampleEnabled(*v)
	}
	return _u
}

// Mutation returns the AppConfigMutation object of the builder.
func (_u *AppConfigUpdateOne) Mutation() *AppConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the AppConfigUpdate builder.
func (_u *AppConfigUpdateOne) Where(ps ...predicate.AppConfig) *AppConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AppConfigUpdateOne) Select(field string, fields ...string) *AppConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AppConfig entity.
func (_u *AppConfigUpdateOne) Save(ctx context.Context) (*AppConfig, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppConfigUpdateOne) SaveX(ctx context.Context) *AppConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AppConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AppConfigUpdateOne) sqlSave(ctx context.Context) (_node *AppConfig, err error) {
	_spec := sqlgraph.NewUpdateSpec(appconfig.Table, appconfig.Columns, sqlgraph.NewFieldSpec(appconfig.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AppConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appconfig.FieldID)
		for _, f := range fields {
			if !appconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != appconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PingIntervalSec(); ok {
		_spec.SetField(appconfig.FieldPingIntervalSec, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPingIntervalSec(); ok {
		_spec.AddField(appconfig.FieldPingIntervalSec, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FlushIntervalSec(); ok {
		_spec.SetField(appconfig.FieldFlushIntervalSec, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFlushIntervalSec(); ok {
		_spec.AddField(appconfig.FieldFlushIntervalSec, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PingTimeoutMs(); ok {
		_spec.SetField(appconfig.FieldPingTimeoutMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPingTimeoutMs(); ok {
		_spec.AddField(appconfig.FieldPingTimeoutMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RetentionRawDays(); ok {
		_spec.SetField(appconfig.FieldRetentionRawDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetentionRawDays(); ok {
		_spec.AddField(appconfig.FieldRetentionRawDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Retention1minDays(); ok {
		_spec.SetField(appconfig.FieldRetention1minDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetention1minDays(); ok {
		_spec.AddField(appconfig.FieldRetention1minDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Retention5minDays(); ok {
		_spec.SetField(appconfig.FieldRetention5minDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetention5minDays(); ok {
		_spec.AddField(appconfig.FieldRetention5minDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WifiSampleEnabled(); ok {
		_spec.SetField(appconfig.FieldWifiSampleEnabled, field.TypeBool, value)
	}
	_node = &AppConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
