// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sid-technologies/vigil/db/ent/appconfig"
)

// AppConfigCreate is the builder for creating a AppConfig entity.
type AppConfigCreate struct {
	config
	mutation *AppConfigMutation
	hooks    []Hook
}

// SetPingIntervalSec sets the "ping_interval_sec" field.
func (_c *AppConfigCreate) SetPingIntervalSec(v float64) *AppConfigCreate {
	_c.mutation.SetPingIntervalSec(v)
	return _c
}

// SetNillablePingIntervalSec sets the "ping_interval_sec" field if the given value is not nil.
func (_c *AppConfigCreate) SetNillablePingIntervalSec(v *float64) *AppConfigCreate {
	if v != nil {
		_c.SetPingIntervalSec(*v)
	}
	return _c
}

// SetFlushIntervalSec sets the "flush_interval_sec" field.
func (_c *AppConfigCreate) SetFlushIntervalSec(v int) *AppConfigCreate {
	_c.mutation.SetFlushIntervalSec(v)
	return _c
}

// SetNillableFlushIntervalSec sets the "flush_interval_sec" field if the given value is not nil.
func (_c *AppConfigCreate) SetNillableFlushIntervalSec(v *int) *AppConfigCreate {
	if v != nil {
		_c.SetFlushIntervalSec(*v)
	}
	return _c
}

// SetPingTimeoutMs sets the "ping_timeout_ms" field.
func (_c *AppConfigCreate) SetPingTimeoutMs(v int) *AppConfigCreate {
	_c.mutation.SetPingTimeoutMs(v)
	return _c
}

// SetNillablePingTimeoutMs sets the "ping_timeout_ms" field if the given value is not nil.
func (_c *AppConfigCreate) SetNillablePingTimeoutMs(v *int) *AppConfigCreate {
	if v != nil {
		_c.SetPingTimeoutMs(*v)
	}
	return _c
}

// SetRetentionRawDays sets the "retention_raw_days" field.
func (_c *AppConfigCreate) SetRetentionRawDays(v int) *AppConfigCreate {
	_c.mutation.SetRetentionRawDays(v)
	return _c
}

// SetNillableRetentionRawDays sets the "retention_raw_days" field if the given value is not nil.
func (_c *AppConfigCreate) SetNillableRetentionRawDays(v *int) *AppConfigCreate {
	if v != nil {
		_c.SetRetentionRawDays(*v)
	}
	return _c
}

// SetRetention1minDays sets the "retention_1min_days" field.
func (_c *AppConfigCreate) SetRetention1minDays(v int) *AppConfigCreate {
	_c.mutation.SetRetention1minDays(v)
	return _c
}

// SetNillableRetention1minDays sets the "retention_1min_days" field if the given value is not nil.
func (_c *AppConfigCreate) SetNillableRetention1minDays(v *int) *AppConfigCreate {
	if v != nil {
		_c.SetRetention1minDays(*v)
	}
	return _c
}

// SetRetention5minDays sets the "retention_5min_days" field.
func (_c *AppConfigCreate) SetRetention5minDays(v int) *AppConfigCreate {
	_c.mutation.SetRetention5minDays(v)
	return _c
}

// SetNillableRetention5minDays sets the "retention_5min_days" field if the given value is not nil.
func (_c *AppConfigCreate) SetNillableRetention5minDays(v *int) *AppConfigCreate {
	if v != nil {
		_c.SetRetention5minDays(*v)
	}
	return _c
}

// SetWifiSampleEnabled sets the "wifi_sample_enabled" field.
func (_c *AppConfigCreate) SetWifiSampleEnabled(v bool) *AppConfigCreate {
	_c.mutation.SetWifiSampleEnabled(v)
	return _c
}

// SetNillableWifiSampleEnabled sets the "wifi_sample_enabled" field if the given value is not nil.
func (_c *AppConfigCreate) SetNillableWifiSampleEnabled(v *bool) *AppConfigCreate {
	if v != nil {
		_c.SetWifiSampleEnabled(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AppConfigCreate) SetID(v int) *AppConfigCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AppConfigMutation object of the builder.
func (_c *AppConfigCreate) Mutation() *AppConfigMutation {
	return _c.mutation
}

// Save creates the AppConfig in the database.
func (_c *AppConfigCreate) Save(ctx context.Context) (*AppConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AppConfigCreate) SaveX(ctx context.Context) *AppConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AppConfigCreate) defaults() {
	if _, ok := _c.mutation.PingIntervalSec(); !ok {
		v := appconfig.DefaultPingIntervalSec
		_c.mutation.SetPingIntervalSec(v)
	}
	if _, ok := _c.mutation.FlushIntervalSec(); !ok {
		v := appconfig.DefaultFlushIntervalSec
		_c.mutation.SetFlushIntervalSec(v)
	}
	if _, ok := _c.mutation.PingTimeoutMs(); !ok {
		v := appconfig.DefaultPingTimeoutMs
		_c.mutation.SetPingTimeoutMs(v)
	}
	if _, ok := _c.mutation.RetentionRawDays(); !ok {
		v := appconfig.DefaultRetentionRawDays
		_c.mutation.SetRetentionRawDays(v)
	}
	if _, ok := _c.mutation.Retention1minDays(); !ok {
		v := appconfig.DefaultRetention1minDays
		_c.mutation.SetRetention1minDays(v)
	}
	if _, ok := _c.mutation.Retention5minDays(); !ok {
		v := appconfig.DefaultRetention5minDays
		_c.mutation.SetRetention5minDays(v)
	}
	if _, ok := _c.mutation.WifiSampleEnabled(); !ok {
		v := appconfig.DefaultWifiSampleEnabled
		_c.mutation.SetWifiSampleEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AppConfigCreate) check() error {
	if _, ok := _c.mutation.PingIntervalSec(); !ok {
		return &ValidationError{Name: "ping_interval_sec", err: errors.New(`ent: missing required field "AppConfig.ping_interval_sec"`)}
	}
	if _, ok := _c.mutation.FlushIntervalSec(); !ok {
		return &ValidationError{Name: "flush_interval_sec", err: errors.New(`ent: missing required field "AppConfig.flush_interval_sec"`)}
	}
	if _, ok := _c.mutation.PingTimeoutMs(); !ok {
		return &ValidationError{Name: "ping_timeout_ms", err: errors.New(`ent: missing required field "AppConfig.ping_timeout_ms"`)}
	}
	if _, ok := _c.mutation.RetentionRawDays(); !ok {
		return &ValidationError{Name: "retention_raw_days", err: errors.New(`ent: missing required field "AppConfig.retention_raw_days"`)}
	}
	if _, ok := _c.mutation.Retention1minDays(); !ok {
		return &ValidationError{Name: "retention_1min_days", err: errors.New(`ent: missing required field "AppConfig.retention_1min_days"`)}
	}
	if _, ok := _c.mutation.Retention5minDays(); !ok {
		return &ValidationError{Name: "retention_5min_days", err: errors.New(`ent: missing required field "AppConfig.retention_5min_days"`)}
	}
	if _, ok := _c.mutation.WifiSampleEnabled(); !ok {
		return &ValidationError{Name: "wifi_sample_enabled", err: errors.New(`ent: missing required field "AppConfig.wifi_sample_enabled"`)}
	}
	return nil
}

func (_c *AppConfigCreate) sqlSave(ctx context.Context) (*AppConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AppConfigCreate) createSpec() (*AppConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &AppConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(appconfig.Table, sqlgraph.NewFieldSpec(appconfig.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.PingIntervalSec(); ok {
		_spec.SetField(appconfig.FieldPingIntervalSec, field.TypeFloat64, value)
		_node.PingIntervalSec = value
	}
	if value, ok := _c.mutation.FlushIntervalSec(); ok {
		_spec.SetField(appconfig.FieldFlushIntervalSec, field.TypeInt, value)
		_node.FlushIntervalSec = value
	}
	if value, ok := _c.mutation.PingTimeoutMs(); ok {
		_spec.SetField(appconfig.FieldPingTimeoutMs, field.TypeInt, value)
		_node.PingTimeoutMs = value
	}
	if value, ok := _c.mutation.RetentionRawDays(); ok {
		_spec.SetField(appconfig.FieldRetentionRawDays, field.TypeInt, value)
		_node.RetentionRawDays = value
	}
	if value, ok := _c.mutation.Retention1minDays(); ok {
		_spec.SetField(appconfig.FieldRetention1minDays, field.TypeInt, value)
		_node.Retention1minDays = value
	}
	if value, ok := _c.mutation.Retention5minDays(); ok {
		_spec.SetField(appconfig.FieldRetention5minDays, field.TypeInt, value)
		_node.Retention5minDays = value
	}
	if value, ok := _c.mutation.WifiSampleEnabled(); ok {
		_spec.SetField(appconfig.FieldWifiSampleEnabled, field.TypeBool, value)
		_node.WifiSampleEnabled = value
	}
	return _node, _spec
}

// AppConfigCreateBulk is the builder for creating many AppConfig entities in bulk.
type AppConfigCreateBulk struct {
	config
	err      error
	builders []*AppConfigCreate
}

// Save creates the AppConfig entities in the database.
func (_c *AppConfigCreateBulk) Save(ctx context.Context) ([]*AppConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AppConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AppConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AppConfigCreateBulk) SaveX(ctx context.Context) []*AppConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
