// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/sid-technologies/vigil/db/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/sid-technologies/vigil/db/ent/appconfig"
	"github.com/sid-technologies/vigil/db/ent/outage"
	"github.com/sid-technologies/vigil/db/ent/sample"
	"github.com/sid-technologies/vigil/db/ent/sample1h"
	"github.com/sid-technologies/vigil/db/ent/sample1min"
	"github.com/sid-technologies/vigil/db/ent/sample5min"
	"github.com/sid-technologies/vigil/db/ent/target"
	"github.com/sid-technologies/vigil/db/ent/wifisample"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AppConfig is the client for interacting with the AppConfig builders.
	AppConfig *AppConfigClient
	// Outage is the client for interacting with the Outage builders.
	Outage *OutageClient
	// Sample is the client for interacting with the Sample builders.
	Sample *SampleClient
	// Sample1h is the client for interacting with the Sample1h builders.
	Sample1h *Sample1hClient
	// Sample1min is the client for interacting with the Sample1min builders.
	Sample1min *Sample1minClient
	// Sample5min is the client for interacting with the Sample5min builders.
	Sample5min *Sample5minClient
	// Target is the client for interacting with the Target builders.
	Target *TargetClient
	// WifiSample is the client for interacting with the WifiSample builders.
	WifiSample *WifiSampleClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AppConfig = NewAppConfigClient(c.config)
	c.Outage = NewOutageClient(c.config)
	c.Sample = NewSampleClient(c.config)
	c.Sample1h = NewSample1hClient(c.config)
	c.Sample1min = NewSample1minClient(c.config)
	c.Sample5min = NewSample5minClient(c.config)
	c.Target = NewTargetClient(c.config)
	c.WifiSample = NewWifiSampleClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		AppConfig:  NewAppConfigClient(cfg),
		Outage:     NewOutageClient(cfg),
		Sample:     NewSampleClient(cfg),
		Sample1h:   NewSample1hClient(cfg),
		Sample1min: NewSample1minClient(cfg),
		Sample5min: NewSample5minClient(cfg),
		Target:     NewTargetClient(cfg),
		WifiSample: NewWifiSampleClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		AppConfig:  NewAppConfigClient(cfg),
		Outage:     NewOutageClient(cfg),
		Sample:     NewSampleClient(cfg),
		Sample1h:   NewSample1hClient(cfg),
		Sample1min: NewSample1minClient(cfg),
		Sample5min: NewSample5minClient(cfg),
		Target:     NewTargetClient(cfg),
		WifiSample: NewWifiSampleClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AppConfig.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.AppConfig, c.Outage, c.Sample, c.Sample1h, c.Sample1min, c.Sample5min,
		c.Target, c.WifiSample,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.AppConfig, c.Outage, c.Sample, c.Sample1h, c.Sample1min, c.Sample5min,
		c.Target, c.WifiSample,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AppConfigMutation:
		return c.AppConfig.mutate(ctx, m)
	case *OutageMutation:
		return c.Outage.mutate(ctx, m)
	case *SampleMutation:
		return c.Sample.mutate(ctx, m)
	case *Sample1hMutation:
		return c.Sample1h.mutate(ctx, m)
	case *Sample1minMutation:
		return c.Sample1min.mutate(ctx, m)
	case *Sample5minMutation:
		return c.Sample5min.mutate(ctx, m)
	case *TargetMutation:
		return c.Target.mutate(ctx, m)
	case *WifiSampleMutation:
		return c.WifiSample.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AppConfigClient is a client for the AppConfig schema.
type AppConfigClient struct {
	config
}

// NewAppConfigClient returns a client for the AppConfig from the given config.
func NewAppConfigClient(c config) *AppConfigClient {
	return &AppConfigClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `appconfig.Hooks(f(g(h())))`.
func (c *AppConfigClient) Use(hooks ...Hook) {
	c.hooks.AppConfig = append(c.hooks.AppConfig, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `appconfig.Intercept(f(g(h())))`.
func (c *AppConfigClient) Intercept(interceptors ...Interceptor) {
	c.inters.AppConfig = append(c.inters.AppConfig, interceptors...)
}

// Create returns a builder for creating a AppConfig entity.
func (c *AppConfigClient) Create() *AppConfigCreate {
	mutation := newAppConfigMutation(c.config, OpCreate)
	return &AppConfigCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AppConfig entities.
func (c *AppConfigClient) CreateBulk(builders ...*AppConfigCreate) *AppConfigCreateBulk {
	return &AppConfigCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AppConfigClient) MapCreateBulk(slice any, setFunc func(*AppConfigCreate, int)) *AppConfigCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AppConfigCreateBulk{err: fmt.Errorf("calling to AppConfigClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AppConfigCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AppConfigCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AppConfig.
func (c *AppConfigClient) Update() *AppConfigUpdate {
	mutation := newAppConfigMutation(c.config, OpUpdate)
	return &AppConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AppConfigClient) UpdateOne(_m *AppConfig) *AppConfigUpdateOne {
	mutation := newAppConfigMutation(c.config, OpUpdateOne, withAppConfig(_m))
	return &AppConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AppConfigClient) UpdateOneID(id int) *AppConfigUpdateOne {
	mutation := newAppConfigMutation(c.config, OpUpdateOne, withAppConfigID(id))
	return &AppConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AppConfig.
func (c *AppConfigClient) Delete() *AppConfigDelete {
	mutation := newAppConfigMutation(c.config, OpDelete)
	return &AppConfigDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AppConfigClient) DeleteOne(_m *AppConfig) *AppConfigDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AppConfigClient) DeleteOneID(id int) *AppConfigDeleteOne {
	builder := c.Delete().Where(appconfig.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AppConfigDeleteOne{builder}
}

// Query returns a query builder for AppConfig.
func (c *AppConfigClient) Query() *AppConfigQuery {
	return &AppConfigQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAppConfig},
		inters: c.Interceptors(),
	}
}

// Get returns a AppConfig entity by its id.
func (c *AppConfigClient) Get(ctx context.Context, id int) (*AppConfig, error) {
	return c.Query().Where(appconfig.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AppConfigClient) GetX(ctx context.Context, id int) *AppConfig {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AppConfigClient) Hooks() []Hook {
	return c.hooks.AppConfig
}

// Interceptors returns the client interceptors.
func (c *AppConfigClient) Interceptors() []Interceptor {
	return c.inters.AppConfig
}

func (c *AppConfigClient) mutate(ctx context.Context, m *AppConfigMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AppConfigCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AppConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AppConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AppConfigDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AppConfig mutation op: %q", m.Op())
	}
}

// OutageClient is a client for the Outage schema.
type OutageClient struct {
	config
}

// NewOutageClient returns a client for the Outage from the given config.
func NewOutageClient(c config) *OutageClient {
	return &OutageClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `outage.Hooks(f(g(h())))`.
func (c *OutageClient) Use(hooks ...Hook) {
	c.hooks.Outage = append(c.hooks.Outage, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `outage.Intercept(f(g(h())))`.
func (c *OutageClient) Intercept(interceptors ...Interceptor) {
	c.inters.Outage = append(c.inters.Outage, interceptors...)
}

// Create returns a builder for creating a Outage entity.
func (c *OutageClient) Create() *OutageCreate {
	mutation := newOutageMutation(c.config, OpCreate)
	return &OutageCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Outage entities.
func (c *OutageClient) CreateBulk(builders ...*OutageCreate) *OutageCreateBulk {
	return &OutageCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OutageClient) MapCreateBulk(slice any, setFunc func(*OutageCreate, int)) *OutageCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OutageCreateBulk{err: fmt.Errorf("calling to OutageClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OutageCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OutageCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Outage.
func (c *OutageClient) Update() *OutageUpdate {
	mutation := newOutageMutation(c.config, OpUpdate)
	return &OutageUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OutageClient) UpdateOne(_m *Outage) *OutageUpdateOne {
	mutation := newOutageMutation(c.config, OpUpdateOne, withOutage(_m))
	return &OutageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OutageClient) UpdateOneID(id string) *OutageUpdateOne {
	mutation := newOutageMutation(c.config, OpUpdateOne, withOutageID(id))
	return &OutageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Outage.
func (c *OutageClient) Delete() *OutageDelete {
	mutation := newOutageMutation(c.config, OpDelete)
	return &OutageDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OutageClient) DeleteOne(_m *Outage) *OutageDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OutageClient) DeleteOneID(id string) *OutageDeleteOne {
	builder := c.Delete().Where(outage.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OutageDeleteOne{builder}
}

// Query returns a query builder for Outage.
func (c *OutageClient) Query() *OutageQuery {
	return &OutageQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOutage},
		inters: c.Interceptors(),
	}
}

// Get returns a Outage entity by its id.
func (c *OutageClient) Get(ctx context.Context, id string) (*Outage, error) {
	return c.Query().Where(outage.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OutageClient) GetX(ctx context.Context, id string) *Outage {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OutageClient) Hooks() []Hook {
	return c.hooks.Outage
}

// Interceptors returns the client interceptors.
func (c *OutageClient) Interceptors() []Interceptor {
	return c.inters.Outage
}

func (c *OutageClient) mutate(ctx context.Context, m *OutageMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OutageCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OutageUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OutageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OutageDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Outage mutation op: %q", m.Op())
	}
}

// SampleClient is a client for the Sample schema.
type SampleClient struct {
	config
}

// NewSampleClient returns a client for the Sample from the given config.
func NewSampleClient(c config) *SampleClient {
	return &SampleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sample.Hooks(f(g(h())))`.
func (c *SampleClient) Use(hooks ...Hook) {
	c.hooks.Sample = append(c.hooks.Sample, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sample.Intercept(f(g(h())))`.
func (c *SampleClient) Intercept(interceptors ...Interceptor) {
	c.inters.Sample = append(c.inters.Sample, interceptors...)
}

// Create returns a builder for creating a Sample entity.
func (c *SampleClient) Create() *SampleCreate {
	mutation := newSampleMutation(c.config, OpCreate)
	return &SampleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Sample entities.
func (c *SampleClient) CreateBulk(builders ...*SampleCreate) *SampleCreateBulk {
	return &SampleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SampleClient) MapCreateBulk(slice any, setFunc func(*SampleCreate, int)) *SampleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SampleCreateBulk{err: fmt.Errorf("calling to SampleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SampleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SampleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Sample.
func (c *SampleClient) Update() *SampleUpdate {
	mutation := newSampleMutation(c.config, OpUpdate)
	return &SampleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SampleClient) UpdateOne(_m *Sample) *SampleUpdateOne {
	mutation := newSampleMutation(c.config, OpUpdateOne, withSample(_m))
	return &SampleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SampleClient) UpdateOneID(id int) *SampleUpdateOne {
	mutation := newSampleMutation(c.config, OpUpdateOne, withSampleID(id))
	return &SampleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Sample.
func (c *SampleClient) Delete() *SampleDelete {
	mutation := newSampleMutation(c.config, OpDelete)
	return &SampleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SampleClient) DeleteOne(_m *Sample) *SampleDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SampleClient) DeleteOneID(id int) *SampleDeleteOne {
	builder := c.Delete().Where(sample.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SampleDeleteOne{builder}
}

// Query returns a query builder for Sample.
func (c *SampleClient) Query() *SampleQuery {
	return &SampleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSample},
		inters: c.Interceptors(),
	}
}

// Get returns a Sample entity by its id.
func (c *SampleClient) Get(ctx context.Context, id int) (*Sample, error) {
	return c.Query().Where(sample.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SampleClient) GetX(ctx context.Context, id int) *Sample {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SampleClient) Hooks() []Hook {
	return c.hooks.Sample
}

// Interceptors returns the client interceptors.
func (c *SampleClient) Interceptors() []Interceptor {
	return c.inters.Sample
}

func (c *SampleClient) mutate(ctx context.Context, m *SampleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SampleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SampleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SampleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SampleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Sample mutation op: %q", m.Op())
	}
}

// Sample1hClient is a client for the Sample1h schema.
type Sample1hClient struct {
	config
}

// NewSample1hClient returns a client for the Sample1h from the given config.
func NewSample1hClient(c config) *Sample1hClient {
	return &Sample1hClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sample1h.Hooks(f(g(h())))`.
func (c *Sample1hClient) Use(hooks ...Hook) {
	c.hooks.Sample1h = append(c.hooks.Sample1h, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sample1h.Intercept(f(g(h())))`.
func (c *Sample1hClient) Intercept(interceptors ...Interceptor) {
	c.inters.Sample1h = append(c.inters.Sample1h, interceptors...)
}

// Create returns a builder for creating a Sample1h entity.
func (c *Sample1hClient) Create() *Sample1hCreate {
	mutation := newSample1hMutation(c.config, OpCreate)
	return &Sample1hCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Sample1h entities.
func (c *Sample1hClient) CreateBulk(builders ...*Sample1hCreate) *Sample1hCreateBulk {
	return &Sample1hCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *Sample1hClient) MapCreateBulk(slice any, setFunc func(*Sample1hCreate, int)) *Sample1hCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &Sample1hCreateBulk{err: fmt.Errorf("calling to Sample1hClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*Sample1hCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &Sample1hCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Sample1h.
func (c *Sample1hClient) Update() *Sample1hUpdate {
	mutation := newSample1hMutation(c.config, OpUpdate)
	return &Sample1hUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *Sample1hClient) UpdateOne(_m *Sample1h) *Sample1hUpdateOne {
	mutation := newSample1hMutation(c.config, OpUpdateOne, withSample1h(_m))
	return &Sample1hUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *Sample1hClient) UpdateOneID(id int) *Sample1hUpdateOne {
	mutation := newSample1hMutation(c.config, OpUpdateOne, withSample1hID(id))
	return &Sample1hUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Sample1h.
func (c *Sample1hClient) Delete() *Sample1hDelete {
	mutation := newSample1hMutation(c.config, OpDelete)
	return &Sample1hDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *Sample1hClient) DeleteOne(_m *Sample1h) *Sample1hDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *Sample1hClient) DeleteOneID(id int) *Sample1hDeleteOne {
	builder := c.Delete().Where(sample1h.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &Sample1hDeleteOne{builder}
}

// Query returns a query builder for Sample1h.
func (c *Sample1hClient) Query() *Sample1hQuery {
	return &Sample1hQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSample1h},
		inters: c.Interceptors(),
	}
}

// Get returns a Sample1h entity by its id.
func (c *Sample1hClient) Get(ctx context.Context, id int) (*Sample1h, error) {
	return c.Query().Where(sample1h.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *Sample1hClient) GetX(ctx context.Context, id int) *Sample1h {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *Sample1hClient) Hooks() []Hook {
	return c.hooks.Sample1h
}

// Interceptors returns the client interceptors.
func (c *Sample1hClient) Interceptors() []Interceptor {
	return c.inters.Sample1h
}

func (c *Sample1hClient) mutate(ctx context.Context, m *Sample1hMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&Sample1hCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&Sample1hUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&Sample1hUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&Sample1hDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Sample1h mutation op: %q", m.Op())
	}
}

// Sample1minClient is a client for the Sample1min schema.
type Sample1minClient struct {
	config
}

// NewSample1minClient returns a client for the Sample1min from the given config.
func NewSample1minClient(c config) *Sample1minClient {
	return &Sample1minClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sample1min.Hooks(f(g(h())))`.
func (c *Sample1minClient) Use(hooks ...Hook) {
	c.hooks.Sample1min = append(c.hooks.Sample1min, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sample1min.Intercept(f(g(h())))`.
func (c *Sample1minClient) Intercept(interceptors ...Interceptor) {
	c.inters.Sample1min = append(c.inters.Sample1min, interceptors...)
}

// Create returns a builder for creating a Sample1min entity.
func (c *Sample1minClient) Create() *Sample1minCreate {
	mutation := newSample1minMutation(c.config, OpCreate)
	return &Sample1minCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Sample1min entities.
func (c *Sample1minClient) CreateBulk(builders ...*Sample1minCreate) *Sample1minCreateBulk {
	return &Sample1minCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *Sample1minClient) MapCreateBulk(slice any, setFunc func(*Sample1minCreate, int)) *Sample1minCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &Sample1minCreateBulk{err: fmt.Errorf("calling to Sample1minClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*Sample1minCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &Sample1minCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Sample1min.
func (c *Sample1minClient) Update() *Sample1minUpdate {
	mutation := newSample1minMutation(c.config, OpUpdate)
	return &Sample1minUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *Sample1minClient) UpdateOne(_m *Sample1min) *Sample1minUpdateOne {
	mutation := newSample1minMutation(c.config, OpUpdateOne, withSample1min(_m))
	return &Sample1minUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *Sample1minClient) UpdateOneID(id int) *Sample1minUpdateOne {
	mutation := newSample1minMutation(c.config, OpUpdateOne, withSample1minID(id))
	return &Sample1minUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Sample1min.
func (c *Sample1minClient) Delete() *Sample1minDelete {
	mutation := newSample1minMutation(c.config, OpDelete)
	return &Sample1minDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *Sample1minClient) DeleteOne(_m *Sample1min) *Sample1minDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *Sample1minClient) DeleteOneID(id int) *Sample1minDeleteOne {
	builder := c.Delete().Where(sample1min.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &Sample1minDeleteOne{builder}
}

// Query returns a query builder for Sample1min.
func (c *Sample1minClient) Query() *Sample1minQuery {
	return &Sample1minQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSample1min},
		inters: c.Interceptors(),
	}
}

// Get returns a Sample1min entity by its id.
func (c *Sample1minClient) Get(ctx context.Context, id int) (*Sample1min, error) {
	return c.Query().Where(sample1min.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *Sample1minClient) GetX(ctx context.Context, id int) *Sample1min {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *Sample1minClient) Hooks() []Hook {
	return c.hooks.Sample1min
}

// Interceptors returns the client interceptors.
func (c *Sample1minClient) Interceptors() []Interceptor {
	return c.inters.Sample1min
}

func (c *Sample1minClient) mutate(ctx context.Context, m *Sample1minMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&Sample1minCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&Sample1minUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&Sample1minUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&Sample1minDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Sample1min mutation op: %q", m.Op())
	}
}

// Sample5minClient is a client for the Sample5min schema.
type Sample5minClient struct {
	config
}

// NewSample5minClient returns a client for the Sample5min from the given config.
func NewSample5minClient(c config) *Sample5minClient {
	return &Sample5minClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sample5min.Hooks(f(g(h())))`.
func (c *Sample5minClient) Use(hooks ...Hook) {
	c.hooks.Sample5min = append(c.hooks.Sample5min, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sample5min.Intercept(f(g(h())))`.
func (c *Sample5minClient) Intercept(interceptors ...Interceptor) {
	c.inters.Sample5min = append(c.inters.Sample5min, interceptors...)
}

// Create returns a builder for creating a Sample5min entity.
func (c *Sample5minClient) Create() *Sample5minCreate {
	mutation := newSample5minMutation(c.config, OpCreate)
	return &Sample5minCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Sample5min entities.
func (c *Sample5minClient) CreateBulk(builders ...*Sample5minCreate) *Sample5minCreateBulk {
	return &Sample5minCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *Sample5minClient) MapCreateBulk(slice any, setFunc func(*Sample5minCreate, int)) *Sample5minCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &Sample5minCreateBulk{err: fmt.Errorf("calling to Sample5minClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*Sample5minCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &Sample5minCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Sample5min.
func (c *Sample5minClient) Update() *Sample5minUpdate {
	mutation := newSample5minMutation(c.config, OpUpdate)
	return &Sample5minUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *Sample5minClient) UpdateOne(_m *Sample5min) *Sample5minUpdateOne {
	mutation := newSample5minMutation(c.config, OpUpdateOne, withSample5min(_m))
	return &Sample5minUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *Sample5minClient) UpdateOneID(id int) *Sample5minUpdateOne {
	mutation := newSample5minMutation(c.config, OpUpdateOne, withSample5minID(id))
	return &Sample5minUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Sample5min.
func (c *Sample5minClient) Delete() *Sample5minDelete {
	mutation := newSample5minMutation(c.config, OpDelete)
	return &Sample5minDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *Sample5minClient) DeleteOne(_m *Sample5min) *Sample5minDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *Sample5minClient) DeleteOneID(id int) *Sample5minDeleteOne {
	builder := c.Delete().Where(sample5min.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &Sample5minDeleteOne{builder}
}

// Query returns a query builder for Sample5min.
func (c *Sample5minClient) Query() *Sample5minQuery {
	return &Sample5minQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSample5min},
		inters: c.Interceptors(),
	}
}

// Get returns a Sample5min entity by its id.
func (c *Sample5minClient) Get(ctx context.Context, id int) (*Sample5min, error) {
	return c.Query().Where(sample5min.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *Sample5minClient) GetX(ctx context.Context, id int) *Sample5min {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *Sample5minClient) Hooks() []Hook {
	return c.hooks.Sample5min
}

// Interceptors returns the client interceptors.
func (c *Sample5minClient) Interceptors() []Interceptor {
	return c.inters.Sample5min
}

func (c *Sample5minClient) mutate(ctx context.Context, m *Sample5minMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&Sample5minCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&Sample5minUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&Sample5minUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&Sample5minDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Sample5min mutation op: %q", m.Op())
	}
}

// TargetClient is a client for the Target schema.
type TargetClient struct {
	config
}

// NewTargetClient returns a client for the Target from the given config.
func NewTargetClient(c config) *TargetClient {
	return &TargetClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `target.Hooks(f(g(h())))`.
func (c *TargetClient) Use(hooks ...Hook) {
	c.hooks.Target = append(c.hooks.Target, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `target.Intercept(f(g(h())))`.
func (c *TargetClient) Intercept(interceptors ...Interceptor) {
	c.inters.Target = append(c.inters.Target, interceptors...)
}

// Create returns a builder for creating a Target entity.
func (c *TargetClient) Create() *TargetCreate {
	mutation := newTargetMutation(c.config, OpCreate)
	return &TargetCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Target entities.
func (c *TargetClient) CreateBulk(builders ...*TargetCreate) *TargetCreateBulk {
	return &TargetCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TargetClient) MapCreateBulk(slice any, setFunc func(*TargetCreate, int)) *TargetCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TargetCreateBulk{err: fmt.Errorf("calling to TargetClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TargetCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TargetCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Target.
func (c *TargetClient) Update() *TargetUpdate {
	mutation := newTargetMutation(c.config, OpUpdate)
	return &TargetUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TargetClient) UpdateOne(_m *Target) *TargetUpdateOne {
	mutation := newTargetMutation(c.config, OpUpdateOne, withTarget(_m))
	return &TargetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TargetClient) UpdateOneID(id string) *TargetUpdateOne {
	mutation := newTargetMutation(c.config, OpUpdateOne, withTargetID(id))
	return &TargetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Target.
func (c *TargetClient) Delete() *TargetDelete {
	mutation := newTargetMutation(c.config, OpDelete)
	return &TargetDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TargetClient) DeleteOne(_m *Target) *TargetDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TargetClient) DeleteOneID(id string) *TargetDeleteOne {
	builder := c.Delete().Where(target.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TargetDeleteOne{builder}
}

// Query returns a query builder for Target.
func (c *TargetClient) Query() *TargetQuery {
	return &TargetQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTarget},
		inters: c.Interceptors(),
	}
}

// Get returns a Target entity by its id.
func (c *TargetClient) Get(ctx context.Context, id string) (*Target, error) {
	return c.Query().Where(target.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TargetClient) GetX(ctx context.Context, id string) *Target {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TargetClient) Hooks() []Hook {
	return c.hooks.Target
}

// Interceptors returns the client interceptors.
func (c *TargetClient) Interceptors() []Interceptor {
	return c.inters.Target
}

func (c *TargetClient) mutate(ctx context.Context, m *TargetMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TargetCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TargetUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TargetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TargetDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Target mutation op: %q", m.Op())
	}
}

// WifiSampleClient is a client for the WifiSample schema.
type WifiSampleClient struct {
	config
}

// NewWifiSampleClient returns a client for the WifiSample from the given config.
func NewWifiSampleClient(c config) *WifiSampleClient {
	return &WifiSampleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `wifisample.Hooks(f(g(h())))`.
func (c *WifiSampleClient) Use(hooks ...Hook) {
	c.hooks.WifiSample = append(c.hooks.WifiSample, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `wifisample.Intercept(f(g(h())))`.
func (c *WifiSampleClient) Intercept(interceptors ...Interceptor) {
	c.inters.WifiSample = append(c.inters.WifiSample, interceptors...)
}

// Create returns a builder for creating a WifiSample entity.
func (c *WifiSampleClient) Create() *WifiSampleCreate {
	mutation := newWifiSampleMutation(c.config, OpCreate)
	return &WifiSampleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of WifiSample entities.
func (c *WifiSampleClient) CreateBulk(builders ...*WifiSampleCreate) *WifiSampleCreateBulk {
	return &WifiSampleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WifiSampleClient) MapCreateBulk(slice any, setFunc func(*WifiSampleCreate, int)) *WifiSampleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WifiSampleCreateBulk{err: fmt.Errorf("calling to WifiSampleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WifiSampleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WifiSampleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for WifiSample.
func (c *WifiSampleClient) Update() *WifiSampleUpdate {
	mutation := newWifiSampleMutation(c.config, OpUpdate)
	return &WifiSampleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WifiSampleClient) UpdateOne(_m *WifiSample) *WifiSampleUpdateOne {
	mutation := newWifiSampleMutation(c.config, OpUpdateOne, withWifiSample(_m))
	return &WifiSampleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WifiSampleClient) UpdateOneID(id int) *WifiSampleUpdateOne {
	mutation := newWifiSampleMutation(c.config, OpUpdateOne, withWifiSampleID(id))
	return &WifiSampleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for WifiSample.
func (c *WifiSampleClient) Delete() *WifiSampleDelete {
	mutation := newWifiSampleMutation(c.config, OpDelete)
	return &WifiSampleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WifiSampleClient) DeleteOne(_m *WifiSample) *WifiSampleDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WifiSampleClient) DeleteOneID(id int) *WifiSampleDeleteOne {
	builder := c.Delete().Where(wifisample.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WifiSampleDeleteOne{builder}
}

// Query returns a query builder for WifiSample.
func (c *WifiSampleClient) Query() *WifiSampleQuery {
	return &WifiSampleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWifiSample},
		inters: c.Interceptors(),
	}
}

// Get returns a WifiSample entity by its id.
func (c *WifiSampleClient) Get(ctx context.Context, id int) (*WifiSample, error) {
	return c.Query().Where(wifisample.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WifiSampleClient) GetX(ctx context.Context, id int) *WifiSample {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *WifiSampleClient) Hooks() []Hook {
	return c.hooks.WifiSample
}

// Interceptors returns the client interceptors.
func (c *WifiSampleClient) Interceptors() []Interceptor {
	return c.inters.WifiSample
}

func (c *WifiSampleClient) mutate(ctx context.Context, m *WifiSampleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WifiSampleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WifiSampleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WifiSampleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WifiSampleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown WifiSample mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AppConfig, Outage, Sample, Sample1h, Sample1min, Sample5min, Target,
		WifiSample []ent.Hook
	}
	inters struct {
		AppConfig, Outage, Sample, Sample1h, Sample1min, Sample5min, Target,
		WifiSample []ent.Interceptor
	}
)
