// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sid-technologies/vigil/db/ent/outage"
	"github.com/sid-technologies/vigil/db/ent/predicate"
)

// OutageUpdate is the builder for updating Outage entities.
type OutageUpdate struct {
	config
	hooks    []Hook
	mutation *OutageMutation
}

// Where appends a list predicates to the OutageUpdate builder.
func (_u *OutageUpdate) Where(ps ...predicate.Outage) *OutageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetScope sets the "scope" field.
func (_u *OutageUpdate) SetScope(v string) *OutageUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *OutageUpdate) SetNillableScope(v *string) *OutageUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetStartTsUnixMs sets the "start_ts_unix_ms" field.
func (_u *OutageUpdate) SetStartTsUnixMs(v int64) *OutageUpdate {
	_u.mutation.ResetStartTsUnixMs()
	_u.mutation.SetStartTsUnixMs(v)
	return _u
}

// SetNillableStartTsUnixMs sets the "start_ts_unix_ms" field if the given value is not nil.
func (_u *OutageUpdate) SetNillableStartTsUnixMs(v *int64) *OutageUpdate {
	if v != nil {
		_u.SetStartTsUnixMs(*v)
	}
	return _u
}

// AddStartTsUnixMs adds value to the "start_ts_unix_ms" field.
func (_u *OutageUpdate) AddStartTsUnixMs(v int64) *OutageUpdate {
	_u.mutation.AddStartTsUnixMs(v)
	return _u
}

// SetEndTsUnixMs sets the "end_ts_unix_ms" field.
func (_u *OutageUpdate) SetEndTsUnixMs(v int64) *OutageUpdate {
	_u.mutation.ResetEndTsUnixMs()
	_u.mutation.SetEndTsUnixMs(v)
	return _u
}

// SetNillableEndTsUnixMs sets the "end_ts_unix_ms" field if the given value is not nil.
func (_u *OutageUpdate) SetNillableEndTsUnixMs(v *int64) *OutageUpdate {
	if v != nil {
		_u.SetEndTsUnixMs(*v)
	}
	return _u
}

// AddEndTsUnixMs adds value to the "end_ts_unix_ms" field.
func (_u *OutageUpdate) AddEndTsUnixMs(v int64) *OutageUpdate {
	_u.mutation.AddEndTsUnixMs(v)
	return _u
}

// ClearEndTsUnixMs clears the value of the "end_ts_unix_ms" field.
func (_u *OutageUpdate) ClearEndTsUnixMs() *OutageUpdate {
	_u.mutation.ClearEndTsUnixMs()
	return _u
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (_u *OutageUpdate) SetConsecutiveFailures(v int) *OutageUpdate {
	_u.mutation.ResetConsecutiveFailures()
	_u.mutation.SetConsecutiveFailures(v)
	return _u
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (_u *OutageUpdate) SetNillableConsecutiveFailures(v *int) *OutageUpdate {
	if v != nil {
		_u.SetConsecutiveFailures(*v)
	}
	return _u
}

// AddConsecutiveFailures adds value to the "consecutive_failures" field.
func (_u *OutageUpdate) AddConsecutiveFailures(v int) *OutageUpdate {
	_u.mutation.AddConsecutiveFailures(v)
	return _u
}

// SetErrors sets the "errors" field.
func (_u *OutageUpdate) SetErrors(v map[string]int) *OutageUpdate {
	_u.mutation.SetErrors(v)
	return _u
}

// ClearErrors clears the value of the "errors" field.
func (_u *OutageUpdate) ClearErrors() *OutageUpdate {
	_u.mutation.ClearErrors()
	return _u
}

// Mutation returns the OutageMutation object of the builder.
func (_u *OutageUpdate) Mutation() *OutageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OutageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OutageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OutageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OutageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OutageUpdate) check() error {
	if v, ok := _u.mutation.Scope(); ok {
		if err := outage.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "Outage.scope": %w`, err)}
		}
	}
	return nil
}

func (_u *OutageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(outage.Table, outage.Columns, sqlgraph.NewFieldSpec(outage.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(outage.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartTsUnixMs(); ok {
		_spec.SetField(outage.FieldStartTsUnixMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStartTsUnixMs(); ok {
		_spec.AddField(outage.FieldStartTsUnixMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.EndTsUnixMs(); ok {
		_spec.SetField(outage.FieldEndTsUnixMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEndTsUnixMs(); ok {
		_spec.AddField(outage.FieldEndTsUnixMs, field.TypeInt64, value)
	}
	if _u.mutation.EndTsUnixMsCleared() {
		_spec.ClearField(outage.FieldEndTsUnixMs, field.TypeInt64)
	}
	if value, ok := _u.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(outage.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveFailures(); ok {
		_spec.AddField(outage.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Errors(); ok {
		_spec.SetField(outage.FieldErrors, field.TypeJSON, value)
	}
	if _u.mutation.ErrorsCleared() {
		_spec.ClearField(outage.FieldErrors, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OutageUpdateOne is the builder for updating a single Outage entity.
type OutageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OutageMutation
}

// SetScope sets the "scope" field.
func (_u *OutageUpdateOne) SetScope(v string) *OutageUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *OutageUpdateOne) SetNillableScope(v *string) *OutageUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetStartTsUnixMs sets the "start_ts_unix_ms" field.
func (_u *OutageUpdateOne) SetStartTsUnixMs(v int64) *OutageUpdateOne {
	_u.mutation.ResetStartTsUnixMs()
	_u.mutation.SetStartTsUnixMs(v)
	return _u
}

// SetNillableStartTsUnixMs sets the "start_ts_unix_ms" field if the given value is not nil.
func (_u *OutageUpdateOne) SetNillableStartTsUnixMs(v *int64) *OutageUpdateOne {
	if v != nil {
		_u.SetStartTsUnixMs(*v)
	}
	return _u
}

// AddStartTsUnixMs adds value to the "start_ts_unix_ms" field.
func (_u *OutageUpdateOne) AddStartTsUnixMs(v int64) *OutageUpdateOne {
	_u.mutation.AddStartTsUnixMs(v)
	return _u
}

// SetEndTsUnixMs sets the "end_ts_unix_ms" field.
func (_u *OutageUpdateOne) SetEndTsUnixMs(v int64) *OutageUpdateOne {
	_u.mutation.ResetEndTsUnixMs()
	_u.mutation.SetEndTsUnixMs(v)
	return _u
}

// SetNillableEndTsUnixMs sets the "end_ts_unix_ms" field if the given value is not nil.
func (_u *OutageUpdateOne) SetNillableEndTsUnixMs(v *int64) *OutageUpdateOne {
	if v != nil {
		_u.SetEndTsUnixMs(*v)
	}
	return _u
}

// AddEndTsUnixMs adds value to the "end_ts_unix_ms" field.
func (_u *OutageUpdateOne) AddEndTsUnixMs(v int64) *OutageUpdateOne {
	_u.mutation.AddEndTsUnixMs(v)
	return _u
}

// ClearEndTsUnixMs clears the value of the "end_ts_unix_ms" field.
func (_u *OutageUpdateOne) ClearEndTsUnixMs() *OutageUpdateOne {
	_u.mutation.ClearEndTsUnixMs()
	return _u
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (_u *OutageUpdateOne) SetConsecutiveFailures(v int) *OutageUpdateOne {
	_u.mutation.ResetConsecutiveFailures()
	_u.mutation.SetConsecutiveFailures(v)
	return _u
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (_u *OutageUpdateOne) SetNillableConsecutiveFailures(v *int) *OutageUpdateOne {
	if v != nil {
		_u.SetConsecutiveFailures(*v)
	}
	return _u
}

// AddConsecutiveFailures adds value to the "consecutive_failures" field.
func (_u *OutageUpdateOne) AddConsecutiveFailures(v int) *OutageUpdateOne {
	_u.mutation.AddConsecutiveFailures(v)
	return _u
}

// SetErrors sets the "errors" field.
func (_u *OutageUpdateOne) SetErrors(v map[string]int) *OutageUpdateOne {
	_u.mutation.SetErrors(v)
	return _u
}

// ClearErrors clears the value of the "errors" field.
func (_u *OutageUpdateOne) ClearErrors() *OutageUpdateOne {
	_u.mutation.ClearErrors()
	return _u
}

// Mutation returns the OutageMutation object of the builder.
func (_u *OutageUpdateOne) Mutation() *OutageMutation {
	return _u.mutation
}

// Where appends a list predicates to the OutageUpdate builder.
func (_u *OutageUpdateOne) Where(ps ...predicate.Outage) *OutageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OutageUpdateOne) Select(field string, fields ...string) *OutageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Outage entity.
func (_u *OutageUpdateOne) Save(ctx context.Context) (*Outage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OutageUpdateOne) SaveX(ctx context.Context) *Outage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OutageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OutageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OutageUpdateOne) check() error {
	if v, ok := _u.mutation.Scope(); ok {
		if err := outage.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "Outage.scope": %w`, err)}
		}
	}
	return nil
}

func (_u *OutageUpdateOne) sqlSave(ctx context.Context) (_node *Outage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(outage.Table, outage.Columns, sqlgraph.NewFieldSpec(outage.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Outage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, outage.FieldID)
		for _, f := range fields {
			if !outage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != outage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(outage.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartTsUnixMs(); ok {
		_spec.SetField(outage.FieldStartTsUnixMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStartTsUnixMs(); ok {
		_spec.AddField(outage.FieldStartTsUnixMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.EndTsUnixMs(); ok {
		_spec.SetField(outage.FieldEndTsUnixMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEndTsUnixMs(); ok {
		_spec.AddField(outage.FieldEndTsUnixMs, field.TypeInt64, value)
	}
	if _u.mutation.EndTsUnixMsCleared() {
		_spec.ClearField(outage.FieldEndTsUnixMs, field.TypeInt64)
	}
	if value, ok := _u.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(outage.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveFailures(); ok {
		_spec.AddField(outage.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Errors(); ok {
		_spec.SetField(outage.FieldErrors, field.TypeJSON, value)
	}
	if _u.mutation.ErrorsCleared() {
		_spec.ClearField(outage.FieldErrors, field.TypeJSON)
	}
	_node = &Outage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
