// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sid-technologies/vigil/db/ent/outage"
)

// OutageCreate is the builder for creating a Outage entity.
type OutageCreate struct {
	config
	mutation *OutageMutation
	hooks    []Hook
}

// SetScope sets the "scope" field.
func (_c *OutageCreate) SetScope(v string) *OutageCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetStartTsUnixMs sets the "start_ts_unix_ms" field.
func (_c *OutageCreate) SetStartTsUnixMs(v int64) *OutageCreate {
	_c.mutation.SetStartTsUnixMs(v)
	return _c
}

// SetEndTsUnixMs sets the "end_ts_unix_ms" field.
func (_c *OutageCreate) SetEndTsUnixMs(v int64) *OutageCreate {
	_c.mutation.SetEndTsUnixMs(v)
	return _c
}

// SetNillableEndTsUnixMs sets the "end_ts_unix_ms" field if the given value is not nil.
func (_c *OutageCreate) SetNillableEndTsUnixMs(v *int64) *OutageCreate {
	if v != nil {
		_c.SetEndTsUnixMs(*v)
	}
	return _c
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (_c *OutageCreate) SetConsecutiveFailures(v int) *OutageCreate {
	_c.mutation.SetConsecutiveFailures(v)
	return _c
}

// SetErrors sets the "errors" field.
func (_c *OutageCreate) SetErrors(v map[string]int) *OutageCreate {
	_c.mutation.SetErrors(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OutageCreate) SetCreatedAt(v time.Time) *OutageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OutageCreate) SetNillableCreatedAt(v *time.Time) *OutageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OutageCreate) SetID(v string) *OutageCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the OutageMutation object of the builder.
func (_c *OutageCreate) Mutation() *OutageMutation {
	return _c.mutation
}

// Save creates the Outage in the database.
func (_c *OutageCreate) Save(ctx context.Context) (*Outage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OutageCreate) SaveX(ctx context.Context) *Outage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OutageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OutageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OutageCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := outage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OutageCreate) check() error {
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "Outage.scope"`)}
	}
	if v, ok := _c.mutation.Scope(); ok {
		if err := outage.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "Outage.scope": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartTsUnixMs(); !ok {
		return &ValidationError{Name: "start_ts_unix_ms", err: errors.New(`ent: missing required field "Outage.start_ts_unix_ms"`)}
	}
	if _, ok := _c.mutation.ConsecutiveFailures(); !ok {
		return &ValidationError{Name: "consecutive_failures", err: errors.New(`ent: missing required field "Outage.consecutive_failures"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Outage.created_at"`)}
	}
	return nil
}

func (_c *OutageCreate) sqlSave(ctx context.Context) (*Outage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Outage.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OutageCreate) createSpec() (*Outage, *sqlgraph.CreateSpec) {
	var (
		_node = &Outage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(outage.Table, sqlgraph.NewFieldSpec(outage.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(outage.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.StartTsUnixMs(); ok {
		_spec.SetField(outage.FieldStartTsUnixMs, field.TypeInt64, value)
		_node.StartTsUnixMs = value
	}
	if value, ok := _c.mutation.EndTsUnixMs(); ok {
		_spec.SetField(outage.FieldEndTsUnixMs, field.TypeInt64, value)
		_node.EndTsUnixMs = &value
	}
	if value, ok := _c.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(outage.FieldConsecutiveFailures, field.TypeInt, value)
		_node.ConsecutiveFailures = value
	}
	if value, ok := _c.mutation.Errors(); ok {
		_spec.SetField(outage.FieldErrors, field.TypeJSON, value)
		_node.Errors = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(outage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OutageCreateBulk is the builder for creating many Outage entities in bulk.
type OutageCreateBulk struct {
	config
	err      error
	builders []*OutageCreate
}

// Save creates the Outage entities in the database.
func (_c *OutageCreateBulk) Save(ctx context.Context) ([]*Outage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Outage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OutageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OutageCreateBulk) SaveX(ctx context.Context) []*Outage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OutageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OutageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
