// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/sid-technologies/vigil/db/ent/outage"
)

// Outage is the model entity for the Outage schema.
type Outage struct {
	config `json:"-"`
	// ID of the ent.
	// UUID set at creation
	ID string `json:"id,omitempty"`
	// 'network' or 'target:<label>'
	Scope string `json:"scope,omitempty"`
	// StartTsUnixMs holds the value of the "start_ts_unix_ms" field.
	StartTsUnixMs int64 `json:"start_ts_unix_ms,omitempty"`
	// Null while ongoing
	EndTsUnixMs *int64 `json:"end_ts_unix_ms,omitempty"`
	// ConsecutiveFailures holds the value of the "consecutive_failures" field.
	ConsecutiveFailures int `json:"consecutive_failures,omitempty"`
	// Error code → count across the failure run
	Errors map[string]int `json:"errors,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Outage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case outage.FieldErrors:
			values[i] = new([]byte)
		case outage.FieldStartTsUnixMs, outage.FieldEndTsUnixMs, outage.FieldConsecutiveFailures:
			values[i] = new(sql.NullInt64)
		case outage.FieldID, outage.FieldScope:
			values[i] = new(sql.NullString)
		case outage.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Outage fields.
func (_m *Outage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case outage.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case outage.FieldScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope", values[i])
			} else if value.Valid {
				_m.Scope = value.String
			}
		case outage.FieldStartTsUnixMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field start_ts_unix_ms", values[i])
			} else if value.Valid {
				_m.StartTsUnixMs = value.Int64
			}
		case outage.FieldEndTsUnixMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field end_ts_unix_ms", values[i])
			} else if value.Valid {
				_m.EndTsUnixMs = new(int64)
				*_m.EndTsUnixMs = value.Int64
			}
		case outage.FieldConsecutiveFailures:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field consecutive_failures", values[i])
			} else if value.Valid {
				_m.ConsecutiveFailures = int(value.Int64)
			}
		case outage.FieldErrors:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field errors", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Errors); err != nil {
					return fmt.Errorf("unmarshal field errors: %w", err)
				}
			}
		case outage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Outage.
// This includes values selected through modifiers, order, etc.
func (_m *Outage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Outage.
// Note that you need to call Outage.Unwrap() before calling this method if this Outage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Outage) Update() *OutageUpdateOne {
	return NewOutageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Outage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Outage) Unwrap() *Outage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Outage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Outage) String() string {
	var builder strings.Builder
	builder.WriteString("Outage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("scope=")
	builder.WriteString(_m.Scope)
	builder.WriteString(", ")
	builder.WriteString("start_ts_unix_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.StartTsUnixMs))
	builder.WriteString(", ")
	if v := _m.EndTsUnixMs; v != nil {
		builder.WriteString("end_ts_unix_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("consecutive_failures=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConsecutiveFailures))
	builder.WriteString(", ")
	builder.WriteString("errors=")
	builder.WriteString(fmt.Sprintf("%v", _m.Errors))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Outages is a parsable slice of Outage.
type Outages []*Outage
