// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/sid-technologies/vigil/db/ent/appconfig"
	"github.com/sid-technologies/vigil/db/ent/outage"
	"github.com/sid-technologies/vigil/db/ent/sample"
	"github.com/sid-technologies/vigil/db/ent/sample1h"
	"github.com/sid-technologies/vigil/db/ent/sample1min"
	"github.com/sid-technologies/vigil/db/ent/sample5min"
	"github.com/sid-technologies/vigil/db/ent/schema"
	"github.com/sid-technologies/vigil/db/ent/target"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appconfigFields := schema.AppConfig{}.Fields()
	_ = appconfigFields
	// appconfigDescPingIntervalSec is the schema descriptor for ping_interval_sec field.
	appconfigDescPingIntervalSec := appconfigFields[1].Descriptor()
	// appconfig.DefaultPingIntervalSec holds the default value on creation for the ping_interval_sec field.
	appconfig.DefaultPingIntervalSec = appconfigDescPingIntervalSec.Default.(float64)
	// appconfigDescFlushIntervalSec is the schema descriptor for flush_interval_sec field.
	appconfigDescFlushIntervalSec := appconfigFields[2].Descriptor()
	// appconfig.DefaultFlushIntervalSec holds the default value on creation for the flush_interval_sec field.
	appconfig.DefaultFlushIntervalSec = appconfigDescFlushIntervalSec.Default.(int)
	// appconfigDescPingTimeoutMs is the schema descriptor for ping_timeout_ms field.
	appconfigDescPingTimeoutMs := appconfigFields[3].Descriptor()
	// appconfig.DefaultPingTimeoutMs holds the default value on creation for the ping_timeout_ms field.
	appconfig.DefaultPingTimeoutMs = appconfigDescPingTimeoutMs.Default.(int)
	// appconfigDescRetentionRawDays is the schema descriptor for retention_raw_days field.
	appconfigDescRetentionRawDays := appconfigFields[4].Descriptor()
	// appconfig.DefaultRetentionRawDays holds the default value on creation for the retention_raw_days field.
	appconfig.DefaultRetentionRawDays = appconfigDescRetentionRawDays.Default.(int)
	// appconfigDescRetention1minDays is the schema descriptor for retention_1min_days field.
	appconfigDescRetention1minDays := appconfigFields[5].Descriptor()
	// appconfig.DefaultRetention1minDays holds the default value on creation for the retention_1min_days field.
	appconfig.DefaultRetention1minDays = appconfigDescRetention1minDays.Default.(int)
	// appconfigDescRetention5minDays is the schema descriptor for retention_5min_days field.
	appconfigDescRetention5minDays := appconfigFields[6].Descriptor()
	// appconfig.DefaultRetention5minDays holds the default value on creation for the retention_5min_days field.
	appconfig.DefaultRetention5minDays = appconfigDescRetention5minDays.Default.(int)
	// appconfigDescWifiSampleEnabled is the schema descriptor for wifi_sample_enabled field.
	appconfigDescWifiSampleEnabled := appconfigFields[7].Descriptor()
	// appconfig.DefaultWifiSampleEnabled holds the default value on creation for the wifi_sample_enabled field.
	appconfig.DefaultWifiSampleEnabled = appconfigDescWifiSampleEnabled.Default.(bool)
	outageFields := schema.Outage{}.Fields()
	_ = outageFields
	// outageDescScope is the schema descriptor for scope field.
	outageDescScope := outageFields[1].Descriptor()
	// outage.ScopeValidator is a validator for the "scope" field. It is called by the builders before save.
	outage.ScopeValidator = outageDescScope.Validators[0].(func(string) error)
	// outageDescCreatedAt is the schema descriptor for created_at field.
	outageDescCreatedAt := outageFields[6].Descriptor()
	// outage.DefaultCreatedAt holds the default value on creation for the created_at field.
	outage.DefaultCreatedAt = outageDescCreatedAt.Default.(func() time.Time)
	sampleFields := schema.Sample{}.Fields()
	_ = sampleFields
	// sampleDescTargetLabel is the schema descriptor for target_label field.
	sampleDescTargetLabel := sampleFields[1].Descriptor()
	// sample.TargetLabelValidator is a validator for the "target_label" field. It is called by the builders before save.
	sample.TargetLabelValidator = sampleDescTargetLabel.Validators[0].(func(string) error)
	sample1hFields := schema.Sample1h{}.Fields()
	_ = sample1hFields
	// sample1hDescTargetLabel is the schema descriptor for target_label field.
	sample1hDescTargetLabel := sample1hFields[1].Descriptor()
	// sample1h.TargetLabelValidator is a validator for the "target_label" field. It is called by the builders before save.
	sample1h.TargetLabelValidator = sample1hDescTargetLabel.Validators[0].(func(string) error)
	sample1minFields := schema.Sample1min{}.Fields()
	_ = sample1minFields
	// sample1minDescTargetLabel is the schema descriptor for target_label field.
	sample1minDescTargetLabel := sample1minFields[1].Descriptor()
	// sample1min.TargetLabelValidator is a validator for the "target_label" field. It is called by the builders before save.
	sample1min.TargetLabelValidator = sample1minDescTargetLabel.Validators[0].(func(string) error)
	sample5minFields := schema.Sample5min{}.Fields()
	_ = sample5minFields
	// sample5minDescTargetLabel is the schema descriptor for target_label field.
	sample5minDescTargetLabel := sample5minFields[1].Descriptor()
	// sample5min.TargetLabelValidator is a validator for the "target_label" field. It is called by the builders before save.
	sample5min.TargetLabelValidator = sample5minDescTargetLabel.Validators[0].(func(string) error)
	targetFields := schema.Target{}.Fields()
	_ = targetFields
	// targetDescLabel is the schema descriptor for label field.
	targetDescLabel := targetFields[1].Descriptor()
	// target.LabelValidator is a validator for the "label" field. It is called by the builders before save.
	target.LabelValidator = func() func(string) error {
		validators := targetDescLabel.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(label string) error {
			for _, fn := range fns {
				if err := fn(label); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// targetDescHost is the schema descriptor for host field.
	targetDescHost := targetFields[3].Descriptor()
	// target.HostValidator is a validator for the "host" field. It is called by the builders before save.
	target.HostValidator = targetDescHost.Validators[0].(func(string) error)
	// targetDescEnabled is the schema descriptor for enabled field.
	targetDescEnabled := targetFields[5].Descriptor()
	// target.DefaultEnabled holds the default value on creation for the enabled field.
	target.DefaultEnabled = targetDescEnabled.Default.(bool)
	// targetDescIsBuiltin is the schema descriptor for is_builtin field.
	targetDescIsBuiltin := targetFields[6].Descriptor()
	// target.DefaultIsBuiltin holds the default value on creation for the is_builtin field.
	target.DefaultIsBuiltin = targetDescIsBuiltin.Default.(bool)
	// targetDescCreatedAt is the schema descriptor for created_at field.
	targetDescCreatedAt := targetFields[7].Descriptor()
	// target.DefaultCreatedAt holds the default value on creation for the created_at field.
	target.DefaultCreatedAt = targetDescCreatedAt.Default.(func() time.Time)
	// targetDescUpdatedAt is the schema descriptor for updated_at field.
	targetDescUpdatedAt := targetFields[8].Descriptor()
	// target.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	target.DefaultUpdatedAt = targetDescUpdatedAt.Default.(func() time.Time)
	// target.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	target.UpdateDefaultUpdatedAt = targetDescUpdatedAt.UpdateDefault.(func() time.Time)
}
