// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sid-technologies/vigil/db/ent/predicate"
	"github.com/sid-technologies/vigil/db/ent/sample1h"
)

// Sample1hUpdate is the builder for updating Sample1h entities.
type Sample1hUpdate struct {
	config
	hooks    []Hook
	mutation *Sample1hMutation
}

// Where appends a list predicates to the Sample1hUpdate builder.
func (_u *Sample1hUpdate) Where(ps ...predicate.Sample1h) *Sample1hUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBucketStartUnixMs sets the "bucket_start_unix_ms" field.
func (_u *Sample1hUpdate) SetBucketStartUnixMs(v int64) *Sample1hUpdate {
	_u.mutation.ResetBucketStartUnixMs()
	_u.mutation.SetBucketStartUnixMs(v)
	return _u
}

// SetNillableBucketStartUnixMs sets the "bucket_start_unix_ms" field if the given value is not nil.
func (_u *Sample1hUpdate) SetNillableBucketStartUnixMs(v *int64) *Sample1hUpdate {
	if v != nil {
		_u.SetBucketStartUnixMs(*v)
	}
	return _u
}

// AddBucketStartUnixMs adds value to the "bucket_start_unix_ms" field.
func (_u *Sample1hUpdate) AddBucketStartUnixMs(v int64) *Sample1hUpdate {
	_u.mutation.AddBucketStartUnixMs(v)
	return _u
}

// SetTargetLabel sets the "target_label" field.
func (_u *Sample1hUpdate) SetTargetLabel(v string) *Sample1hUpdate {
	_u.mutation.SetTargetLabel(v)
	return _u
}

// SetNillableTargetLabel sets the "target_label" field if the given value is not nil.
func (_u *Sample1hUpdate) SetNillableTargetLabel(v *string) *Sample1hUpdate {
	if v != nil {
		_u.SetTargetLabel(*v)
	}
	return _u
}

// SetCount sets the "count" field.
func (_u *Sample1hUpdate) SetCount(v int) *Sample1hUpdate {
	_u.mutation.ResetCount()
	_u.mutation.SetCount(v)
	return _u
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (_u *Sample1hUpdate) SetNillableCount(v *int) *Sample1hUpdate {
	if v != nil {
		_u.SetCount(*v)
	}
	return _u
}

// AddCount adds value to the "count" field.
func (_u *Sample1hUpdate) AddCount(v int) *Sample1hUpdate {
	_u.mutation.AddCount(v)
	return _u
}

// SetSuccessCount sets the "success_count" field.
func (_u *Sample1hUpdate) SetSuccessCount(v int) *Sample1hUpdate {
	_u.mutation.ResetSuccessCount()
	_u.mutation.SetSuccessCount(v)
	return _u
}

// SetNillableSuccessCount sets the "success_count" field if the given value is not nil.
func (_u *Sample1hUpdate) SetNillableSuccessCount(v *int) *Sample1hUpdate {
	if v != nil {
		_u.SetSuccessCount(*v)
	}
	return _u
}

// AddSuccessCount adds value to the "success_count" field.
func (_u *Sample1hUpdate) AddSuccessCount(v int) *Sample1hUpdate {
	_u.mutation.AddSuccessCount(v)
	return _u
}

// SetFailCount sets the "fail_count" field.
func (_u *Sample1hUpdate) SetFailCount(v int) *Sample1hUpdate {
	_u.mutation.ResetFailCount()
	_u.mutation.SetFailCount(v)
	return _u
}

// SetNillableFailCount sets the "fail_count" field if the given value is not nil.
func (_u *Sample1hUpdate) SetNillableFailCount(v *int) *Sample1hUpdate {
	if v != nil {
		_u.SetFailCount(*v)
	}
	return _u
}

// AddFailCount adds value to the "fail_count" field.
func (_u *Sample1hUpdate) AddFailCount(v int) *Sample1hUpdate {
	_u.mutation.AddFailCount(v)
	return _u
}

// SetRttP50Ms sets the "rtt_p50_ms" field.
func (_u *Sample1hUpdate) SetRttP50Ms(v float64) *Sample1hUpdate {
	_u.mutation.ResetRttP50Ms()
	_u.mutation.SetRttP50Ms(v)
	return _u
}

// SetNillableRttP50Ms sets the "rtt_p50_ms" field if the given value is not nil.
func (_u *Sample1hUpdate) SetNillableRttP50Ms(v *float64) *Sample1hUpdate {
	if v != nil {
		_u.SetRttP50Ms(*v)
	}
	return _u
}

// AddRttP50Ms adds value to the "rtt_p50_ms" field.
func (_u *Sample1hUpdate) AddRttP50Ms(v float64) *Sample1hUpdate {
	_u.mutation.AddRttP50Ms(v)
	return _u
}

// ClearRttP50Ms clears the value of the "rtt_p50_ms" field.
func (_u *Sample1hUpdate) ClearRttP50Ms() *Sample1hUpdate {
	_u.mutation.ClearRttP50Ms()
	return _u
}

// SetRttP95Ms sets the "rtt_p95_ms" field.
func (_u *Sample1hUpdate) SetRttP95Ms(v float64) *Sample1hUpdate {
	_u.mutation.ResetRttP95Ms()
	_u.mutation.SetRttP95Ms(v)
	return _u
}

// SetNillableRttP95Ms sets the "rtt_p95_ms" field if the given value is not nil.
func (_u *Sample1hUpdate) SetNillableRttP95Ms(v *float64) *Sample1hUpdate {
	if v != nil {
		_u.SetRttP95Ms(*v)
	}
	return _u
}

// AddRttP95Ms adds value to the "rtt_p95_ms" field.
func (_u *Sample1hUpdate) AddRttP95Ms(v float64) *Sample1hUpdate {
	_u.mutation.AddRttP95Ms(v)
	return _u
}

// ClearRttP95Ms clears the value of the "rtt_p95_ms" field.
func (_u *Sample1hUpdate) ClearRttP95Ms() *Sample1hUpdate {
	_u.mutation.ClearRttP95Ms()
	return _u
}

// SetRttP99Ms sets the "rtt_p99_ms" field.
func (_u *Sample1hUpdate) SetRttP99Ms(v float64) *Sample1hUpdate {
	_u.mutation.ResetRttP99Ms()
	_u.mutation.SetRttP99Ms(v)
	return _u
}

// SetNillableRttP99Ms sets the "rtt_p99_ms" field if the given value is not nil.
func (_u *Sample1hUpdate) SetNillableRttP99Ms(v *float64) *Sample1hUpdate {
	if v != nil {
		_u.SetRttP99Ms(*v)
	}
	return _u
}

// AddRttP99Ms adds value to the "rtt_p99_ms" field.
func (_u *Sample1hUpdate) AddRttP99Ms(v float64) *Sample1hUpdate {
	_u.mutation.AddRttP99Ms(v)
	return _u
}

// ClearRttP99Ms clears the value of the "rtt_p99_ms" field.
func (_u *Sample1hUpdate) ClearRttP99Ms() *Sample1hUpdate {
	_u.mutation.ClearRttP99Ms()
	return _u
}

// SetRttMaxMs sets the "rtt_max_ms" field.
func (_u *Sample1hUpdate) SetRttMaxMs(v float64) *Sample1hUpdate {
	_u.mutation.ResetRttMaxMs()
	_u.mutation.SetRttMaxMs(v)
	return _u
}

// SetNillableRttMaxMs sets the "rtt_max_ms" field if the given value is not nil.
func (_u *Sample1hUpdate) SetNillableRttMaxMs(v *float64) *Sample1hUpdate {
	if v != nil {
		_u.SetRttMaxMs(*v)
	}
	return _u
}

// AddRttMaxMs adds value to the "rtt_max_ms" field.
func (_u *Sample1hUpdate) AddRttMaxMs(v float64) *Sample1hUpdate {
	_u.mutation.AddRttMaxMs(v)
	return _u
}

// ClearRttMaxMs clears the value of the "rtt_max_ms" field.
func (_u *Sample1hUpdate) ClearRttMaxMs() *Sample1hUpdate {
	_u.mutation.ClearRttMaxMs()
	return _u
}

// SetRttMeanMs sets the "rtt_mean_ms" field.
func (_u *Sample1hUpdate) SetRttMeanMs(v float64) *Sample1hUpdate {
	_u.mutation.ResetRttMeanMs()
	_u.mutation.SetRttMeanMs(v)
	return _u
}

// SetNillableRttMeanMs sets the "rtt_mean_ms" field if the given value is not nil.
func (_u *Sample1hUpdate) SetNillableRttMeanMs(v *float64) *Sample1hUpdate {
	if v != nil {
		_u.SetRttMeanMs(*v)
	}
	return _u
}

// AddRttMeanMs adds value to the "rtt_mean_ms" field.
func (_u *Sample1hUpdate) AddRttMeanMs(v float64) *Sample1hUpdate {
	_u.mutation.AddRttMeanMs(v)
	return _u
}

// ClearRttMeanMs clears the value of the "rtt_mean_ms" field.
func (_u *Sample1hUpdate) ClearRttMeanMs() *Sample1hUpdate {
	_u.mutation.ClearRttMeanMs()
	return _u
}

// SetJitterMs sets the "jitter_ms" field.
func (_u *Sample1hUpdate) SetJitterMs(v float64) *Sample1hUpdate {
	_u.mutation.ResetJitterMs()
	_u.mutation.SetJitterMs(v)
	return _u
}

// SetNillableJitterMs sets the "jitter_ms" field if the given value is not nil.
func (_u *Sample1hUpdate) SetNillableJitterMs(v *float64) *Sample1hUpdate {
	if v != nil {
		_u.SetJitterMs(*v)
	}
	return _u
}

// AddJitterMs adds value to the "jitter_ms" field.
func (_u *Sample1hUpdate) AddJitterMs(v float64) *Sample1hUpdate {
	_u.mutation.AddJitterMs(v)
	return _u
}

// ClearJitterMs clears the value of the "jitter_ms" field.
func (_u *Sample1hUpdate) ClearJitterMs() *Sample1hUpdate {
	_u.mutation.ClearJitterMs()
	return _u
}

// SetErrors sets the "errors" field.
func (_u *Sample1hUpdate) SetErrors(v map[string]int) *Sample1hUpdate {
	_u.mutation.SetErrors(v)
	return _u
}

// ClearErrors clears the value of the "errors" field.
func (_u *Sample1hUpdate) ClearErrors() *Sample1hUpdate {
	_u.mutation.ClearErrors()
	return _u
}

// Mutation returns the Sample1hMutation object of the builder.
func (_u *Sample1hUpdate) Mutation() *Sample1hMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *Sample1hUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *Sample1hUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *Sample1hUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *Sample1hUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *Sample1hUpdate) check() error {
	if v, ok := _u.mutation.TargetLabel(); ok {
		if err := sample1h.TargetLabelValidator(v); err != nil {
			return &ValidationError{Name: "target_label", err: fmt.Errorf(`ent: validator failed for field "Sample1h.target_label": %w`, err)}
		}
	}
	return nil
}

func (_u *Sample1hUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sample1h.Table, sample1h.Columns, sqlgraph.NewFieldSpec(sample1h.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BucketStartUnixMs(); ok {
		_spec.SetField(sample1h.FieldBucketStartUnixMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBucketStartUnixMs(); ok {
		_spec.AddField(sample1h.FieldBucketStartUnixMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TargetLabel(); ok {
		_spec.SetField(sample1h.FieldTargetLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Count(); ok {
		_spec.SetField(sample1h.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCount(); ok {
		_spec.AddField(sample1h.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SuccessCount(); ok {
		_spec.SetField(sample1h.FieldSuccessCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSuccessCount(); ok {
		_spec.AddField(sample1h.FieldSuccessCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FailCount(); ok {
		_spec.SetField(sample1h.FieldFailCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailCount(); ok {
		_spec.AddField(sample1h.FieldFailCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RttP50Ms(); ok {
		_spec.SetField(sample1h.FieldRttP50Ms, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRttP50Ms(); ok {
		_spec.AddField(sample1h.FieldRttP50Ms, field.TypeFloat64, value)
	}
	if _u.mutation.RttP50MsCleared() {
		_spec.ClearField(sample1h.FieldRttP50Ms, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RttP95Ms(); ok {
		_spec.SetField(sample1h.FieldRttP95Ms, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRttP95Ms(); ok {
		_spec.AddField(sample1h.FieldRttP95Ms, field.TypeFloat64, value)
	}
	if _u.mutation.RttP95MsCleared() {
		_spec.ClearField(sample1h.FieldRttP95Ms, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RttP99Ms(); ok {
		_spec.SetField(sample1h.FieldRttP99Ms, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRttP99Ms(); ok {
		_spec.AddField(sample1h.FieldRttP99Ms, field.TypeFloat64, value)
	}
	if _u.mutation.RttP99MsCleared() {
		_spec.ClearField(sample1h.FieldRttP99Ms, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RttMaxMs(); ok {
		_spec.SetField(sample1h.FieldRttMaxMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRttMaxMs(); ok {
		_spec.AddField(sample1h.FieldRttMaxMs, field.TypeFloat64, value)
	}
	if _u.mutation.RttMaxMsCleared() {
		_spec.ClearField(sample1h.FieldRttMaxMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RttMeanMs(); ok {
		_spec.SetField(sample1h.FieldRttMeanMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRttMeanMs(); ok {
		_spec.AddField(sample1h.FieldRttMeanMs, field.TypeFloat64, value)
	}
	if _u.mutation.RttMeanMsCleared() {
		_spec.ClearField(sample1h.FieldRttMeanMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.JitterMs(); ok {
		_spec.SetField(sample1h.FieldJitterMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedJitterMs(); ok {
		_spec.AddField(sample1h.FieldJitterMs, field.TypeFloat64, value)
	}
	if _u.mutation.JitterMsCleared() {
		_spec.ClearField(sample1h.FieldJitterMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Errors(); ok {
		_spec.SetField(sample1h.FieldErrors, field.TypeJSON, value)
	}
	if _u.mutation.ErrorsCleared() {
		_spec.ClearField(sample1h.FieldErrors, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sample1h.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// Sample1hUpdateOne is the builder for updating a single Sample1h entity.
type Sample1hUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *Sample1hMutation
}

// SetBucketStartUnixMs sets the "bucket_start_unix_ms" field.
func (_u *Sample1hUpdateOne) SetBucketStartUnixMs(v int64) *Sample1hUpdateOne {
	_u.mutation.ResetBucketStartUnixMs()
	_u.mutation.SetBucketStartUnixMs(v)
	return _u
}

// SetNillableBucketStartUnixMs sets the "bucket_start_unix_ms" field if the given value is not nil.
func (_u *Sample1hUpdateOne) SetNillableBucketStartUnixMs(v *int64) *Sample1hUpdateOne {
	if v != nil {
		_u.SetBucketStartUnixMs(*v)
	}
	return _u
}

// AddBucketStartUnixMs adds value to the "bucket_start_unix_ms" field.
func (_u *Sample1hUpdateOne) AddBucketStartUnixMs(v int64) *Sample1hUpdateOne {
	_u.mutation.AddBucketStartUnixMs(v)
	return _u
}

// SetTargetLabel sets the "target_label" field.
func (_u *Sample1hUpdateOne) SetTargetLabel(v string) *Sample1hUpdateOne {
	_u.mutation.SetTargetLabel(v)
	return _u
}

// SetNillableTargetLabel sets the "target_label" field if the given value is not nil.
func (_u *Sample1hUpdateOne) SetNillableTargetLabel(v *string) *Sample1hUpdateOne {
	if v != nil {
		_u.SetTargetLabel(*v)
	}
	return _u
}

// SetCount sets the "count" field.
func (_u *Sample1hUpdateOne) SetCount(v int) *Sample1hUpdateOne {
	_u.mutation.ResetCount()
	_u.mutation.SetCount(v)
	return _u
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (_u *Sample1hUpdateOne) SetNillableCount(v *int) *Sample1hUpdateOne {
	if v != nil {
		_u.SetCount(*v)
	}
	return _u
}

// AddCount adds value to the "count" field.
func (_u *Sample1hUpdateOne) AddCount(v int) *Sample1hUpdateOne {
	_u.mutation.AddCount(v)
	return _u
}

// SetSuccessCount sets the "success_count" field.
func (_u *Sample1hUpdateOne) SetSuccessCount(v int) *Sample1hUpdateOne {
	_u.mutation.ResetSuccessCount()
	_u.mutation.SetSuccessCount(v)
	return _u
}

// SetNillableSuccessCount sets the "success_count" field if the given value is not nil.
func (_u *Sample1hUpdateOne) SetNillableSuccessCount(v *int) *Sample1hUpdateOne {
	if v != nil {
		_u.SetSuccessCount(*v)
	}
	return _u
}

// AddSuccessCount adds value to the "success_count" field.
func (_u *Sample1hUpdateOne) AddSuccessCount(v int) *Sample1hUpdateOne {
	_u.mutation.AddSuccessCount(v)
	return _u
}

// SetFailCount sets the "fail_count" field.
func (_u *Sample1hUpdateOne) SetFailCount(v int) *Sample1hUpdateOne {
	_u.mutation.ResetFailCount()
	_u.mutation.SetFailCount(v)
	return _u
}

// SetNillableFailCount sets the "fail_count" field if the given value is not nil.
func (_u *Sample1hUpdateOne) SetNillableFailCount(v *int) *Sample1hUpdateOne {
	if v != nil {
		_u.SetFailCount(*v)
	}
	return _u
}

// AddFailCount adds value to the "fail_count" field.
func (_u *Sample1hUpdateOne) AddFailCount(v int) *Sample1hUpdateOne {
	_u.mutation.AddFailCount(v)
	return _u
}

// SetRttP50Ms sets the "rtt_p50_ms" field.
func (_u *Sample1hUpdateOne) SetRttP50Ms(v float64) *Sample1hUpdateOne {
	_u.mutation.ResetRttP50Ms()
	_u.mutation.SetRttP50Ms(v)
	return _u
}

// SetNillableRttP50Ms sets the "rtt_p50_ms" field if the given value is not nil.
func (_u *Sample1hUpdateOne) SetNillableRttP50Ms(v *float64) *Sample1hUpdateOne {
	if v != nil {
		_u.SetRttP50Ms(*v)
	}
	return _u
}

// AddRttP50Ms adds value to the "rtt_p50_ms" field.
func (_u *Sample1hUpdateOne) AddRttP50Ms(v float64) *Sample1hUpdateOne {
	_u.mutation.AddRttP50Ms(v)
	return _u
}

// ClearRttP50Ms clears the value of the "rtt_p50_ms" field.
func (_u *Sample1hUpdateOne) ClearRttP50Ms() *Sample1hUpdateOne {
	_u.mutation.ClearRttP50Ms()
	return _u
}

// SetRttP95Ms sets the "rtt_p95_ms" field.
func (_u *Sample1hUpdateOne) SetRttP95Ms(v float64) *Sample1hUpdateOne {
	_u.mutation.ResetRttP95Ms()
	_u.mutation.SetRttP95Ms(v)
	return _u
}

// SetNillableRttP95Ms sets the "rtt_p95_ms" field if the given value is not nil.
func (_u *Sample1hUpdateOne) SetNillableRttP95Ms(v *float64) *Sample1hUpdateOne {
	if v != nil {
		_u.SetRttP95Ms(*v)
	}
	return _u
}

// AddRttP95Ms adds value to the "rtt_p95_ms" field.
func (_u *Sample1hUpdateOne) AddRttP95Ms(v float64) *Sample1hUpdateOne {
	_u.mutation.AddRttP95Ms(v)
	return _u
}

// ClearRttP95Ms clears the value of the "rtt_p95_ms" field.
func (_u *Sample1hUpdateOne) ClearRttP95Ms() *Sample1hUpdateOne {
	_u.mutation.ClearRttP95Ms()
	return _u
}

// SetRttP99Ms sets the "rtt_p99_ms" field.
func (_u *Sample1hUpdateOne) SetRttP99Ms(v float64) *Sample1hUpdateOne {
	_u.mutation.ResetRttP99Ms()
	_u.mutation.SetRttP99Ms(v)
	return _u
}

// SetNillableRttP99Ms sets the "rtt_p99_ms" field if the given value is not nil.
func (_u *Sample1hUpdateOne) SetNillableRttP99Ms(v *float64) *Sample1hUpdateOne {
	if v != nil {
		_u.SetRttP99Ms(*v)
	}
	return _u
}

// AddRttP99Ms adds value to the "rtt_p99_ms" field.
func (_u *Sample1hUpdateOne) AddRttP99Ms(v float64) *Sample1hUpdateOne {
	_u.mutation.AddRttP99Ms(v)
	return _u
}

// ClearRttP99Ms clears the value of the "rtt_p99_ms" field.
func (_u *Sample1hUpdateOne) ClearRttP99Ms() *Sample1hUpdateOne {
	_u.mutation.ClearRttP99Ms()
	return _u
}

// SetRttMaxMs sets the "rtt_max_ms" field.
func (_u *Sample1hUpdateOne) SetRttMaxMs(v float64) *Sample1hUpdateOne {
	_u.mutation.ResetRttMaxMs()
	_u.mutation.SetRttMaxMs(v)
	return _u
}

// SetNillableRttMaxMs sets the "rtt_max_ms" field if the given value is not nil.
func (_u *Sample1hUpdateOne) SetNillableRttMaxMs(v *float64) *Sample1hUpdateOne {
	if v != nil {
		_u.SetRttMaxMs(*v)
	}
	return _u
}

// AddRttMaxMs adds value to the "rtt_max_ms" field.
func (_u *Sample1hUpdateOne) AddRttMaxMs(v float64) *Sample1hUpdateOne {
	_u.mutation.AddRttMaxMs(v)
	return _u
}

// ClearRttMaxMs clears the value of the "rtt_max_ms" field.
func (_u *Sample1hUpdateOne) ClearRttMaxMs() *Sample1hUpdateOne {
	_u.mutation.ClearRttMaxMs()
	return _u
}

// SetRttMeanMs sets the "rtt_mean_ms" field.
func (_u *Sample1hUpdateOne) SetRttMeanMs(v float64) *Sample1hUpdateOne {
	_u.mutation.ResetRttMeanMs()
	_u.mutation.SetRttMeanMs(v)
	return _u
}

// SetNillableRttMeanMs sets the "rtt_mean_ms" field if the given value is not nil.
func (_u *Sample1hUpdateOne) SetNillableRttMeanMs(v *float64) *Sample1hUpdateOne {
	if v != nil {
		_u.SetRttMeanMs(*v)
	}
	return _u
}

// AddRttMeanMs adds value to the "rtt_mean_ms" field.
func (_u *Sample1hUpdateOne) AddRttMeanMs(v float64) *Sample1hUpdateOne {
	_u.mutation.AddRttMeanMs(v)
	return _u
}

// ClearRttMeanMs clears the value of the "rtt_mean_ms" field.
func (_u *Sample1hUpdateOne) ClearRttMeanMs() *Sample1hUpdateOne {
	_u.mutation.ClearRttMeanMs()
	return _u
}

// SetJitterMs sets the "jitter_ms" field.
func (_u *Sample1hUpdateOne) SetJitterMs(v float64) *Sample1hUpdateOne {
	_u.mutation.ResetJitterMs()
	_u.mutation.SetJitterMs(v)
	return _u
}

// SetNillableJitterMs sets the "jitter_ms" field if the given value is not nil.
func (_u *Sample1hUpdateOne) SetNillableJitterMs(v *float64) *Sample1hUpdateOne {
	if v != nil {
		_u.SetJitterMs(*v)
	}
	return _u
}

// AddJitterMs adds value to the "jitter_ms" field.
func (_u *Sample1hUpdateOne) AddJitterMs(v float64) *Sample1hUpdateOne {
	_u.mutation.AddJitterMs(v)
	return _u
}

// ClearJitterMs clears the value of the "jitter_ms" field.
func (_u *Sample1hUpdateOne) ClearJitterMs() *Sample1hUpdateOne {
	_u.mutation.ClearJitterMs()
	return _u
}

// SetErrors sets the "errors" field.
func (_u *Sample1hUpdateOne) SetErrors(v map[string]int) *Sample1hUpdateOne {
	_u.mutation.SetErrors(v)
	return _u
}

// ClearErrors clears the value of the "errors" field.
func (_u *Sample1hUpdateOne) ClearErrors() *Sample1hUpdateOne {
	_u.mutation.ClearErrors()
	return _u
}

// Mutation returns the Sample1hMutation object of the builder.
func (_u *Sample1hUpdateOne) Mutation() *Sample1hMutation {
	return _u.mutation
}

// Where appends a list predicates to the Sample1hUpdate builder.
func (_u *Sample1hUpdateOne) Where(ps ...predicate.Sample1h) *Sample1hUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *Sample1hUpdateOne) Select(field string, fields ...string) *Sample1hUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Sample1h entity.
func (_u *Sample1hUpdateOne) Save(ctx context.Context) (*Sample1h, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *Sample1hUpdateOne) SaveX(ctx context.Context) *Sample1h {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *Sample1hUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *Sample1hUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *Sample1hUpdateOne) check() error {
	if v, ok := _u.mutation.TargetLabel(); ok {
		if err := sample1h.TargetLabelValidator(v); err != nil {
			return &ValidationError{Name: "target_label", err: fmt.Errorf(`ent: validator failed for field "Sample1h.target_label": %w`, err)}
		}
	}
	return nil
}

func (_u *Sample1hUpdateOne) sqlSave(ctx context.Context) (_node *Sample1h, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sample1h.Table, sample1h.Columns, sqlgraph.NewFieldSpec(sample1h.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Sample1h.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sample1h.FieldID)
		for _, f := range fields {
			if !sample1h.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sample1h.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BucketStartUnixMs(); ok {
		_spec.SetField(sample1h.FieldBucketStartUnixMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBucketStartUnixMs(); ok {
		_spec.AddField(sample1h.FieldBucketStartUnixMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TargetLabel(); ok {
		_spec.SetField(sample1h.FieldTargetLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Count(); ok {
		_spec.SetField(sample1h.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCount(); ok {
		_spec.AddField(sample1h.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SuccessCount(); ok {
		_spec.SetField(sample1h.FieldSuccessCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSuccessCount(); ok {
		_spec.AddField(sample1h.FieldSuccessCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FailCount(); ok {
		_spec.SetField(sample1h.FieldFailCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailCount(); ok {
		_spec.AddField(sample1h.FieldFailCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RttP50Ms(); ok {
		_spec.SetField(sample1h.FieldRttP50Ms, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRttP50Ms(); ok {
		_spec.AddField(sample1h.FieldRttP50Ms, field.TypeFloat64, value)
	}
	if _u.mutation.RttP50MsCleared() {
		_spec.ClearField(sample1h.FieldRttP50Ms, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RttP95Ms(); ok {
		_spec.SetField(sample1h.FieldRttP95Ms, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRttP95Ms(); ok {
		_spec.AddField(sample1h.FieldRttP95Ms, field.TypeFloat64, value)
	}
	if _u.mutation.RttP95MsCleared() {
		_spec.ClearField(sample1h.FieldRttP95Ms, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RttP99Ms(); ok {
		_spec.SetField(sample1h.FieldRttP99Ms, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRttP99Ms(); ok {
		_spec.AddField(sample1h.FieldRttP99Ms, field.TypeFloat64, value)
	}
	if _u.mutation.RttP99MsCleared() {
		_spec.ClearField(sample1h.FieldRttP99Ms, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RttMaxMs(); ok {
		_spec.SetField(sample1h.FieldRttMaxMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRttMaxMs(); ok {
		_spec.AddField(sample1h.FieldRttMaxMs, field.TypeFloat64, value)
	}
	if _u.mutation.RttMaxMsCleared() {
		_spec.ClearField(sample1h.FieldRttMaxMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RttMeanMs(); ok {
		_spec.SetField(sample1h.FieldRttMeanMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRttMeanMs(); ok {
		_spec.AddField(sample1h.FieldRttMeanMs, field.TypeFloat64, value)
	}
	if _u.mutation.RttMeanMsCleared() {
		_spec.ClearField(sample1h.FieldRttMeanMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.JitterMs(); ok {
		_spec.SetField(sample1h.FieldJitterMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedJitterMs(); ok {
		_spec.AddField(sample1h.FieldJitterMs, field.TypeFloat64, value)
	}
	if _u.mutation.JitterMsCleared() {
		_spec.ClearField(sample1h.FieldJitterMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Errors(); ok {
		_spec.SetField(sample1h.FieldErrors, field.TypeJSON, value)
	}
	if _u.mutation.ErrorsCleared() {
		_spec.ClearField(sample1h.FieldErrors, field.TypeJSON)
	}
	_node = &Sample1h{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sample1h.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
