// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sid-technologies/vigil/db/ent/predicate"
	"github.com/sid-technologies/vigil/db/ent/sample1min"
)

// Sample1minUpdate is the builder for updating Sample1min entities.
type Sample1minUpdate struct {
	config
	hooks    []Hook
	mutation *Sample1minMutation
}

// Where appends a list predicates to the Sample1minUpdate builder.
func (_u *Sample1minUpdate) Where(ps ...predicate.Sample1min) *Sample1minUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBucketStartUnixMs sets the "bucket_start_unix_ms" field.
func (_u *Sample1minUpdate) SetBucketStartUnixMs(v int64) *Sample1minUpdate {
	_u.mutation.ResetBucketStartUnixMs()
	_u.mutation.SetBucketStartUnixMs(v)
	return _u
}

// SetNillableBucketStartUnixMs sets the "bucket_start_unix_ms" field if the given value is not nil.
func (_u *Sample1minUpdate) SetNillableBucketStartUnixMs(v *int64) *Sample1minUpdate {
	if v != nil {
		_u.SetBucketStartUnixMs(*v)
	}
	return _u
}

// AddBucketStartUnixMs adds value to the "bucket_start_unix_ms" field.
func (_u *Sample1minUpdate) AddBucketStartUnixMs(v int64) *Sample1minUpdate {
	_u.mutation.AddBucketStartUnixMs(v)
	return _u
}

// SetTargetLabel sets the "target_label" field.
func (_u *Sample1minUpdate) SetTargetLabel(v string) *Sample1minUpdate {
	_u.mutation.SetTargetLabel(v)
	return _u
}

// SetNillableTargetLabel sets the "target_label" field if the given value is not nil.
func (_u *Sample1minUpdate) SetNillableTargetLabel(v *string) *Sample1minUpdate {
	if v != nil {
		_u.SetTargetLabel(*v)
	}
	return _u
}

// SetCount sets the "count" field.
func (_u *Sample1minUpdate) SetCount(v int) *Sample1minUpdate {
	_u.mutation.ResetCount()
	_u.mutation.SetCount(v)
	return _u
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (_u *Sample1minUpdate) SetNillableCount(v *int) *Sample1minUpdate {
	if v != nil {
		_u.SetCount(*v)
	}
	return _u
}

// AddCount adds value to the "count" field.
func (_u *Sample1minUpdate) AddCount(v int) *Sample1minUpdate {
	_u.mutation.AddCount(v)
	return _u
}

// SetSuccessCount sets the "success_count" field.
func (_u *Sample1minUpdate) SetSuccessCount(v int) *Sample1minUpdate {
	_u.mutation.ResetSuccessCount()
	_u.mutation.SetSuccessCount(v)
	return _u
}

// SetNillableSuccessCount sets the "success_count" field if the given value is not nil.
func (_u *Sample1minUpdate) SetNillableSuccessCount(v *int) *Sample1minUpdate {
	if v != nil {
		_u.SetSuccessCount(*v)
	}
	return _u
}

// AddSuccessCount adds value to the "success_count" field.
func (_u *Sample1minUpdate) AddSuccessCount(v int) *Sample1minUpdate {
	_u.mutation.AddSuccessCount(v)
	return _u
}

// SetFailCount sets the "fail_count" field.
func (_u *Sample1minUpdate) SetFailCount(v int) *Sample1minUpdate {
	_u.mutation.ResetFailCount()
	_u.mutation.SetFailCount(v)
	return _u
}

// SetNillableFailCount sets the "fail_count" field if the given value is not nil.
func (_u *Sample1minUpdate) SetNillableFailCount(v *int) *Sample1minUpdate {
	if v != nil {
		_u.SetFailCount(*v)
	}
	return _u
}

// AddFailCount adds value to the "fail_count" field.
func (_u *Sample1minUpdate) AddFailCount(v int) *Sample1minUpdate {
	_u.mutation.AddFailCount(v)
	return _u
}

// SetRttP50Ms sets the "rtt_p50_ms" field.
func (_u *Sample1minUpdate) SetRttP50Ms(v float64) *Sample1minUpdate {
	_u.mutation.ResetRttP50Ms()
	_u.mutation.SetRttP50Ms(v)
	return _u
}

// SetNillableRttP50Ms sets the "rtt_p50_ms" field if the given value is not nil.
func (_u *Sample1minUpdate) SetNillableRttP50Ms(v *float64) *Sample1minUpdate {
	if v != nil {
		_u.SetRttP50Ms(*v)
	}
	return _u
}

// AddRttP50Ms adds value to the "rtt_p50_ms" field.
func (_u *Sample1minUpdate) AddRttP50Ms(v float64) *Sample1minUpdate {
	_u.mutation.AddRttP50Ms(v)
	return _u
}

// ClearRttP50Ms clears the value of the "rtt_p50_ms" field.
func (_u *Sample1minUpdate) ClearRttP50Ms() *Sample1minUpdate {
	_u.mutation.ClearRttP50Ms()
	return _u
}

// SetRttP95Ms sets the "rtt_p95_ms" field.
func (_u *Sample1minUpdate) SetRttP95Ms(v float64) *Sample1minUpdate {
	_u.mutation.ResetRttP95Ms()
	_u.mutation.SetRttP95Ms(v)
	return _u
}

// SetNillableRttP95Ms sets the "rtt_p95_ms" field if the given value is not nil.
func (_u *Sample1minUpdate) SetNillableRttP95Ms(v *float64) *Sample1minUpdate {
	if v != nil {
		_u.SetRttP95Ms(*v)
	}
	return _u
}

// AddRttP95Ms adds value to the "rtt_p95_ms" field.
func (_u *Sample1minUpdate) AddRttP95Ms(v float64) *Sample1minUpdate {
	_u.mutation.AddRttP95Ms(v)
	return _u
}

// ClearRttP95Ms clears the value of the "rtt_p95_ms" field.
func (_u *Sample1minUpdate) ClearRttP95Ms() *Sample1minUpdate {
	_u.mutation.ClearRttP95Ms()
	return _u
}

// SetRttP99Ms sets the "rtt_p99_ms" field.
func (_u *Sample1minUpdate) SetRttP99Ms(v float64) *Sample1minUpdate {
	_u.mutation.ResetRttP99Ms()
	_u.mutation.SetRttP99Ms(v)
	return _u
}

// SetNillableRttP99Ms sets the "rtt_p99_ms" field if the given value is not nil.
func (_u *Sample1minUpdate) SetNillableRttP99Ms(v *float64) *Sample1minUpdate {
	if v != nil {
		_u.SetRttP99Ms(*v)
	}
	return _u
}

// AddRttP99Ms adds value to the "rtt_p99_ms" field.
func (_u *Sample1minUpdate) AddRttP99Ms(v float64) *Sample1minUpdate {
	_u.mutation.AddRttP99Ms(v)
	return _u
}

// ClearRttP99Ms clears the value of the "rtt_p99_ms" field.
func (_u *Sample1minUpdate) ClearRttP99Ms() *Sample1minUpdate {
	_u.mutation.ClearRttP99Ms()
	return _u
}

// SetRttMaxMs sets the "rtt_max_ms" field.
func (_u *Sample1minUpdate) SetRttMaxMs(v float64) *Sample1minUpdate {
	_u.mutation.ResetRttMaxMs()
	_u.mutation.SetRttMaxMs(v)
	return _u
}

// SetNillableRttMaxMs sets the "rtt_max_ms" field if the given value is not nil.
func (_u *Sample1minUpdate) SetNillableRttMaxMs(v *float64) *Sample1minUpdate {
	if v != nil {
		_u.SetRttMaxMs(*v)
	}
	return _u
}

// AddRttMaxMs adds value to the "rtt_max_ms" field.
func (_u *Sample1minUpdate) AddRttMaxMs(v float64) *Sample1minUpdate {
	_u.mutation.AddRttMaxMs(v)
	return _u
}

// ClearRttMaxMs clears the value of the "rtt_max_ms" field.
func (_u *Sample1minUpdate) ClearRttMaxMs() *Sample1minUpdate {
	_u.mutation.ClearRttMaxMs()
	return _u
}

// SetRttMeanMs sets the "rtt_mean_ms" field.
func (_u *Sample1minUpdate) SetRttMeanMs(v float64) *Sample1minUpdate {
	_u.mutation.ResetRttMeanMs()
	_u.mutation.SetRttMeanMs(v)
	return _u
}

// SetNillableRttMeanMs sets the "rtt_mean_ms" field if the given value is not nil.
func (_u *Sample1minUpdate) SetNillableRttMeanMs(v *float64) *Sample1minUpdate {
	if v != nil {
		_u.SetRttMeanMs(*v)
	}
	return _u
}

// AddRttMeanMs adds value to the "rtt_mean_ms" field.
func (_u *Sample1minUpdate) AddRttMeanMs(v float64) *Sample1minUpdate {
	_u.mutation.AddRttMeanMs(v)
	return _u
}

// ClearRttMeanMs clears the value of the "rtt_mean_ms" field.
func (_u *Sample1minUpdate) ClearRttMeanMs() *Sample1minUpdate {
	_u.mutation.ClearRttMeanMs()
	return _u
}

// SetJitterMs sets the "jitter_ms" field.
func (_u *Sample1minUpdate) SetJitterMs(v float64) *Sample1minUpdate {
	_u.mutation.ResetJitterMs()
	_u.mutation.SetJitterMs(v)
	return _u
}

// SetNillableJitterMs sets the "jitter_ms" field if the given value is not nil.
func (_u *Sample1minUpdate) SetNillableJitterMs(v *float64) *Sample1minUpdate {
	if v != nil {
		_u.SetJitterMs(*v)
	}
	return _u
}

// AddJitterMs adds value to the "jitter_ms" field.
func (_u *Sample1minUpdate) AddJitterMs(v float64) *Sample1minUpdate {
	_u.mutation.AddJitterMs(v)
	return _u
}

// ClearJitterMs clears the value of the "jitter_ms" field.
func (_u *Sample1minUpdate) ClearJitterMs() *Sample1minUpdate {
	_u.mutation.ClearJitterMs()
	return _u
}

// SetErrors sets the "errors" field.
func (_u *Sample1minUpdate) SetErrors(v map[string]int) *Sample1minUpdate {
	_u.mutation.SetErrors(v)
	return _u
}

// ClearErrors clears the value of the "errors" field.
func (_u *Sample1minUpdate) ClearErrors() *Sample1minUpdate {
	_u.mutation.ClearErrors()
	return _u
}

// Mutation returns the Sample1minMutation object of the builder.
func (_u *Sample1minUpdate) Mutation() *Sample1minMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *Sample1minUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *Sample1minUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *Sample1minUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *Sample1minUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *Sample1minUpdate) check() error {
	if v, ok := _u.mutation.TargetLabel(); ok {
		if err := sample1min.TargetLabelValidator(v); err != nil {
			return &ValidationError{Name: "target_label", err: fmt.Errorf(`ent: validator failed for field "Sample1min.target_label": %w`, err)}
		}
	}
	return nil
}

func (_u *Sample1minUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sample1min.Table, sample1min.Columns, sqlgraph.NewFieldSpec(sample1min.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BucketStartUnixMs(); ok {
		_spec.SetField(sample1min.FieldBucketStartUnixMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBucketStartUnixMs(); ok {
		_spec.AddField(sample1min.FieldBucketStartUnixMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TargetLabel(); ok {
		_spec.SetField(sample1min.FieldTargetLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Count(); ok {
		_spec.SetField(sample1min.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCount(); ok {
		_spec.AddField(sample1min.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SuccessCount(); ok {
		_spec.SetField(sample1min.FieldSuccessCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSuccessCount(); ok {
		_spec.AddField(sample1min.FieldSuccessCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FailCount(); ok {
		_spec.SetField(sample1min.FieldFailCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailCount(); ok {
		_spec.AddField(sample1min.FieldFailCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RttP50Ms(); ok {
		_spec.SetField(sample1min.FieldRttP50Ms, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRttP50Ms(); ok {
		_spec.AddField(sample1min.FieldRttP50Ms, field.TypeFloat64, value)
	}
	if _u.mutation.RttP50MsCleared() {
		_spec.ClearField(sample1min.FieldRttP50Ms, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RttP95Ms(); ok {
		_spec.SetField(sample1min.FieldRttP95Ms, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRttP95Ms(); ok {
		_spec.AddField(sample1min.FieldRttP95Ms, field.TypeFloat64, value)
	}
	if _u.mutation.RttP95MsCleared() {
		_spec.ClearField(sample1min.FieldRttP95Ms, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RttP99Ms(); ok {
		_spec.SetField(sample1min.FieldRttP99Ms, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRttP99Ms(); ok {
		_spec.AddField(sample1min.FieldRttP99Ms, field.TypeFloat64, value)
	}
	if _u.mutation.RttP99MsCleared() {
		_spec.ClearField(sample1min.FieldRttP99Ms, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RttMaxMs(); ok {
		_spec.SetField(sample1min.FieldRttMaxMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRttMaxMs(); ok {
		_spec.AddField(sample1min.FieldRttMaxMs, field.TypeFloat64, value)
	}
	if _u.mutation.RttMaxMsCleared() {
		_spec.ClearField(sample1min.FieldRttMaxMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RttMeanMs(); ok {
		_spec.SetField(sample1min.FieldRttMeanMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRttMeanMs(); ok {
		_spec.AddField(sample1min.FieldRttMeanMs, field.TypeFloat64, value)
	}
	if _u.mutation.RttMeanMsCleared() {
		_spec.ClearField(sample1min.FieldRttMeanMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.JitterMs(); ok {
		_spec.SetField(sample1min.FieldJitterMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedJitterMs(); ok {
		_spec.AddField(sample1min.FieldJitterMs, field.TypeFloat64, value)
	}
	if _u.mutation.JitterMsCleared() {
		_spec.ClearField(sample1min.FieldJitterMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Errors(); ok {
		_spec.SetField(sample1min.FieldErrors, field.TypeJSON, value)
	}
	if _u.mutation.ErrorsCleared() {
		_spec.ClearField(sample1min.FieldErrors, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sample1min.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// Sample1minUpdateOne is the builder for updating a single Sample1min entity.
type Sample1minUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *Sample1minMutation
}

// SetBucketStartUnixMs sets the "bucket_start_unix_ms" field.
func (_u *Sample1minUpdateOne) SetBucketStartUnixMs(v int64) *Sample1minUpdateOne {
	_u.mutation.ResetBucketStartUnixMs()
	_u.mutation.SetBucketStartUnixMs(v)
	return _u
}

// SetNillableBucketStartUnixMs sets the "bucket_start_unix_ms" field if the given value is not nil.
func (_u *Sample1minUpdateOne) SetNillableBucketStartUnixMs(v *int64) *Sample1minUpdateOne {
	if v != nil {
		_u.SetBucketStartUnixMs(*v)
	}
	return _u
}

// AddBucketStartUnixMs adds value to the "bucket_start_unix_ms" field.
func (_u *Sample1minUpdateOne) AddBucketStartUnixMs(v int64) *Sample1minUpdateOne {
	_u.mutation.AddBucketStartUnixMs(v)
	return _u
}

// SetTargetLabel sets the "target_label" field.
func (_u *Sample1minUpdateOne) SetTargetLabel(v string) *Sample1minUpdateOne {
	_u.mutation.SetTargetLabel(v)
	return _u
}

// SetNillableTargetLabel sets the "target_label" field if the given value is not nil.
func (_u *Sample1minUpdateOne) SetNillableTargetLabel(v *string) *Sample1minUpdateOne {
	if v != nil {
		_u.SetTargetLabel(*v)
	}
	return _u
}

// SetCount sets the "count" field.
func (_u *Sample1minUpdateOne) SetCount(v int) *Sample1minUpdateOne {
	_u.mutation.ResetCount()
	_u.mutation.SetCount(v)
	return _u
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (_u *Sample1minUpdateOne) SetNillableCount(v *int) *Sample1minUpdateOne {
	if v != nil {
		_u.SetCount(*v)
	}
	return _u
}

// AddCount adds value to the "count" field.
func (_u *Sample1minUpdateOne) AddCount(v int) *Sample1minUpdateOne {
	_u.mutation.AddCount(v)
	return _u
}

// SetSuccessCount sets the "success_count" field.
func (_u *Sample1minUpdateOne) SetSuccessCount(v int) *Sample1minUpdateOne {
	_u.mutation.ResetSuccessCount()
	_u.mutation.SetSuccessCount(v)
	return _u
}

// SetNillableSuccessCount sets the "success_count" field if the given value is not nil.
func (_u *Sample1minUpdateOne) SetNillableSuccessCount(v *int) *Sample1minUpdateOne {
	if v != nil {
		_u.SetSuccessCount(*v)
	}
	return _u
}

// AddSuccessCount adds value to the "success_count" field.
func (_u *Sample1minUpdateOne) AddSuccessCount(v int) *Sample1minUpdateOne {
	_u.mutation.AddSuccessCount(v)
	return _u
}

// SetFailCount sets the "fail_count" field.
func (_u *Sample1minUpdateOne) SetFailCount(v int) *Sample1minUpdateOne {
	_u.mutation.ResetFailCount()
	_u.mutation.SetFailCount(v)
	return _u
}

// SetNillableFailCount sets the "fail_count" field if the given value is not nil.
func (_u *Sample1minUpdateOne) SetNillableFailCount(v *int) *Sample1minUpdateOne {
	if v != nil {
		_u.SetFailCount(*v)
	}
	return _u
}

// AddFailCount adds value to the "fail_count" field.
func (_u *Sample1minUpdateOne) AddFailCount(v int) *Sample1minUpdateOne {
	_u.mutation.AddFailCount(v)
	return _u
}

// SetRttP50Ms sets the "rtt_p50_ms" field.
func (_u *Sample1minUpdateOne) SetRttP50Ms(v float64) *Sample1minUpdateOne {
	_u.mutation.ResetRttP50Ms()
	_u.mutation.SetRttP50Ms(v)
	return _u
}

// SetNillableRttP50Ms sets the "rtt_p50_ms" field if the given value is not nil.
func (_u *Sample1minUpdateOne) SetNillableRttP50Ms(v *float64) *Sample1minUpdateOne {
	if v != nil {
		_u.SetRttP50Ms(*v)
	}
	return _u
}

// AddRttP50Ms adds value to the "rtt_p50_ms" field.
func (_u *Sample1minUpdateOne) AddRttP50Ms(v float64) *Sample1minUpdateOne {
	_u.mutation.AddRttP50Ms(v)
	return _u
}

// ClearRttP50Ms clears the value of the "rtt_p50_ms" field.
func (_u *Sample1minUpdateOne) ClearRttP50Ms() *Sample1minUpdateOne {
	_u.mutation.ClearRttP50Ms()
	return _u
}

// SetRttP95Ms sets the "rtt_p95_ms" field.
func (_u *Sample1minUpdateOne) SetRttP95Ms(v float64) *Sample1minUpdateOne {
	_u.mutation.ResetRttP95Ms()
	_u.mutation.SetRttP95Ms(v)
	return _u
}

// SetNillableRttP95Ms sets the "rtt_p95_ms" field if the given value is not nil.
func (_u *Sample1minUpdateOne) SetNillableRttP95Ms(v *float64) *Sample1minUpdateOne {
	if v != nil {
		_u.SetRttP95Ms(*v)
	}
	return _u
}

// AddRttP95Ms adds value to the "rtt_p95_ms" field.
func (_u *Sample1minUpdateOne) AddRttP95Ms(v float64) *Sample1minUpdateOne {
	_u.mutation.AddRttP95Ms(v)
	return _u
}

// ClearRttP95Ms clears the value of the "rtt_p95_ms" field.
func (_u *Sample1minUpdateOne) ClearRttP95Ms() *Sample1minUpdateOne {
	_u.mutation.ClearRttP95Ms()
	return _u
}

// SetRttP99Ms sets the "rtt_p99_ms" field.
func (_u *Sample1minUpdateOne) SetRttP99Ms(v float64) *Sample1minUpdateOne {
	_u.mutation.ResetRttP99Ms()
	_u.mutation.SetRttP99Ms(v)
	return _u
}

// SetNillableRttP99Ms sets the "rtt_p99_ms" field if the given value is not nil.
func (_u *Sample1minUpdateOne) SetNillableRttP99Ms(v *float64) *Sample1minUpdateOne {
	if v != nil {
		_u.SetRttP99Ms(*v)
	}
	return _u
}

// AddRttP99Ms adds value to the "rtt_p99_ms" field.
func (_u *Sample1minUpdateOne) AddRttP99Ms(v float64) *Sample1minUpdateOne {
	_u.mutation.AddRttP99Ms(v)
	return _u
}

// ClearRttP99Ms clears the value of the "rtt_p99_ms" field.
func (_u *Sample1minUpdateOne) ClearRttP99Ms() *Sample1minUpdateOne {
	_u.mutation.ClearRttP99Ms()
	return _u
}

// SetRttMaxMs sets the "rtt_max_ms" field.
func (_u *Sample1minUpdateOne) SetRttMaxMs(v float64) *Sample1minUpdateOne {
	_u.mutation.ResetRttMaxMs()
	_u.mutation.SetRttMaxMs(v)
	return _u
}

// SetNillableRttMaxMs sets the "rtt_max_ms" field if the given value is not nil.
func (_u *Sample1minUpdateOne) SetNillableRttMaxMs(v *float64) *Sample1minUpdateOne {
	if v != nil {
		_u.SetRttMaxMs(*v)
	}
	return _u
}

// AddRttMaxMs adds value to the "rtt_max_ms" field.
func (_u *Sample1minUpdateOne) AddRttMaxMs(v float64) *Sample1minUpdateOne {
	_u.mutation.AddRttMaxMs(v)
	return _u
}

// ClearRttMaxMs clears the value of the "rtt_max_ms" field.
func (_u *Sample1minUpdateOne) ClearRttMaxMs() *Sample1minUpdateOne {
	_u.mutation.ClearRttMaxMs()
	return _u
}

// SetRttMeanMs sets the "rtt_mean_ms" field.
func (_u *Sample1minUpdateOne) SetRttMeanMs(v float64) *Sample1minUpdateOne {
	_u.mutation.ResetRttMeanMs()
	_u.mutation.SetRttMeanMs(v)
	return _u
}

// SetNillableRttMeanMs sets the "rtt_mean_ms" field if the given value is not nil.
func (_u *Sample1minUpdateOne) SetNillableRttMeanMs(v *float64) *Sample1minUpdateOne {
	if v != nil {
		_u.SetRttMeanMs(*v)
	}
	return _u
}

// AddRttMeanMs adds value to the "rtt_mean_ms" field.
func (_u *Sample1minUpdateOne) AddRttMeanMs(v float64) *Sample1minUpdateOne {
	_u.mutation.AddRttMeanMs(v)
	return _u
}

// ClearRttMeanMs clears the value of the "rtt_mean_ms" field.
func (_u *Sample1minUpdateOne) ClearRttMeanMs() *Sample1minUpdateOne {
	_u.mutation.ClearRttMeanMs()
	return _u
}

// SetJitterMs sets the "jitter_ms" field.
func (_u *Sample1minUpdateOne) SetJitterMs(v float64) *Sample1minUpdateOne {
	_u.mutation.ResetJitterMs()
	_u.mutation.SetJitterMs(v)
	return _u
}

// SetNillableJitterMs sets the "jitter_ms" field if the given value is not nil.
func (_u *Sample1minUpdateOne) SetNillableJitterMs(v *float64) *Sample1minUpdateOne {
	if v != nil {
		_u.SetJitterMs(*v)
	}
	return _u
}

// AddJitterMs adds value to the "jitter_ms" field.
func (_u *Sample1minUpdateOne) AddJitterMs(v float64) *Sample1minUpdateOne {
	_u.mutation.AddJitterMs(v)
	return _u
}

// ClearJitterMs clears the value of the "jitter_ms" field.
func (_u *Sample1minUpdateOne) ClearJitterMs() *Sample1minUpdateOne {
	_u.mutation.ClearJitterMs()
	return _u
}

// SetErrors sets the "errors" field.
func (_u *Sample1minUpdateOne) SetErrors(v map[string]int) *Sample1minUpdateOne {
	_u.mutation.SetErrors(v)
	return _u
}

// ClearErrors clears the value of the "errors" field.
func (_u *Sample1minUpdateOne) ClearErrors() *Sample1minUpdateOne {
	_u.mutation.ClearErrors()
	return _u
}

// Mutation returns the Sample1minMutation object of the builder.
func (_u *Sample1minUpdateOne) Mutation() *Sample1minMutation {
	return _u.mutation
}

// Where appends a list predicates to the Sample1minUpdate builder.
func (_u *Sample1minUpdateOne) Where(ps ...predicate.Sample1min) *Sample1minUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *Sample1minUpdateOne) Select(field string, fields ...string) *Sample1minUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Sample1min entity.
func (_u *Sample1minUpdateOne) Save(ctx context.Context) (*Sample1min, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *Sample1minUpdateOne) SaveX(ctx context.Context) *Sample1min {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *Sample1minUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *Sample1minUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *Sample1minUpdateOne) check() error {
	if v, ok := _u.mutation.TargetLabel(); ok {
		if err := sample1min.TargetLabelValidator(v); err != nil {
			return &ValidationError{Name: "target_label", err: fmt.Errorf(`ent: validator failed for field "Sample1min.target_label": %w`, err)}
		}
	}
	return nil
}

func (_u *Sample1minUpdateOne) sqlSave(ctx context.Context) (_node *Sample1min, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sample1min.Table, sample1min.Columns, sqlgraph.NewFieldSpec(sample1min.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Sample1min.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sample1min.FieldID)
		for _, f := range fields {
			if !sample1min.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sample1min.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BucketStartUnixMs(); ok {
		_spec.SetField(sample1min.FieldBucketStartUnixMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBucketStartUnixMs(); ok {
		_spec.AddField(sample1min.FieldBucketStartUnixMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TargetLabel(); ok {
		_spec.SetField(sample1min.FieldTargetLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Count(); ok {
		_spec.SetField(sample1min.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCount(); ok {
		_spec.AddField(sample1min.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SuccessCount(); ok {
		_spec.SetField(sample1min.FieldSuccessCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSuccessCount(); ok {
		_spec.AddField(sample1min.FieldSuccessCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FailCount(); ok {
		_spec.SetField(sample1min.FieldFailCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailCount(); ok {
		_spec.AddField(sample1min.FieldFailCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RttP50Ms(); ok {
		_spec.SetField(sample1min.FieldRttP50Ms, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRttP50Ms(); ok {
		_spec.AddField(sample1min.FieldRttP50Ms, field.TypeFloat64, value)
	}
	if _u.mutation.RttP50MsCleared() {
		_spec.ClearField(sample1min.FieldRttP50Ms, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RttP95Ms(); ok {
		_spec.SetField(sample1min.FieldRttP95Ms, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRttP95Ms(); ok {
		_spec.AddField(sample1min.FieldRttP95Ms, field.TypeFloat64, value)
	}
	if _u.mutation.RttP95MsCleared() {
		_spec.ClearField(sample1min.FieldRttP95Ms, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RttP99Ms(); ok {
		_spec.SetField(sample1min.FieldRttP99Ms, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRttP99Ms(); ok {
		_spec.AddField(sample1min.FieldRttP99Ms, field.TypeFloat64, value)
	}
	if _u.mutation.RttP99MsCleared() {
		_spec.ClearField(sample1min.FieldRttP99Ms, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RttMaxMs(); ok {
		_spec.SetField(sample1min.FieldRttMaxMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRttMaxMs(); ok {
		_spec.AddField(sample1min.FieldRttMaxMs, field.TypeFloat64, value)
	}
	if _u.mutation.RttMaxMsCleared() {
		_spec.ClearField(sample1min.FieldRttMaxMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RttMeanMs(); ok {
		_spec.SetField(sample1min.FieldRttMeanMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRttMeanMs(); ok {
		_spec.AddField(sample1min.FieldRttMeanMs, field.TypeFloat64, value)
	}
	if _u.mutation.RttMeanMsCleared() {
		_spec.ClearField(sample1min.FieldRttMeanMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.JitterMs(); ok {
		_spec.SetField(sample1min.FieldJitterMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedJitterMs(); ok {
		_spec.AddField(sample1min.FieldJitterMs, field.TypeFloat64, value)
	}
	if _u.mutation.JitterMsCleared() {
		_spec.ClearField(sample1min.FieldJitterMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Errors(); ok {
		_spec.SetField(sample1min.FieldErrors, field.TypeJSON, value)
	}
	if _u.mutation.ErrorsCleared() {
		_spec.ClearField(sample1min.FieldErrors, field.TypeJSON)
	}
	_node = &Sample1min{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sample1min.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
