// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sid-technologies/vigil/db/ent/sample"
)

// SampleCreate is the builder for creating a Sample entity.
type SampleCreate struct {
	config
	mutation *SampleMutation
	hooks    []Hook
}

// SetTsUnixMs sets the "ts_unix_ms" field.
func (_c *SampleCreate) SetTsUnixMs(v int64) *SampleCreate {
	_c.mutation.SetTsUnixMs(v)
	return _c
}

// SetTargetLabel sets the "target_label" field.
func (_c *SampleCreate) SetTargetLabel(v string) *SampleCreate {
	_c.mutation.SetTargetLabel(v)
	return _c
}

// SetTargetKind sets the "target_kind" field.
func (_c *SampleCreate) SetTargetKind(v string) *SampleCreate {
	_c.mutation.SetTargetKind(v)
	return _c
}

// SetTargetHost sets the "target_host" field.
func (_c *SampleCreate) SetTargetHost(v string) *SampleCreate {
	_c.mutation.SetTargetHost(v)
	return _c
}

// SetTargetPort sets the "target_port" field.
func (_c *SampleCreate) SetTargetPort(v int) *SampleCreate {
	_c.mutation.SetTargetPort(v)
	return _c
}

// SetNillableTargetPort sets the "target_port" field if the given value is not nil.
func (_c *SampleCreate) SetNillableTargetPort(v *int) *SampleCreate {
	if v != nil {
		_c.SetTargetPort(*v)
	}
	return _c
}

// SetSuccess sets the "success" field.
func (_c *SampleCreate) SetSuccess(v bool) *SampleCreate {
	_c.mutation.SetSuccess(v)
	return _c
}

// SetRttMs sets the "rtt_ms" field.
func (_c *SampleCreate) SetRttMs(v float64) *SampleCreate {
	_c.mutation.SetRttMs(v)
	return _c
}

// SetNillableRttMs sets the "rtt_ms" field if the given value is not nil.
func (_c *SampleCreate) SetNillableRttMs(v *float64) *SampleCreate {
	if v != nil {
		_c.SetRttMs(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *SampleCreate) SetError(v string) *SampleCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *SampleCreate) SetNillableError(v *string) *SampleCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// Mutation returns the SampleMutation object of the builder.
func (_c *SampleCreate) Mutation() *SampleMutation {
	return _c.mutation
}

// Save creates the Sample in the database.
func (_c *SampleCreate) Save(ctx context.Context) (*Sample, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SampleCreate) SaveX(ctx context.Context) *Sample {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SampleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SampleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SampleCreate) check() error {
	if _, ok := _c.mutation.TsUnixMs(); !ok {
		return &ValidationError{Name: "ts_unix_ms", err: errors.New(`ent: missing required field "Sample.ts_unix_ms"`)}
	}
	if _, ok := _c.mutation.TargetLabel(); !ok {
		return &ValidationError{Name: "target_label", err: errors.New(`ent: missing required field "Sample.target_label"`)}
	}
	if v, ok := _c.mutation.TargetLabel(); ok {
		if err := sample.TargetLabelValidator(v); err != nil {
			return &ValidationError{Name: "target_label", err: fmt.Errorf(`ent: validator failed for field "Sample.target_label": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetKind(); !ok {
		return &ValidationError{Name: "target_kind", err: errors.New(`ent: missing required field "Sample.target_kind"`)}
	}
	if _, ok := _c.mutation.TargetHost(); !ok {
		return &ValidationError{Name: "target_host", err: errors.New(`ent: missing required field "Sample.target_host"`)}
	}
	if _, ok := _c.mutation.Success(); !ok {
		return &ValidationError{Name: "success", err: errors.New(`ent: missing required field "Sample.success"`)}
	}
	return nil
}

func (_c *SampleCreate) sqlSave(ctx context.Context) (*Sample, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SampleCreate) createSpec() (*Sample, *sqlgraph.CreateSpec) {
	var (
		_node = &Sample{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sample.Table, sqlgraph.NewFieldSpec(sample.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TsUnixMs(); ok {
		_spec.SetField(sample.FieldTsUnixMs, field.TypeInt64, value)
		_node.TsUnixMs = value
	}
	if value, ok := _c.mutation.TargetLabel(); ok {
		_spec.SetField(sample.FieldTargetLabel, field.TypeString, value)
		_node.TargetLabel = value
	}
	if value, ok := _c.mutation.TargetKind(); ok {
		_spec.SetField(sample.FieldTargetKind, field.TypeString, value)
		_node.TargetKind = value
	}
	if value, ok := _c.mutation.TargetHost(); ok {
		_spec.SetField(sample.FieldTargetHost, field.TypeString, value)
		_node.TargetHost = value
	}
	if value, ok := _c.mutation.TargetPort(); ok {
		_spec.SetField(sample.FieldTargetPort, field.TypeInt, value)
		_node.TargetPort = &value
	}
	if value, ok := _c.mutation.Success(); ok {
		_spec.SetField(sample.FieldSuccess, field.TypeBool, value)
		_node.Success = value
	}
	if value, ok := _c.mutation.RttMs(); ok {
		_spec.SetField(sample.FieldRttMs, field.TypeFloat64, value)
		_node.RttMs = &value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(sample.FieldError, field.TypeString, value)
		_node.Error = &value
	}
	return _node, _spec
}

// SampleCreateBulk is the builder for creating many Sample entities in bulk.
type SampleCreateBulk struct {
	config
	err      error
	builders []*SampleCreate
}

// Save creates the Sample entities in the database.
func (_c *SampleCreateBulk) Save(ctx context.Context) ([]*Sample, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Sample, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SampleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SampleCreateBulk) SaveX(ctx context.Context) []*Sample {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SampleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SampleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
