// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/sid-technologies/vigil/db/ent/sample1h"
)

// Sample1h is the model entity for the Sample1h schema.
type Sample1h struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Unix-ms of the 1-hour window start, multiple of 3_600_000
	BucketStartUnixMs int64 `json:"bucket_start_unix_ms,omitempty"`
	// TargetLabel holds the value of the "target_label" field.
	TargetLabel string `json:"target_label,omitempty"`
	// Count holds the value of the "count" field.
	Count int `json:"count,omitempty"`
	// SuccessCount holds the value of the "success_count" field.
	SuccessCount int `json:"success_count,omitempty"`
	// FailCount holds the value of the "fail_count" field.
	FailCount int `json:"fail_count,omitempty"`
	// RttP50Ms holds the value of the "rtt_p50_ms" field.
	RttP50Ms *float64 `json:"rtt_p50_ms,omitempty"`
	// RttP95Ms holds the value of the "rtt_p95_ms" field.
	RttP95Ms *float64 `json:"rtt_p95_ms,omitempty"`
	// RttP99Ms holds the value of the "rtt_p99_ms" field.
	RttP99Ms *float64 `json:"rtt_p99_ms,omitempty"`
	// RttMaxMs holds the value of the "rtt_max_ms" field.
	RttMaxMs *float64 `json:"rtt_max_ms,omitempty"`
	// RttMeanMs holds the value of the "rtt_mean_ms" field.
	RttMeanMs *float64 `json:"rtt_mean_ms,omitempty"`
	// JitterMs holds the value of the "jitter_ms" field.
	JitterMs *float64 `json:"jitter_ms,omitempty"`
	// Errors holds the value of the "errors" field.
	Errors       map[string]int `json:"errors,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Sample1h) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sample1h.FieldErrors:
			values[i] = new([]byte)
		case sample1h.FieldRttP50Ms, sample1h.FieldRttP95Ms, sample1h.FieldRttP99Ms, sample1h.FieldRttMaxMs, sample1h.FieldRttMeanMs, sample1h.FieldJitterMs:
			values[i] = new(sql.NullFloat64)
		case sample1h.FieldID, sample1h.FieldBucketStartUnixMs, sample1h.FieldCount, sample1h.FieldSuccessCount, sample1h.FieldFailCount:
			values[i] = new(sql.NullInt64)
		case sample1h.FieldTargetLabel:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Sample1h fields.
func (_m *Sample1h) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sample1h.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case sample1h.FieldBucketStartUnixMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bucket_start_unix_ms", values[i])
			} else if value.Valid {
				_m.BucketStartUnixMs = value.Int64
			}
		case sample1h.FieldTargetLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_label", values[i])
			} else if value.Valid {
				_m.TargetLabel = value.String
			}
		case sample1h.FieldCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field count", values[i])
			} else if value.Valid {
				_m.Count = int(value.Int64)
			}
		case sample1h.FieldSuccessCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field success_count", values[i])
			} else if value.Valid {
				_m.SuccessCount = int(value.Int64)
			}
		case sample1h.FieldFailCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field fail_count", values[i])
			} else if value.Valid {
				_m.FailCount = int(value.Int64)
			}
		case sample1h.FieldRttP50Ms:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rtt_p50_ms", values[i])
			} else if value.Valid {
				_m.RttP50Ms = new(float64)
				*_m.RttP50Ms = value.Float64
			}
		case sample1h.FieldRttP95Ms:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rtt_p95_ms", values[i])
			} else if value.Valid {
				_m.RttP95Ms = new(float64)
				*_m.RttP95Ms = value.Float64
			}
		case sample1h.FieldRttP99Ms:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rtt_p99_ms", values[i])
			} else if value.Valid {
				_m.RttP99Ms = new(float64)
				*_m.RttP99Ms = value.Float64
			}
		case sample1h.FieldRttMaxMs:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rtt_max_ms", values[i])
			} else if value.Valid {
				_m.RttMaxMs = new(float64)
				*_m.RttMaxMs = value.Float64
			}
		case sample1h.FieldRttMeanMs:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rtt_mean_ms", values[i])
			} else if value.Valid {
				_m.RttMeanMs = new(float64)
				*_m.RttMeanMs = value.Float64
			}
		case sample1h.FieldJitterMs:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field jitter_ms", values[i])
			} else if value.Valid {
				_m.JitterMs = new(float64)
				*_m.JitterMs = value.Float64
			}
		case sample1h.FieldErrors:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field errors", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Errors); err != nil {
					return fmt.Errorf("unmarshal field errors: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Sample1h.
// This includes values selected through modifiers, order, etc.
func (_m *Sample1h) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Sample1h.
// Note that you need to call Sample1h.Unwrap() before calling this method if this Sample1h
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Sample1h) Update() *Sample1hUpdateOne {
	return NewSample1hClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Sample1h entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Sample1h) Unwrap() *Sample1h {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Sample1h is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Sample1h) String() string {
	var builder strings.Builder
	builder.WriteString("Sample1h(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("bucket_start_unix_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.BucketStartUnixMs))
	builder.WriteString(", ")
	builder.WriteString("target_label=")
	builder.WriteString(_m.TargetLabel)
	builder.WriteString(", ")
	builder.WriteString("count=")
	builder.WriteString(fmt.Sprintf("%v", _m.Count))
	builder.WriteString(", ")
	builder.WriteString("success_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SuccessCount))
	builder.WriteString(", ")
	builder.WriteString("fail_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.FailCount))
	builder.WriteString(", ")
	if v := _m.RttP50Ms; v != nil {
		builder.WriteString("rtt_p50_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RttP95Ms; v != nil {
		builder.WriteString("rtt_p95_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RttP99Ms; v != nil {
		builder.WriteString("rtt_p99_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RttMaxMs; v != nil {
		builder.WriteString("rtt_max_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RttMeanMs; v != nil {
		builder.WriteString("rtt_mean_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.JitterMs; v != nil {
		builder.WriteString("jitter_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("errors=")
	builder.WriteString(fmt.Sprintf("%v", _m.Errors))
	builder.WriteByte(')')
	return builder.String()
}

// Sample1hs is a parsable slice of Sample1h.
type Sample1hs []*Sample1h
