// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sid-technologies/vigil/db/ent/predicate"
	"github.com/sid-technologies/vigil/db/ent/sample5min"
)

// Sample5minDelete is the builder for deleting a Sample5min entity.
type Sample5minDelete struct {
	config
	hooks    []Hook
	mutation *Sample5minMutation
}

// Where appends a list predicates to the Sample5minDelete builder.
func (_d *Sample5minDelete) Where(ps ...predicate.Sample5min) *Sample5minDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *Sample5minDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *Sample5minDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *Sample5minDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(sample5min.Table, sqlgraph.NewFieldSpec(sample5min.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// Sample5minDeleteOne is the builder for deleting a single Sample5min entity.
type Sample5minDeleteOne struct {
	_d *Sample5minDelete
}

// Where appends a list predicates to the Sample5minDelete builder.
func (_d *Sample5minDeleteOne) Where(ps ...predicate.Sample5min) *Sample5minDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *Sample5minDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{sample5min.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *Sample5minDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
