// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sid-technologies/vigil/db/ent/predicate"
	"github.com/sid-technologies/vigil/db/ent/sample"
)

// SampleUpdate is the builder for updating Sample entities.
type SampleUpdate struct {
	config
	hooks    []Hook
	mutation *SampleMutation
}

// Where appends a list predicates to the SampleUpdate builder.
func (_u *SampleUpdate) Where(ps ...predicate.Sample) *SampleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTsUnixMs sets the "ts_unix_ms" field.
func (_u *SampleUpdate) SetTsUnixMs(v int64) *SampleUpdate {
	_u.mutation.ResetTsUnixMs()
	_u.mutation.SetTsUnixMs(v)
	return _u
}

// SetNillableTsUnixMs sets the "ts_unix_ms" field if the given value is not nil.
func (_u *SampleUpdate) SetNillableTsUnixMs(v *int64) *SampleUpdate {
	if v != nil {
		_u.SetTsUnixMs(*v)
	}
	return _u
}

// AddTsUnixMs adds value to the "ts_unix_ms" field.
func (_u *SampleUpdate) AddTsUnixMs(v int64) *SampleUpdate {
	_u.mutation.AddTsUnixMs(v)
	return _u
}

// SetTargetLabel sets the "target_label" field.
func (_u *SampleUpdate) SetTargetLabel(v string) *SampleUpdate {
	_u.mutation.SetTargetLabel(v)
	return _u
}

// SetNillableTargetLabel sets the "target_label" field if the given value is not nil.
func (_u *SampleUpdate) SetNillableTargetLabel(v *string) *SampleUpdate {
	if v != nil {
		_u.SetTargetLabel(*v)
	}
	return _u
}

// SetTargetKind sets the "target_kind" field.
func (_u *SampleUpdate) SetTargetKind(v string) *SampleUpdate {
	_u.mutation.SetTargetKind(v)
	return _u
}

// SetNillableTargetKind sets the "target_kind" field if the given value is not nil.
func (_u *SampleUpdate) SetNillableTargetKind(v *string) *SampleUpdate {
	if v != nil {
		_u.SetTargetKind(*v)
	}
	return _u
}

// SetTargetHost sets the "target_host" field.
func (_u *SampleUpdate) SetTargetHost(v string) *SampleUpdate {
	_u.mutation.SetTargetHost(v)
	return _u
}

// SetNillableTargetHost sets the "target_host" field if the given value is not nil.
func (_u *SampleUpdate) SetNillableTargetHost(v *string) *SampleUpdate {
	if v != nil {
		_u.SetTargetHost(*v)
	}
	return _u
}

// SetTargetPort sets the "target_port" field.
func (_u *SampleUpdate) SetTargetPort(v int) *SampleUpdate {
	_u.mutation.ResetTargetPort()
	_u.mutation.SetTargetPort(v)
	return _u
}

// SetNillableTargetPort sets the "target_port" field if the given value is not nil.
func (_u *SampleUpdate) SetNillableTargetPort(v *int) *SampleUpdate {
	if v != nil {
		_u.SetTargetPort(*v)
	}
	return _u
}

// AddTargetPort adds value to the "target_port" field.
func (_u *SampleUpdate) AddTargetPort(v int) *SampleUpdate {
	_u.mutation.AddTargetPort(v)
	return _u
}

// ClearTargetPort clears the value of the "target_port" field.
func (_u *SampleUpdate) ClearTargetPort() *SampleUpdate {
	_u.mutation.ClearTargetPort()
	return _u
}

// SetSuccess sets the "success" field.
func (_u *SampleUpdate) SetSuccess(v bool) *SampleUpdate {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *SampleUpdate) SetNillableSuccess(v *bool) *SampleUpdate {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// SetRttMs sets the "rtt_ms" field.
func (_u *SampleUpdate) SetRttMs(v float64) *SampleUpdate {
	_u.mutation.ResetRttMs()
	_u.mutation.SetRttMs(v)
	return _u
}

// SetNillableRttMs sets the "rtt_ms" field if the given value is not nil.
func (_u *SampleUpdate) SetNillableRttMs(v *float64) *SampleUpdate {
	if v != nil {
		_u.SetRttMs(*v)
	}
	return _u
}

// AddRttMs adds value to the "rtt_ms" field.
func (_u *SampleUpdate) AddRttMs(v float64) *SampleUpdate {
	_u.mutation.AddRttMs(v)
	return _u
}

// ClearRttMs clears the value of the "rtt_ms" field.
func (_u *SampleUpdate) ClearRttMs() *SampleUpdate {
	_u.mutation.ClearRttMs()
	return _u
}

// SetError sets the "error" field.
func (_u *SampleUpdate) SetError(v string) *SampleUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *SampleUpdate) SetNillableError(v *string) *SampleUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *SampleUpdate) ClearError() *SampleUpdate {
	_u.mutation.ClearError()
	return _u
}

// Mutation returns the SampleMutation object of the builder.
func (_u *SampleUpdate) Mutation() *SampleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SampleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SampleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SampleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SampleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SampleUpdate) check() error {
	if v, ok := _u.mutation.TargetLabel(); ok {
		if err := sample.TargetLabelValidator(v); err != nil {
			return &ValidationError{Name: "target_label", err: fmt.Errorf(`ent: validator failed for field "Sample.target_label": %w`, err)}
		}
	}
	return nil
}

func (_u *SampleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sample.Table, sample.Columns, sqlgraph.NewFieldSpec(sample.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TsUnixMs(); ok {
		_spec.SetField(sample.FieldTsUnixMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTsUnixMs(); ok {
		_spec.AddField(sample.FieldTsUnixMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TargetLabel(); ok {
		_spec.SetField(sample.FieldTargetLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetKind(); ok {
		_spec.SetField(sample.FieldTargetKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetHost(); ok {
		_spec.SetField(sample.FieldTargetHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetPort(); ok {
		_spec.SetField(sample.FieldTargetPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTargetPort(); ok {
		_spec.AddField(sample.FieldTargetPort, field.TypeInt, value)
	}
	if _u.mutation.TargetPortCleared() {
		_spec.ClearField(sample.FieldTargetPort, field.TypeInt)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(sample.FieldSuccess, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RttMs(); ok {
		_spec.SetField(sample.FieldRttMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRttMs(); ok {
		_spec.AddField(sample.FieldRttMs, field.TypeFloat64, value)
	}
	if _u.mutation.RttMsCleared() {
		_spec.ClearField(sample.FieldRttMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(sample.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(sample.FieldError, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sample.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SampleUpdateOne is the builder for updating a single Sample entity.
type SampleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SampleMutation
}

// SetTsUnixMs sets the "ts_unix_ms" field.
func (_u *SampleUpdateOne) SetTsUnixMs(v int64) *SampleUpdateOne {
	_u.mutation.ResetTsUnixMs()
	_u.mutation.SetTsUnixMs(v)
	return _u
}

// SetNillableTsUnixMs sets the "ts_unix_ms" field if the given value is not nil.
func (_u *SampleUpdateOne) SetNillableTsUnixMs(v *int64) *SampleUpdateOne {
	if v != nil {
		_u.SetTsUnixMs(*v)
	}
	return _u
}

// AddTsUnixMs adds value to the "ts_unix_ms" field.
func (_u *SampleUpdateOne) AddTsUnixMs(v int64) *SampleUpdateOne {
	_u.mutation.AddTsUnixMs(v)
	return _u
}

// SetTargetLabel sets the "target_label" field.
func (_u *SampleUpdateOne) SetTargetLabel(v string) *SampleUpdateOne {
	_u.mutation.SetTargetLabel(v)
	return _u
}

// SetNillableTargetLabel sets the "target_label" field if the given value is not nil.
func (_u *SampleUpdateOne) SetNillableTargetLabel(v *string) *SampleUpdateOne {
	if v != nil {
		_u.SetTargetLabel(*v)
	}
	return _u
}

// SetTargetKind sets the "target_kind" field.
func (_u *SampleUpdateOne) SetTargetKind(v string) *SampleUpdateOne {
	_u.mutation.SetTargetKind(v)
	return _u
}

// SetNillableTargetKind sets the "target_kind" field if the given value is not nil.
func (_u *SampleUpdateOne) SetNillableTargetKind(v *string) *SampleUpdateOne {
	if v != nil {
		_u.SetTargetKind(*v)
	}
	return _u
}

// SetTargetHost sets the "target_host" field.
func (_u *SampleUpdateOne) SetTargetHost(v string) *SampleUpdateOne {
	_u.mutation.SetTargetHost(v)
	return _u
}

// SetNillableTargetHost sets the "target_host" field if the given value is not nil.
func (_u *SampleUpdateOne) SetNillableTargetHost(v *string) *SampleUpdateOne {
	if v != nil {
		_u.SetTargetHost(*v)
	}
	return _u
}

// SetTargetPort sets the "target_port" field.
func (_u *SampleUpdateOne) SetTargetPort(v int) *SampleUpdateOne {
	_u.mutation.ResetTargetPort()
	_u.mutation.SetTargetPort(v)
	return _u
}

// SetNillableTargetPort sets the "target_port" field if the given value is not nil.
func (_u *SampleUpdateOne) SetNillableTargetPort(v *int) *SampleUpdateOne {
	if v != nil {
		_u.SetTargetPort(*v)
	}
	return _u
}

// AddTargetPort adds value to the "target_port" field.
func (_u *SampleUpdateOne) AddTargetPort(v int) *SampleUpdateOne {
	_u.mutation.AddTargetPort(v)
	return _u
}

// ClearTargetPort clears the value of the "target_port" field.
func (_u *SampleUpdateOne) ClearTargetPort() *SampleUpdateOne {
	_u.mutation.ClearTargetPort()
	return _u
}

// SetSuccess sets the "success" field.
func (_u *SampleUpdateOne) SetSuccess(v bool) *SampleUpdateOne {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *SampleUpdateOne) SetNillableSuccess(v *bool) *SampleUpdateOne {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// SetRttMs sets the "rtt_ms" field.
func (_u *SampleUpdateOne) SetRttMs(v float64) *SampleUpdateOne {
	_u.mutation.ResetRttMs()
	_u.mutation.SetRttMs(v)
	return _u
}

// SetNillableRttMs sets the "rtt_ms" field if the given value is not nil.
func (_u *SampleUpdateOne) SetNillableRttMs(v *float64) *SampleUpdateOne {
	if v != nil {
		_u.SetRttMs(*v)
	}
	return _u
}

// AddRttMs adds value to the "rtt_ms" field.
func (_u *SampleUpdateOne) AddRttMs(v float64) *SampleUpdateOne {
	_u.mutation.AddRttMs(v)
	return _u
}

// ClearRttMs clears the value of the "rtt_ms" field.
func (_u *SampleUpdateOne) ClearRttMs() *SampleUpdateOne {
	_u.mutation.ClearRttMs()
	return _u
}

// SetError sets the "error" field.
func (_u *SampleUpdateOne) SetError(v string) *SampleUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *SampleUpdateOne) SetNillableError(v *string) *SampleUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *SampleUpdateOne) ClearError() *SampleUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// Mutation returns the SampleMutation object of the builder.
func (_u *SampleUpdateOne) Mutation() *SampleMutation {
	return _u.mutation
}

// Where appends a list predicates to the SampleUpdate builder.
func (_u *SampleUpdateOne) Where(ps ...predicate.Sample) *SampleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SampleUpdateOne) Select(field string, fields ...string) *SampleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Sample entity.
func (_u *SampleUpdateOne) Save(ctx context.Context) (*Sample, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SampleUpdateOne) SaveX(ctx context.Context) *Sample {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SampleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SampleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SampleUpdateOne) check() error {
	if v, ok := _u.mutation.TargetLabel(); ok {
		if err := sample.TargetLabelValidator(v); err != nil {
			return &ValidationError{Name: "target_label", err: fmt.Errorf(`ent: validator failed for field "Sample.target_label": %w`, err)}
		}
	}
	return nil
}

func (_u *SampleUpdateOne) sqlSave(ctx context.Context) (_node *Sample, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sample.Table, sample.Columns, sqlgraph.NewFieldSpec(sample.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Sample.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sample.FieldID)
		for _, f := range fields {
			if !sample.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sample.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TsUnixMs(); ok {
		_spec.SetField(sample.FieldTsUnixMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTsUnixMs(); ok {
		_spec.AddField(sample.FieldTsUnixMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TargetLabel(); ok {
		_spec.SetField(sample.FieldTargetLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetKind(); ok {
		_spec.SetField(sample.FieldTargetKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetHost(); ok {
		_spec.SetField(sample.FieldTargetHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetPort(); ok {
		_spec.SetField(sample.FieldTargetPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTargetPort(); ok {
		_spec.AddField(sample.FieldTargetPort, field.TypeInt, value)
	}
	if _u.mutation.TargetPortCleared() {
		_spec.ClearField(sample.FieldTargetPort, field.TypeInt)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(sample.FieldSuccess, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RttMs(); ok {
		_spec.SetField(sample.FieldRttMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRttMs(); ok {
		_spec.AddField(sample.FieldRttMs, field.TypeFloat64, value)
	}
	if _u.mutation.RttMsCleared() {
		_spec.ClearField(sample.FieldRttMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(sample.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(sample.FieldError, field.TypeString)
	}
	_node = &Sample{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sample.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
