// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/sid-technologies/vigil/db/ent/sample"
)

// Sample is the model entity for the Sample schema.
type Sample struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Probe timestamp, milliseconds since unix epoch
	TsUnixMs int64 `json:"ts_unix_ms,omitempty"`
	// TargetLabel holds the value of the "target_label" field.
	TargetLabel string `json:"target_label,omitempty"`
	// TargetKind holds the value of the "target_kind" field.
	TargetKind string `json:"target_kind,omitempty"`
	// TargetHost holds the value of the "target_host" field.
	TargetHost string `json:"target_host,omitempty"`
	// TargetPort holds the value of the "target_port" field.
	TargetPort *int `json:"target_port,omitempty"`
	// Success holds the value of the "success" field.
	Success bool `json:"success,omitempty"`
	// Round-trip time, only set when success=true
	RttMs *float64 `json:"rtt_ms,omitempty"`
	// Stable machine-readable error code: timeout, host_unreachable, dns, conn_refused, etc.
	Error        *string `json:"error,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Sample) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sample.FieldSuccess:
			values[i] = new(sql.NullBool)
		case sample.FieldRttMs:
			values[i] = new(sql.NullFloat64)
		case sample.FieldID, sample.FieldTsUnixMs, sample.FieldTargetPort:
			values[i] = new(sql.NullInt64)
		case sample.FieldTargetLabel, sample.FieldTargetKind, sample.FieldTargetHost, sample.FieldError:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Sample fields.
func (_m *Sample) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sample.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case sample.FieldTsUnixMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ts_unix_ms", values[i])
			} else if value.Valid {
				_m.TsUnixMs = value.Int64
			}
		case sample.FieldTargetLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_label", values[i])
			} else if value.Valid {
				_m.TargetLabel = value.String
			}
		case sample.FieldTargetKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_kind", values[i])
			} else if value.Valid {
				_m.TargetKind = value.String
			}
		case sample.FieldTargetHost:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_host", values[i])
			} else if value.Valid {
				_m.TargetHost = value.String
			}
		case sample.FieldTargetPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field target_port", values[i])
			} else if value.Valid {
				_m.TargetPort = new(int)
				*_m.TargetPort = int(value.Int64)
			}
		case sample.FieldSuccess:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field success", values[i])
			} else if value.Valid {
				_m.Success = value.Bool
			}
		case sample.FieldRttMs:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rtt_ms", values[i])
			} else if value.Valid {
				_m.RttMs = new(float64)
				*_m.RttMs = value.Float64
			}
		case sample.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = new(string)
				*_m.Error = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Sample.
// This includes values selected through modifiers, order, etc.
func (_m *Sample) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Sample.
// Note that you need to call Sample.Unwrap() before calling this method if this Sample
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Sample) Update() *SampleUpdateOne {
	return NewSampleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Sample entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Sample) Unwrap() *Sample {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Sample is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Sample) String() string {
	var builder strings.Builder
	builder.WriteString("Sample(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ts_unix_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.TsUnixMs))
	builder.WriteString(", ")
	builder.WriteString("target_label=")
	builder.WriteString(_m.TargetLabel)
	builder.WriteString(", ")
	builder.WriteString("target_kind=")
	builder.WriteString(_m.TargetKind)
	builder.WriteString(", ")
	builder.WriteString("target_host=")
	builder.WriteString(_m.TargetHost)
	builder.WriteString(", ")
	if v := _m.TargetPort; v != nil {
		builder.WriteString("target_port=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("success=")
	builder.WriteString(fmt.Sprintf("%v", _m.Success))
	builder.WriteString(", ")
	if v := _m.RttMs; v != nil {
		builder.WriteString("rtt_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Error; v != nil {
		builder.WriteString("error=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// Samples is a parsable slice of Sample.
type Samples []*Sample
