// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sid-technologies/vigil/db/ent/sample1h"
)

// Sample1hCreate is the builder for creating a Sample1h entity.
type Sample1hCreate struct {
	config
	mutation *Sample1hMutation
	hooks    []Hook
}

// SetBucketStartUnixMs sets the "bucket_start_unix_ms" field.
func (_c *Sample1hCreate) SetBucketStartUnixMs(v int64) *Sample1hCreate {
	_c.mutation.SetBucketStartUnixMs(v)
	return _c
}

// SetTargetLabel sets the "target_label" field.
func (_c *Sample1hCreate) SetTargetLabel(v string) *Sample1hCreate {
	_c.mutation.SetTargetLabel(v)
	return _c
}

// SetCount sets the "count" field.
func (_c *Sample1hCreate) SetCount(v int) *Sample1hCreate {
	_c.mutation.SetCount(v)
	return _c
}

// SetSuccessCount sets the "success_count" field.
func (_c *Sample1hCreate) SetSuccessCount(v int) *Sample1hCreate {
	_c.mutation.SetSuccessCount(v)
	return _c
}

// SetFailCount sets the "fail_count" field.
func (_c *Sample1hCreate) SetFailCount(v int) *Sample1hCreate {
	_c.mutation.SetFailCount(v)
	return _c
}

// SetRttP50Ms sets the "rtt_p50_ms" field.
func (_c *Sample1hCreate) SetRttP50Ms(v float64) *Sample1hCreate {
	_c.mutation.SetRttP50Ms(v)
	return _c
}

// SetNillableRttP50Ms sets the "rtt_p50_ms" field if the given value is not nil.
func (_c *Sample1hCreate) SetNillableRttP50Ms(v *float64) *Sample1hCreate {
	if v != nil {
		_c.SetRttP50Ms(*v)
	}
	return _c
}

// SetRttP95Ms sets the "rtt_p95_ms" field.
func (_c *Sample1hCreate) SetRttP95Ms(v float64) *Sample1hCreate {
	_c.mutation.SetRttP95Ms(v)
	return _c
}

// SetNillableRttP95Ms sets the "rtt_p95_ms" field if the given value is not nil.
func (_c *Sample1hCreate) SetNillableRttP95Ms(v *float64) *Sample1hCreate {
	if v != nil {
		_c.SetRttP95Ms(*v)
	}
	return _c
}

// SetRttP99Ms sets the "rtt_p99_ms" field.
func (_c *Sample1hCreate) SetRttP99Ms(v float64) *Sample1hCreate {
	_c.mutation.SetRttP99Ms(v)
	return _c
}

// SetNillableRttP99Ms sets the "rtt_p99_ms" field if the given value is not nil.
func (_c *Sample1hCreate) SetNillableRttP99Ms(v *float64) *Sample1hCreate {
	if v != nil {
		_c.SetRttP99Ms(*v)
	}
	return _c
}

// SetRttMaxMs sets the "rtt_max_ms" field.
func (_c *Sample1hCreate) SetRttMaxMs(v float64) *Sample1hCreate {
	_c.mutation.SetRttMaxMs(v)
	return _c
}

// SetNillableRttMaxMs sets the "rtt_max_ms" field if the given value is not nil.
func (_c *Sample1hCreate) SetNillableRttMaxMs(v *float64) *Sample1hCreate {
	if v != nil {
		_c.SetRttMaxMs(*v)
	}
	return _c
}

// SetRttMeanMs sets the "rtt_mean_ms" field.
func (_c *Sample1hCreate) SetRttMeanMs(v float64) *Sample1hCreate {
	_c.mutation.SetRttMeanMs(v)
	return _c
}

// SetNillableRttMeanMs sets the "rtt_mean_ms" field if the given value is not nil.
func (_c *Sample1hCreate) SetNillableRttMeanMs(v *float64) *Sample1hCreate {
	if v != nil {
		_c.SetRttMeanMs(*v)
	}
	return _c
}

// SetJitterMs sets the "jitter_ms" field.
func (_c *Sample1hCreate) SetJitterMs(v float64) *Sample1hCreate {
	_c.mutation.SetJitterMs(v)
	return _c
}

// SetNillableJitterMs sets the "jitter_ms" field if the given value is not nil.
func (_c *Sample1hCreate) SetNillableJitterMs(v *float64) *Sample1hCreate {
	if v != nil {
		_c.SetJitterMs(*v)
	}
	return _c
}

// SetErrors sets the "errors" field.
func (_c *Sample1hCreate) SetErrors(v map[string]int) *Sample1hCreate {
	_c.mutation.SetErrors(v)
	return _c
}

// Mutation returns the Sample1hMutation object of the builder.
func (_c *Sample1hCreate) Mutation() *Sample1hMutation {
	return _c.mutation
}

// Save creates the Sample1h in the database.
func (_c *Sample1hCreate) Save(ctx context.Context) (*Sample1h, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *Sample1hCreate) SaveX(ctx context.Context) *Sample1h {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *Sample1hCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *Sample1hCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *Sample1hCreate) check() error {
	if _, ok := _c.mutation.BucketStartUnixMs(); !ok {
		return &ValidationError{Name: "bucket_start_unix_ms", err: errors.New(`ent: missing required field "Sample1h.bucket_start_unix_ms"`)}
	}
	if _, ok := _c.mutation.TargetLabel(); !ok {
		return &ValidationError{Name: "target_label", err: errors.New(`ent: missing required field "Sample1h.target_label"`)}
	}
	if v, ok := _c.mutation.TargetLabel(); ok {
		if err := sample1h.TargetLabelValidator(v); err != nil {
			return &ValidationError{Name: "target_label", err: fmt.Errorf(`ent: validator failed for field "Sample1h.target_label": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Count(); !ok {
		return &ValidationError{Name: "count", err: errors.New(`ent: missing required field "Sample1h.count"`)}
	}
	if _, ok := _c.mutation.SuccessCount(); !ok {
		return &ValidationError{Name: "success_count", err: errors.New(`ent: missing required field "Sample1h.success_count"`)}
	}
	if _, ok := _c.mutation.FailCount(); !ok {
		return &ValidationError{Name: "fail_count", err: errors.New(`ent: missing required field "Sample1h.fail_count"`)}
	}
	return nil
}

func (_c *Sample1hCreate) sqlSave(ctx context.Context) (*Sample1h, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *Sample1hCreate) createSpec() (*Sample1h, *sqlgraph.CreateSpec) {
	var (
		_node = &Sample1h{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sample1h.Table, sqlgraph.NewFieldSpec(sample1h.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.BucketStartUnixMs(); ok {
		_spec.SetField(sample1h.FieldBucketStartUnixMs, field.TypeInt64, value)
		_node.BucketStartUnixMs = value
	}
	if value, ok := _c.mutation.TargetLabel(); ok {
		_spec.SetField(sample1h.FieldTargetLabel, field.TypeString, value)
		_node.TargetLabel = value
	}
	if value, ok := _c.mutation.Count(); ok {
		_spec.SetField(sample1h.FieldCount, field.TypeInt, value)
		_node.Count = value
	}
	if value, ok := _c.mutation.SuccessCount(); ok {
		_spec.SetField(sample1h.FieldSuccessCount, field.TypeInt, value)
		_node.SuccessCount = value
	}
	if value, ok := _c.mutation.FailCount(); ok {
		_spec.SetField(sample1h.FieldFailCount, field.TypeInt, value)
		_node.FailCount = value
	}
	if value, ok := _c.mutation.RttP50Ms(); ok {
		_spec.SetField(sample1h.FieldRttP50Ms, field.TypeFloat64, value)
		_node.RttP50Ms = &value
	}
	if value, ok := _c.mutation.RttP95Ms(); ok {
		_spec.SetField(sample1h.FieldRttP95Ms, field.TypeFloat64, value)
		_node.RttP95Ms = &value
	}
	if value, ok := _c.mutation.RttP99Ms(); ok {
		_spec.SetField(sample1h.FieldRttP99Ms, field.TypeFloat64, value)
		_node.RttP99Ms = &value
	}
	if value, ok := _c.mutation.RttMaxMs(); ok {
		_spec.SetField(sample1h.FieldRttMaxMs, field.TypeFloat64, value)
		_node.RttMaxMs = &value
	}
	if value, ok := _c.mutation.RttMeanMs(); ok {
		_spec.SetField(sample1h.FieldRttMeanMs, field.TypeFloat64, value)
		_node.RttMeanMs = &value
	}
	if value, ok := _c.mutation.JitterMs(); ok {
		_spec.SetField(sample1h.FieldJitterMs, field.TypeFloat64, value)
		_node.JitterMs = &value
	}
	if value, ok := _c.mutation.Errors(); ok {
		_spec.SetField(sample1h.FieldErrors, field.TypeJSON, value)
		_node.Errors = value
	}
	return _node, _spec
}

// Sample1hCreateBulk is the builder for creating many Sample1h entities in bulk.
type Sample1hCreateBulk struct {
	config
	err      error
	builders []*Sample1hCreate
}

// Save creates the Sample1h entities in the database.
func (_c *Sample1hCreateBulk) Save(ctx context.Context) ([]*Sample1h, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Sample1h, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*Sample1hMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *Sample1hCreateBulk) SaveX(ctx context.Context) []*Sample1h {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *Sample1hCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *Sample1hCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
