// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sid-technologies/vigil/db/ent/predicate"
	"github.com/sid-technologies/vigil/db/ent/target"
)

// TargetUpdate is the builder for updating Target entities.
type TargetUpdate struct {
	config
	hooks    []Hook
	mutation *TargetMutation
}

// Where appends a list predicates to the TargetUpdate builder.
func (_u *TargetUpdate) Where(ps ...predicate.Target) *TargetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLabel sets the "label" field.
func (_u *TargetUpdate) SetLabel(v string) *TargetUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *TargetUpdate) SetNillableLabel(v *string) *TargetUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *TargetUpdate) SetKind(v target.Kind) *TargetUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *TargetUpdate) SetNillableKind(v *target.Kind) *TargetUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *TargetUpdate) SetHost(v string) *TargetUpdate {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *TargetUpdate) SetNillableHost(v *string) *TargetUpdate {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetPort sets the "port" field.
func (_u *TargetUpdate) SetPort(v int) *TargetUpdate {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *TargetUpdate) SetNillablePort(v *int) *TargetUpdate {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *TargetUpdate) AddPort(v int) *TargetUpdate {
	_u.mutation.AddPort(v)
	return _u
}

// ClearPort clears the value of the "port" field.
func (_u *TargetUpdate) ClearPort() *TargetUpdate {
	_u.mutation.ClearPort()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *TargetUpdate) SetEnabled(v bool) *TargetUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *TargetUpdate) SetNillableEnabled(v *bool) *TargetUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TargetUpdate) SetUpdatedAt(v time.Time) *TargetUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TargetMutation object of the builder.
func (_u *TargetUpdate) Mutation() *TargetMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TargetUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TargetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TargetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TargetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TargetUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := target.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TargetUpdate) check() error {
	if v, ok := _u.mutation.Label(); ok {
		if err := target.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "Target.label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := target.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Target.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Host(); ok {
		if err := target.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "Target.host": %w`, err)}
		}
	}
	return nil
}

func (_u *TargetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(target.Table, target.Columns, sqlgraph.NewFieldSpec(target.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(target.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(target.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(target.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(target.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(target.FieldPort, field.TypeInt, value)
	}
	if _u.mutation.PortCleared() {
		_spec.ClearField(target.FieldPort, field.TypeInt)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(target.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(target.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{target.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TargetUpdateOne is the builder for updating a single Target entity.
type TargetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TargetMutation
}

// SetLabel sets the "label" field.
func (_u *TargetUpdateOne) SetLabel(v string) *TargetUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *TargetUpdateOne) SetNillableLabel(v *string) *TargetUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *TargetUpdateOne) SetKind(v target.Kind) *TargetUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *TargetUpdateOne) SetNillableKind(v *target.Kind) *TargetUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *TargetUpdateOne) SetHost(v string) *TargetUpdateOne {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *TargetUpdateOne) SetNillableHost(v *string) *TargetUpdateOne {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetPort sets the "port" field.
func (_u *TargetUpdateOne) SetPort(v int) *TargetUpdateOne {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *TargetUpdateOne) SetNillablePort(v *int) *TargetUpdateOne {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *TargetUpdateOne) AddPort(v int) *TargetUpdateOne {
	_u.mutation.AddPort(v)
	return _u
}

// ClearPort clears the value of the "port" field.
func (_u *TargetUpdateOne) ClearPort() *TargetUpdateOne {
	_u.mutation.ClearPort()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *TargetUpdateOne) SetEnabled(v bool) *TargetUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *TargetUpdateOne) SetNillableEnabled(v *bool) *TargetUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TargetUpdateOne) SetUpdatedAt(v time.Time) *TargetUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TargetMutation object of the builder.
func (_u *TargetUpdateOne) Mutation() *TargetMutation {
	return _u.mutation
}

// Where appends a list predicates to the TargetUpdate builder.
func (_u *TargetUpdateOne) Where(ps ...predicate.Target) *TargetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TargetUpdateOne) Select(field string, fields ...string) *TargetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Target entity.
func (_u *TargetUpdateOne) Save(ctx context.Context) (*Target, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TargetUpdateOne) SaveX(ctx context.Context) *Target {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TargetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TargetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TargetUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := target.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TargetUpdateOne) check() error {
	if v, ok := _u.mutation.Label(); ok {
		if err := target.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "Target.label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := target.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Target.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Host(); ok {
		if err := target.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "Target.host": %w`, err)}
		}
	}
	return nil
}

func (_u *TargetUpdateOne) sqlSave(ctx context.Context) (_node *Target, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(target.Table, target.Columns, sqlgraph.NewFieldSpec(target.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Target.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, target.FieldID)
		for _, f := range fields {
			if !target.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != target.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(target.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(target.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(target.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(target.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(target.FieldPort, field.TypeInt, value)
	}
	if _u.mutation.PortCleared() {
		_spec.ClearField(target.FieldPort, field.TypeInt)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(target.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(target.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Target{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{target.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
