// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sid-technologies/vigil/db/ent/target"
)

// TargetCreate is the builder for creating a Target entity.
type TargetCreate struct {
	config
	mutation *TargetMutation
	hooks    []Hook
}

// SetLabel sets the "label" field.
func (_c *TargetCreate) SetLabel(v string) *TargetCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *TargetCreate) SetKind(v target.Kind) *TargetCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetHost sets the "host" field.
func (_c *TargetCreate) SetHost(v string) *TargetCreate {
	_c.mutation.SetHost(v)
	return _c
}

// SetPort sets the "port" field.
func (_c *TargetCreate) SetPort(v int) *TargetCreate {
	_c.mutation.SetPort(v)
	return _c
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_c *TargetCreate) SetNillablePort(v *int) *TargetCreate {
	if v != nil {
		_c.SetPort(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *TargetCreate) SetEnabled(v bool) *TargetCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *TargetCreate) SetNillableEnabled(v *bool) *TargetCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetIsBuiltin sets the "is_builtin" field.
func (_c *TargetCreate) SetIsBuiltin(v bool) *TargetCreate {
	_c.mutation.SetIsBuiltin(v)
	return _c
}

// SetNillableIsBuiltin sets the "is_builtin" field if the given value is not nil.
func (_c *TargetCreate) SetNillableIsBuiltin(v *bool) *TargetCreate {
	if v != nil {
		_c.SetIsBuiltin(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TargetCreate) SetCreatedAt(v time.Time) *TargetCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TargetCreate) SetNillableCreatedAt(v *time.Time) *TargetCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TargetCreate) SetUpdatedAt(v time.Time) *TargetCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TargetCreate) SetNillableUpdatedAt(v *time.Time) *TargetCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TargetCreate) SetID(v string) *TargetCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the TargetMutation object of the builder.
func (_c *TargetCreate) Mutation() *TargetMutation {
	return _c.mutation
}

// Save creates the Target in the database.
func (_c *TargetCreate) Save(ctx context.Context) (*Target, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TargetCreate) SaveX(ctx context.Context) *Target {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TargetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TargetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TargetCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := target.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.IsBuiltin(); !ok {
		v := target.DefaultIsBuiltin
		_c.mutation.SetIsBuiltin(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := target.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := target.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TargetCreate) check() error {
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "Target.label"`)}
	}
	if v, ok := _c.mutation.Label(); ok {
		if err := target.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "Target.label": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Target.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := target.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Target.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Host(); !ok {
		return &ValidationError{Name: "host", err: errors.New(`ent: missing required field "Target.host"`)}
	}
	if v, ok := _c.mutation.Host(); ok {
		if err := target.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "Target.host": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Target.enabled"`)}
	}
	if _, ok := _c.mutation.IsBuiltin(); !ok {
		return &ValidationError{Name: "is_builtin", err: errors.New(`ent: missing required field "Target.is_builtin"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Target.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Target.updated_at"`)}
	}
	return nil
}

func (_c *TargetCreate) sqlSave(ctx context.Context) (*Target, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Target.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TargetCreate) createSpec() (*Target, *sqlgraph.CreateSpec) {
	var (
		_node = &Target{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(target.Table, sqlgraph.NewFieldSpec(target.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(target.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(target.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Host(); ok {
		_spec.SetField(target.FieldHost, field.TypeString, value)
		_node.Host = value
	}
	if value, ok := _c.mutation.Port(); ok {
		_spec.SetField(target.FieldPort, field.TypeInt, value)
		_node.Port = &value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(target.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.IsBuiltin(); ok {
		_spec.SetField(target.FieldIsBuiltin, field.TypeBool, value)
		_node.IsBuiltin = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(target.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(target.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// TargetCreateBulk is the builder for creating many Target entities in bulk.
type TargetCreateBulk struct {
	config
	err      error
	builders []*TargetCreate
}

// Save creates the Target entities in the database.
func (_c *TargetCreateBulk) Save(ctx context.Context) ([]*Target, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Target, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TargetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TargetCreateBulk) SaveX(ctx context.Context) []*Target {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TargetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TargetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
