// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sid-technologies/vigil/db/ent/wifisample"
)

// WifiSampleCreate is the builder for creating a WifiSample entity.
type WifiSampleCreate struct {
	config
	mutation *WifiSampleMutation
	hooks    []Hook
}

// SetTsUnixMs sets the "ts_unix_ms" field.
func (_c *WifiSampleCreate) SetTsUnixMs(v int64) *WifiSampleCreate {
	_c.mutation.SetTsUnixMs(v)
	return _c
}

// SetSsid sets the "ssid" field.
func (_c *WifiSampleCreate) SetSsid(v string) *WifiSampleCreate {
	_c.mutation.SetSsid(v)
	return _c
}

// SetNillableSsid sets the "ssid" field if the given value is not nil.
func (_c *WifiSampleCreate) SetNillableSsid(v *string) *WifiSampleCreate {
	if v != nil {
		_c.SetSsid(*v)
	}
	return _c
}

// SetBssid sets the "bssid" field.
func (_c *WifiSampleCreate) SetBssid(v string) *WifiSampleCreate {
	_c.mutation.SetBssid(v)
	return _c
}

// SetNillableBssid sets the "bssid" field if the given value is not nil.
func (_c *WifiSampleCreate) SetNillableBssid(v *string) *WifiSampleCreate {
	if v != nil {
		_c.SetBssid(*v)
	}
	return _c
}

// SetSignalPercent sets the "signal_percent" field.
func (_c *WifiSampleCreate) SetSignalPercent(v int) *WifiSampleCreate {
	_c.mutation.SetSignalPercent(v)
	return _c
}

// SetNillableSignalPercent sets the "signal_percent" field if the given value is not nil.
func (_c *WifiSampleCreate) SetNillableSignalPercent(v *int) *WifiSampleCreate {
	if v != nil {
		_c.SetSignalPercent(*v)
	}
	return _c
}

// SetRssiDbm sets the "rssi_dbm" field.
func (_c *WifiSampleCreate) SetRssiDbm(v int) *WifiSampleCreate {
	_c.mutation.SetRssiDbm(v)
	return _c
}

// SetNillableRssiDbm sets the "rssi_dbm" field if the given value is not nil.
func (_c *WifiSampleCreate) SetNillableRssiDbm(v *int) *WifiSampleCreate {
	if v != nil {
		_c.SetRssiDbm(*v)
	}
	return _c
}

// SetRxRateMbps sets the "rx_rate_mbps" field.
func (_c *WifiSampleCreate) SetRxRateMbps(v float64) *WifiSampleCreate {
	_c.mutation.SetRxRateMbps(v)
	return _c
}

// SetNillableRxRateMbps sets the "rx_rate_mbps" field if the given value is not nil.
func (_c *WifiSampleCreate) SetNillableRxRateMbps(v *float64) *WifiSampleCreate {
	if v != nil {
		_c.SetRxRateMbps(*v)
	}
	return _c
}

// SetTxRateMbps sets the "tx_rate_mbps" field.
func (_c *WifiSampleCreate) SetTxRateMbps(v float64) *WifiSampleCreate {
	_c.mutation.SetTxRateMbps(v)
	return _c
}

// SetNillableTxRateMbps sets the "tx_rate_mbps" field if the given value is not nil.
func (_c *WifiSampleCreate) SetNillableTxRateMbps(v *float64) *WifiSampleCreate {
	if v != nil {
		_c.SetTxRateMbps(*v)
	}
	return _c
}

// SetChannel sets the "channel" field.
func (_c *WifiSampleCreate) SetChannel(v string) *WifiSampleCreate {
	_c.mutation.SetChannel(v)
	return _c
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_c *WifiSampleCreate) SetNillableChannel(v *string) *WifiSampleCreate {
	if v != nil {
		_c.SetChannel(*v)
	}
	return _c
}

// Mutation returns the WifiSampleMutation object of the builder.
func (_c *WifiSampleCreate) Mutation() *WifiSampleMutation {
	return _c.mutation
}

// Save creates the WifiSample in the database.
func (_c *WifiSampleCreate) Save(ctx context.Context) (*WifiSample, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WifiSampleCreate) SaveX(ctx context.Context) *WifiSample {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WifiSampleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WifiSampleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WifiSampleCreate) check() error {
	if _, ok := _c.mutation.TsUnixMs(); !ok {
		return &ValidationError{Name: "ts_unix_ms", err: errors.New(`ent: missing required field "WifiSample.ts_unix_ms"`)}
	}
	return nil
}

func (_c *WifiSampleCreate) sqlSave(ctx context.Context) (*WifiSample, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WifiSampleCreate) createSpec() (*WifiSample, *sqlgraph.CreateSpec) {
	var (
		_node = &WifiSample{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(wifisample.Table, sqlgraph.NewFieldSpec(wifisample.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TsUnixMs(); ok {
		_spec.SetField(wifisample.FieldTsUnixMs, field.TypeInt64, value)
		_node.TsUnixMs = value
	}
	if value, ok := _c.mutation.Ssid(); ok {
		_spec.SetField(wifisample.FieldSsid, field.TypeString, value)
		_node.Ssid = &value
	}
	if value, ok := _c.mutation.Bssid(); ok {
		_spec.SetField(wifisample.FieldBssid, field.TypeString, value)
		_node.Bssid = &value
	}
	if value, ok := _c.mutation.SignalPercent(); ok {
		_spec.SetField(wifisample.FieldSignalPercent, field.TypeInt, value)
		_node.SignalPercent = &value
	}
	if value, ok := _c.mutation.RssiDbm(); ok {
		_spec.SetField(wifisample.FieldRssiDbm, field.TypeInt, value)
		_node.RssiDbm = &value
	}
	if value, ok := _c.mutation.RxRateMbps(); ok {
		_spec.SetField(wifisample.FieldRxRateMbps, field.TypeFloat64, value)
		_node.RxRateMbps = &value
	}
	if value, ok := _c.mutation.TxRateMbps(); ok {
		_spec.SetField(wifisample.FieldTxRateMbps, field.TypeFloat64, value)
		_node.TxRateMbps = &value
	}
	if value, ok := _c.mutation.Channel(); ok {
		_spec.SetField(wifisample.FieldChannel, field.TypeString, value)
		_node.Channel = &value
	}
	return _node, _spec
}

// WifiSampleCreateBulk is the builder for creating many WifiSample entities in bulk.
type WifiSampleCreateBulk struct {
	config
	err      error
	builders []*WifiSampleCreate
}

// Save creates the WifiSample entities in the database.
func (_c *WifiSampleCreateBulk) Save(ctx context.Context) ([]*WifiSample, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WifiSample, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WifiSampleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WifiSampleCreateBulk) SaveX(ctx context.Context) []*WifiSample {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WifiSampleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WifiSampleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
