// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sid-technologies/vigil/db/ent/predicate"
	"github.com/sid-technologies/vigil/db/ent/wifisample"
)

// WifiSampleUpdate is the builder for updating WifiSample entities.
type WifiSampleUpdate struct {
	config
	hooks    []Hook
	mutation *WifiSampleMutation
}

// Where appends a list predicates to the WifiSampleUpdate builder.
func (_u *WifiSampleUpdate) Where(ps ...predicate.WifiSample) *WifiSampleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTsUnixMs sets the "ts_unix_ms" field.
func (_u *WifiSampleUpdate) SetTsUnixMs(v int64) *WifiSampleUpdate {
	_u.mutation.ResetTsUnixMs()
	_u.mutation.SetTsUnixMs(v)
	return _u
}

// SetNillableTsUnixMs sets the "ts_unix_ms" field if the given value is not nil.
func (_u *WifiSampleUpdate) SetNillableTsUnixMs(v *int64) *WifiSampleUpdate {
	if v != nil {
		_u.SetTsUnixMs(*v)
	}
	return _u
}

// AddTsUnixMs adds value to the "ts_unix_ms" field.
func (_u *WifiSampleUpdate) AddTsUnixMs(v int64) *WifiSampleUpdate {
	_u.mutation.AddTsUnixMs(v)
	return _u
}

// SetSsid sets the "ssid" field.
func (_u *WifiSampleUpdate) SetSsid(v string) *WifiSampleUpdate {
	_u.mutation.SetSsid(v)
	return _u
}

// SetNillableSsid sets the "ssid" field if the given value is not nil.
func (_u *WifiSampleUpdate) SetNillableSsid(v *string) *WifiSampleUpdate {
	if v != nil {
		_u.SetSsid(*v)
	}
	return _u
}

// ClearSsid clears the value of the "ssid" field.
func (_u *WifiSampleUpdate) ClearSsid() *WifiSampleUpdate {
	_u.mutation.ClearSsid()
	return _u
}

// SetBssid sets the "bssid" field.
func (_u *WifiSampleUpdate) SetBssid(v string) *WifiSampleUpdate {
	_u.mutation.SetBssid(v)
	return _u
}

// SetNillableBssid sets the "bssid" field if the given value is not nil.
func (_u *WifiSampleUpdate) SetNillableBssid(v *string) *WifiSampleUpdate {
	if v != nil {
		_u.SetBssid(*v)
	}
	return _u
}

// ClearBssid clears the value of the "bssid" field.
func (_u *WifiSampleUpdate) ClearBssid() *WifiSampleUpdate {
	_u.mutation.ClearBssid()
	return _u
}

// SetSignalPercent sets the "signal_percent" field.
func (_u *WifiSampleUpdate) SetSignalPercent(v int) *WifiSampleUpdate {
	_u.mutation.ResetSignalPercent()
	_u.mutation.SetSignalPercent(v)
	return _u
}

// SetNillableSignalPercent sets the "signal_percent" field if the given value is not nil.
func (_u *WifiSampleUpdate) SetNillableSignalPercent(v *int) *WifiSampleUpdate {
	if v != nil {
		_u.SetSignalPercent(*v)
	}
	return _u
}

// AddSignalPercent adds value to the "signal_percent" field.
func (_u *WifiSampleUpdate) AddSignalPercent(v int) *WifiSampleUpdate {
	_u.mutation.AddSignalPercent(v)
	return _u
}

// ClearSignalPercent clears the value of the "signal_percent" field.
func (_u *WifiSampleUpdate) ClearSignalPercent() *WifiSampleUpdate {
	_u.mutation.ClearSignalPercent()
	return _u
}

// SetRssiDbm sets the "rssi_dbm" field.
func (_u *WifiSampleUpdate) SetRssiDbm(v int) *WifiSampleUpdate {
	_u.mutation.ResetRssiDbm()
	_u.mutation.SetRssiDbm(v)
	return _u
}

// SetNillableRssiDbm sets the "rssi_dbm" field if the given value is not nil.
func (_u *WifiSampleUpdate) SetNillableRssiDbm(v *int) *WifiSampleUpdate {
	if v != nil {
		_u.SetRssiDbm(*v)
	}
	return _u
}

// AddRssiDbm adds value to the "rssi_dbm" field.
func (_u *WifiSampleUpdate) AddRssiDbm(v int) *WifiSampleUpdate {
	_u.mutation.AddRssiDbm(v)
	return _u
}

// ClearRssiDbm clears the value of the "rssi_dbm" field.
func (_u *WifiSampleUpdate) ClearRssiDbm() *WifiSampleUpdate {
	_u.mutation.ClearRssiDbm()
	return _u
}

// SetRxRateMbps sets the "rx_rate_mbps" field.
func (_u *WifiSampleUpdate) SetRxRateMbps(v float64) *WifiSampleUpdate {
	_u.mutation.ResetRxRateMbps()
	_u.mutation.SetRxRateMbps(v)
	return _u
}

// SetNillableRxRateMbps sets the "rx_rate_mbps" field if the given value is not nil.
func (_u *WifiSampleUpdate) SetNillableRxRateMbps(v *float64) *WifiSampleUpdate {
	if v != nil {
		_u.SetRxRateMbps(*v)
	}
	return _u
}

// AddRxRateMbps adds value to the "rx_rate_mbps" field.
func (_u *WifiSampleUpdate) AddRxRateMbps(v float64) *WifiSampleUpdate {
	_u.mutation.AddRxRateMbps(v)
	return _u
}

// ClearRxRateMbps clears the value of the "rx_rate_mbps" field.
func (_u *WifiSampleUpdate) ClearRxRateMbps() *WifiSampleUpdate {
	_u.mutation.ClearRxRateMbps()
	return _u
}

// SetTxRateMbps sets the "tx_rate_mbps" field.
func (_u *WifiSampleUpdate) SetTxRateMbps(v float64) *WifiSampleUpdate {
	_u.mutation.ResetTxRateMbps()
	_u.mutation.SetTxRateMbps(v)
	return _u
}

// SetNillableTxRateMbps sets the "tx_rate_mbps" field if the given value is not nil.
func (_u *WifiSampleUpdate) SetNillableTxRateMbps(v *float64) *WifiSampleUpdate {
	if v != nil {
		_u.SetTxRateMbps(*v)
	}
	return _u
}

// AddTxRateMbps adds value to the "tx_rate_mbps" field.
func (_u *WifiSampleUpdate) AddTxRateMbps(v float64) *WifiSampleUpdate {
	_u.mutation.AddTxRateMbps(v)
	return _u
}

// ClearTxRateMbps clears the value of the "tx_rate_mbps" field.
func (_u *WifiSampleUpdate) ClearTxRateMbps() *WifiSampleUpdate {
	_u.mutation.ClearTxRateMbps()
	return _u
}

// SetChannel sets the "channel" field.
func (_u *WifiSampleUpdate) SetChannel(v string) *WifiSampleUpdate {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *WifiSampleUpdate) SetNillableChannel(v *string) *WifiSampleUpdate {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// ClearChannel clears the value of the "channel" field.
func (_u *WifiSampleUpdate) ClearChannel() *WifiSampleUpdate {
	_u.mutation.ClearChannel()
	return _u
}

// Mutation returns the WifiSampleMutation object of the builder.
func (_u *WifiSampleUpdate) Mutation() *WifiSampleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WifiSampleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WifiSampleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WifiSampleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WifiSampleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WifiSampleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(wifisample.Table, wifisample.Columns, sqlgraph.NewFieldSpec(wifisample.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TsUnixMs(); ok {
		_spec.SetField(wifisample.FieldTsUnixMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTsUnixMs(); ok {
		_spec.AddField(wifisample.FieldTsUnixMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Ssid(); ok {
		_spec.SetField(wifisample.FieldSsid, field.TypeString, value)
	}
	if _u.mutation.SsidCleared() {
		_spec.ClearField(wifisample.FieldSsid, field.TypeString)
	}
	if value, ok := _u.mutation.Bssid(); ok {
		_spec.SetField(wifisample.FieldBssid, field.TypeString, value)
	}
	if _u.mutation.BssidCleared() {
		_spec.ClearField(wifisample.FieldBssid, field.TypeString)
	}
	if value, ok := _u.mutation.SignalPercent(); ok {
		_spec.SetField(wifisample.FieldSignalPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSignalPercent(); ok {
		_spec.AddField(wifisample.FieldSignalPercent, field.TypeInt, value)
	}
	if _u.mutation.SignalPercentCleared() {
		_spec.ClearField(wifisample.FieldSignalPercent, field.TypeInt)
	}
	if value, ok := _u.mutation.RssiDbm(); ok {
		_spec.SetField(wifisample.FieldRssiDbm, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRssiDbm(); ok {
		_spec.AddField(wifisample.FieldRssiDbm, field.TypeInt, value)
	}
	if _u.mutation.RssiDbmCleared() {
		_spec.ClearField(wifisample.FieldRssiDbm, field.TypeInt)
	}
	if value, ok := _u.mutation.RxRateMbps(); ok {
		_spec.SetField(wifisample.FieldRxRateMbps, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRxRateMbps(); ok {
		_spec.AddField(wifisample.FieldRxRateMbps, field.TypeFloat64, value)
	}
	if _u.mutation.RxRateMbpsCleared() {
		_spec.ClearField(wifisample.FieldRxRateMbps, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TxRateMbps(); ok {
		_spec.SetField(wifisample.FieldTxRateMbps, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTxRateMbps(); ok {
		_spec.AddField(wifisample.FieldTxRateMbps, field.TypeFloat64, value)
	}
	if _u.mutation.TxRateMbpsCleared() {
		_spec.ClearField(wifisample.FieldTxRateMbps, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(wifisample.FieldChannel, field.TypeString, value)
	}
	if _u.mutation.ChannelCleared() {
		_spec.ClearField(wifisample.FieldChannel, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wifisample.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WifiSampleUpdateOne is the builder for updating a single WifiSample entity.
type WifiSampleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WifiSampleMutation
}

// SetTsUnixMs sets the "ts_unix_ms" field.
func (_u *WifiSampleUpdateOne) SetTsUnixMs(v int64) *WifiSampleUpdateOne {
	_u.mutation.ResetTsUnixMs()
	_u.mutation.SetTsUnixMs(v)
	return _u
}

// SetNillableTsUnixMs sets the "ts_unix_ms" field if the given value is not nil.
func (_u *WifiSampleUpdateOne) SetNillableTsUnixMs(v *int64) *WifiSampleUpdateOne {
	if v != nil {
		_u.SetTsUnixMs(*v)
	}
	return _u
}

// AddTsUnixMs adds value to the "ts_unix_ms" field.
func (_u *WifiSampleUpdateOne) AddTsUnixMs(v int64) *WifiSampleUpdateOne {
	_u.mutation.AddTsUnixMs(v)
	return _u
}

// SetSsid sets the "ssid" field.
func (_u *WifiSampleUpdateOne) SetSsid(v string) *WifiSampleUpdateOne {
	_u.mutation.SetSsid(v)
	return _u
}

// SetNillableSsid sets the "ssid" field if the given value is not nil.
func (_u *WifiSampleUpdateOne) SetNillableSsid(v *string) *WifiSampleUpdateOne {
	if v != nil {
		_u.SetSsid(*v)
	}
	return _u
}

// ClearSsid clears the value of the "ssid" field.
func (_u *WifiSampleUpdateOne) ClearSsid() *WifiSampleUpdateOne {
	_u.mutation.ClearSsid()
	return _u
}

// SetBssid sets the "bssid" field.
func (_u *WifiSampleUpdateOne) SetBssid(v string) *WifiSampleUpdateOne {
	_u.mutation.SetBssid(v)
	return _u
}

// SetNillableBssid sets the "bssid" field if the given value is not nil.
func (_u *WifiSampleUpdateOne) SetNillableBssid(v *string) *WifiSampleUpdateOne {
	if v != nil {
		_u.SetBssid(*v)
	}
	return _u
}

// ClearBssid clears the value of the "bssid" field.
func (_u *WifiSampleUpdateOne) ClearBssid() *WifiSampleUpdateOne {
	_u.mutation.ClearBssid()
	return _u
}

// SetSignalPercent sets the "signal_percent" field.
func (_u *WifiSampleUpdateOne) SetSignalPercent(v int) *WifiSampleUpdateOne {
	_u.mutation.ResetSignalPercent()
	_u.mutation.SetSignalPercent(v)
	return _u
}

// SetNillableSignalPercent sets the "signal_percent" field if the given value is not nil.
func (_u *WifiSampleUpdateOne) SetNillableSignalPercent(v *int) *WifiSampleUpdateOne {
	if v != nil {
		_u.SetSignalPercent(*v)
	}
	return _u
}

// AddSignalPercent adds value to the "signal_percent" field.
func (_u *WifiSampleUpdateOne) AddSignalPercent(v int) *WifiSampleUpdateOne {
	_u.mutation.AddSignalPercent(v)
	return _u
}

// ClearSignalPercent clears the value of the "signal_percent" field.
func (_u *WifiSampleUpdateOne) ClearSignalPercent() *WifiSampleUpdateOne {
	_u.mutation.ClearSignalPercent()
	return _u
}

// SetRssiDbm sets the "rssi_dbm" field.
func (_u *WifiSampleUpdateOne) SetRssiDbm(v int) *WifiSampleUpdateOne {
	_u.mutation.ResetRssiDbm()
	_u.mutation.SetRssiDbm(v)
	return _u
}

// SetNillableRssiDbm sets the "rssi_dbm" field if the given value is not nil.
func (_u *WifiSampleUpdateOne) SetNillableRssiDbm(v *int) *WifiSampleUpdateOne {
	if v != nil {
		_u.SetRssiDbm(*v)
	}
	return _u
}

// AddRssiDbm adds value to the "rssi_dbm" field.
func (_u *WifiSampleUpdateOne) AddRssiDbm(v int) *WifiSampleUpdateOne {
	_u.mutation.AddRssiDbm(v)
	return _u
}

// ClearRssiDbm clears the value of the "rssi_dbm" field.
func (_u *WifiSampleUpdateOne) ClearRssiDbm() *WifiSampleUpdateOne {
	_u.mutation.ClearRssiDbm()
	return _u
}

// SetRxRateMbps sets the "rx_rate_mbps" field.
func (_u *WifiSampleUpdateOne) SetRxRateMbps(v float64) *WifiSampleUpdateOne {
	_u.mutation.ResetRxRateMbps()
	_u.mutation.SetRxRateMbps(v)
	return _u
}

// SetNillableRxRateMbps sets the "rx_rate_mbps" field if the given value is not nil.
func (_u *WifiSampleUpdateOne) SetNillableRxRateMbps(v *float64) *WifiSampleUpdateOne {
	if v != nil {
		_u.SetRxRateMbps(*v)
	}
	return _u
}

// AddRxRateMbps adds value to the "rx_rate_mbps" field.
func (_u *WifiSampleUpdateOne) AddRxRateMbps(v float64) *WifiSampleUpdateOne {
	_u.mutation.AddRxRateMbps(v)
	return _u
}

// ClearRxRateMbps clears the value of the "rx_rate_mbps" field.
func (_u *WifiSampleUpdateOne) ClearRxRateMbps() *WifiSampleUpdateOne {
	_u.mutation.ClearRxRateMbps()
	return _u
}

// SetTxRateMbps sets the "tx_rate_mbps" field.
func (_u *WifiSampleUpdateOne) SetTxRateMbps(v float64) *WifiSampleUpdateOne {
	_u.mutation.ResetTxRateMbps()
	_u.mutation.SetTxRateMbps(v)
	return _u
}

// SetNillableTxRateMbps sets the "tx_rate_mbps" field if the given value is not nil.
func (_u *WifiSampleUpdateOne) SetNillableTxRateMbps(v *float64) *WifiSampleUpdateOne {
	if v != nil {
		_u.SetTxRateMbps(*v)
	}
	return _u
}

// AddTxRateMbps adds value to the "tx_rate_mbps" field.
func (_u *WifiSampleUpdateOne) AddTxRateMbps(v float64) *WifiSampleUpdateOne {
	_u.mutation.AddTxRateMbps(v)
	return _u
}

// ClearTxRateMbps clears the value of the "tx_rate_mbps" field.
func (_u *WifiSampleUpdateOne) ClearTxRateMbps() *WifiSampleUpdateOne {
	_u.mutation.ClearTxRateMbps()
	return _u
}

// SetChannel sets the "channel" field.
func (_u *WifiSampleUpdateOne) SetChannel(v string) *WifiSampleUpdateOne {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *WifiSampleUpdateOne) SetNillableChannel(v *string) *WifiSampleUpdateOne {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// ClearChannel clears the value of the "channel" field.
func (_u *WifiSampleUpdateOne) ClearChannel() *WifiSampleUpdateOne {
	_u.mutation.ClearChannel()
	return _u
}

// Mutation returns the WifiSampleMutation object of the builder.
func (_u *WifiSampleUpdateOne) Mutation() *WifiSampleMutation {
	return _u.mutation
}

// Where appends a list predicates to the WifiSampleUpdate builder.
func (_u *WifiSampleUpdateOne) Where(ps ...predicate.WifiSample) *WifiSampleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WifiSampleUpdateOne) Select(field string, fields ...string) *WifiSampleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WifiSample entity.
func (_u *WifiSampleUpdateOne) Save(ctx context.Context) (*WifiSample, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WifiSampleUpdateOne) SaveX(ctx context.Context) *WifiSample {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WifiSampleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WifiSampleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WifiSampleUpdateOne) sqlSave(ctx context.Context) (_node *WifiSample, err error) {
	_spec := sqlgraph.NewUpdateSpec(wifisample.Table, wifisample.Columns, sqlgraph.NewFieldSpec(wifisample.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WifiSample.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wifisample.FieldID)
		for _, f := range fields {
			if !wifisample.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != wifisample.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TsUnixMs(); ok {
		_spec.SetField(wifisample.FieldTsUnixMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTsUnixMs(); ok {
		_spec.AddField(wifisample.FieldTsUnixMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Ssid(); ok {
		_spec.SetField(wifisample.FieldSsid, field.TypeString, value)
	}
	if _u.mutation.SsidCleared() {
		_spec.ClearField(wifisample.FieldSsid, field.TypeString)
	}
	if value, ok := _u.mutation.Bssid(); ok {
		_spec.SetField(wifisample.FieldBssid, field.TypeString, value)
	}
	if _u.mutation.BssidCleared() {
		_spec.ClearField(wifisample.FieldBssid, field.TypeString)
	}
	if value, ok := _u.mutation.SignalPercent(); ok {
		_spec.SetField(wifisample.FieldSignalPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSignalPercent(); ok {
		_spec.AddField(wifisample.FieldSignalPercent, field.TypeInt, value)
	}
	if _u.mutation.SignalPercentCleared() {
		_spec.ClearField(wifisample.FieldSignalPercent, field.TypeInt)
	}
	if value, ok := _u.mutation.RssiDbm(); ok {
		_spec.SetField(wifisample.FieldRssiDbm, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRssiDbm(); ok {
		_spec.AddField(wifisample.FieldRssiDbm, field.TypeInt, value)
	}
	if _u.mutation.RssiDbmCleared() {
		_spec.ClearField(wifisample.FieldRssiDbm, field.TypeInt)
	}
	if value, ok := _u.mutation.RxRateMbps(); ok {
		_spec.SetField(wifisample.FieldRxRateMbps, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRxRateMbps(); ok {
		_spec.AddField(wifisample.FieldRxRateMbps, field.TypeFloat64, value)
	}
	if _u.mutation.RxRateMbpsCleared() {
		_spec.ClearField(wifisample.FieldRxRateMbps, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TxRateMbps(); ok {
		_spec.SetField(wifisample.FieldTxRateMbps, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTxRateMbps(); ok {
		_spec.AddField(wifisample.FieldTxRateMbps, field.TypeFloat64, value)
	}
	if _u.mutation.TxRateMbpsCleared() {
		_spec.ClearField(wifisample.FieldTxRateMbps, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(wifisample.FieldChannel, field.TypeString, value)
	}
	if _u.mutation.ChannelCleared() {
		_spec.ClearField(wifisample.FieldChannel, field.TypeString)
	}
	_node = &WifiSample{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wifisample.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
