// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/sid-technologies/vigil/db/ent/wifisample"
)

// WifiSample is the model entity for the WifiSample schema.
type WifiSample struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TsUnixMs holds the value of the "ts_unix_ms" field.
	TsUnixMs int64 `json:"ts_unix_ms,omitempty"`
	// Ssid holds the value of the "ssid" field.
	Ssid *string `json:"ssid,omitempty"`
	// Bssid holds the value of the "bssid" field.
	Bssid *string `json:"bssid,omitempty"`
	// Windows-only — derived elsewhere
	SignalPercent *int `json:"signal_percent,omitempty"`
	// RssiDbm holds the value of the "rssi_dbm" field.
	RssiDbm *int `json:"rssi_dbm,omitempty"`
	// Windows-only
	RxRateMbps *float64 `json:"rx_rate_mbps,omitempty"`
	// Windows-only
	TxRateMbps *float64 `json:"tx_rate_mbps,omitempty"`
	// Channel holds the value of the "channel" field.
	Channel      *string `json:"channel,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WifiSample) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case wifisample.FieldRxRateMbps, wifisample.FieldTxRateMbps:
			values[i] = new(sql.NullFloat64)
		case wifisample.FieldID, wifisample.FieldTsUnixMs, wifisample.FieldSignalPercent, wifisample.FieldRssiDbm:
			values[i] = new(sql.NullInt64)
		case wifisample.FieldSsid, wifisample.FieldBssid, wifisample.FieldChannel:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WifiSample fields.
func (_m *WifiSample) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case wifisample.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case wifisample.FieldTsUnixMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ts_unix_ms", values[i])
			} else if value.Valid {
				_m.TsUnixMs = value.Int64
			}
		case wifisample.FieldSsid:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ssid", values[i])
			} else if value.Valid {
				_m.Ssid = new(string)
				*_m.Ssid = value.String
			}
		case wifisample.FieldBssid:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bssid", values[i])
			} else if value.Valid {
				_m.Bssid = new(string)
				*_m.Bssid = value.String
			}
		case wifisample.FieldSignalPercent:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field signal_percent", values[i])
			} else if value.Valid {
				_m.SignalPercent = new(int)
				*_m.SignalPercent = int(value.Int64)
			}
		case wifisample.FieldRssiDbm:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rssi_dbm", values[i])
			} else if value.Valid {
				_m.RssiDbm = new(int)
				*_m.RssiDbm = int(value.Int64)
			}
		case wifisample.FieldRxRateMbps:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rx_rate_mbps", values[i])
			} else if value.Valid {
				_m.RxRateMbps = new(float64)
				*_m.RxRateMbps = value.Float64
			}
		case wifisample.FieldTxRateMbps:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field tx_rate_mbps", values[i])
			} else if value.Valid {
				_m.TxRateMbps = new(float64)
				*_m.TxRateMbps = value.Float64
			}
		case wifisample.FieldChannel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel", values[i])
			} else if value.Valid {
				_m.Channel = new(string)
				*_m.Channel = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WifiSample.
// This includes values selected through modifiers, order, etc.
func (_m *WifiSample) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this WifiSample.
// Note that you need to call WifiSample.Unwrap() before calling this method if this WifiSample
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WifiSample) Update() *WifiSampleUpdateOne {
	return NewWifiSampleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WifiSample entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WifiSample) Unwrap() *WifiSample {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WifiSample is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WifiSample) String() string {
	var builder strings.Builder
	builder.WriteString("WifiSample(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ts_unix_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.TsUnixMs))
	builder.WriteString(", ")
	if v := _m.Ssid; v != nil {
		builder.WriteString("ssid=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Bssid; v != nil {
		builder.WriteString("bssid=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SignalPercent; v != nil {
		builder.WriteString("signal_percent=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RssiDbm; v != nil {
		builder.WriteString("rssi_dbm=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RxRateMbps; v != nil {
		builder.WriteString("rx_rate_mbps=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TxRateMbps; v != nil {
		builder.WriteString("tx_rate_mbps=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Channel; v != nil {
		builder.WriteString("channel=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// WifiSamples is a parsable slice of WifiSample.
type WifiSamples []*WifiSample
